### ISSUE TITLE
Inconsistent redirect to Admin dashboard after submitting changes during curation

### ISSUE THREAD

**Issue by LoriEP** [datadryad/dryad-product-roadmap#1196]
**Bug description:**
Following changes made in #933, the redirect to the admin dash was working, however shortly after began to fail inconsistently. When curators edit and submit changes, the redirect to the admin dash is often successful, however for no clear reason, it sometimes fails and lands back to the "My Datasets" page with the banner of the DOI. No clear trends or steps to reproduce. It appears behavior has reverted to original behavior identified in #933.

**Steps to reproduce:**
Difficult to reproduce, however have multiple cases of the redirect failure:

- 10.5061/dryad.18931zcw3 01/14/2021 22:18:38 UTC

- 10.6086/D13X22 01/26/2021 01:40:01 UTC

- 10.5061/dryad.h70rxwdht 02/20/2021 01:05:06 UTC

**Expected behavior:**
During curation, a curator makes edits to a dataset metadata and/or files,
when the curator has finished the edits, they submit with notes,
following the clicking of the submit button, those changes are processed and curator should be returned to the admin dash
with the dataset information pre-populated in the search box on the admin dash

**Comment by sfisher** [comment]
Still happens, I believe, though I think low impact issue.  May have to do with multiple windows open. Redirect back after uploads are stored in the session since it may originate from multiple pages.  I believe the default is the "my datasets" page if something isn't correct in the session.

**Comment by ahamelers** [comment]
I believe this is fixed with the new admin dashboard
