### ISSUE TITLE
Items with warnings or download problems

### ISSUE THREAD

**Issue by sfisher** [datadryad/dryad-product-roadmap#1222]
I scanned the current public datasets in Merritt for items to correct.

The most common problem was mismatched sizes.  Those were originally supplied when they uploaded and most seemed fine.

2nd most common problem was % in filenames which prevented download and we'll check with Merritt about.

there were a dozen or two with other odd problems that we may want to diagnose or correct if we can that seem to be for a variety of reasons. (wrong number of deposits in Merritt, file removed but not removed from our DB, etc)

https://docs.google.com/spreadsheets/d/1i4hYFjLNQ78io04tc-1wOAy95hVRHlT4SXo-E46urPU/edit#gid=384038393

**Comment by sfisher** [comment]
I don't believe all of these are fixed and seems like it wasn't a priority to fix before.  I think we still have a few datasets or files that have some issues downloading (though very few).

**Comment by ryscher** [comment]
Funny enough, these files download just fine now that we're not going through all of the Merritt machinery. But it is probably dependent on the fact that AWS uses slashes to denote folders, similar to a filesystem. The slashes in the filenames will eventually cause problems...but they're not worth fixing until the problems actually happen.

**Comment by ryscher** [comment]
Most of these have been repaired. The remaining ones will be caught as we improve the integrity checking.
