### ISSUE TITLE
admin interface: ability to edit ORCIDs

### ISSUE THREAD

**Issue by gjanee** [datadryad/dryad-product-roadmap#1249]
Admin interface: It would be nice to be able to edit and assign ORCIDs as with any other metadata.  Currently a depositor gives us an ORCID and asks us to associate it with an author, and we have to tell them that only after the item is published will the authors receive a separate email allowing them to associate their ORCID with the deposit.  This is a roundabout way of doing things, and limits our ability as curators to help depositors.

**Comment by sfisher** [comment]
Agreed, it's annoying--though ORCID was fairly explicit with us that we shouldn't ever allow editing ORCIDs.  Still doesn't prevent us from doing so once in a blue moon if there is a good reason and there is some mixup we need to fix in our data.

I can't remember the timing of this event without reading code, but I thought co-authors were emailed after initial submission?  If not, then we may want to re-consider when they get emailed.

But this is more or less on the direction and overseeing of ORCID who states people shouldn't *ever* be manually editing ORCIDs.  They did a review of our workflow and were pretty clear that manual entry of ORCIDS was forbidden and against all their guidelines and best practices.

**Comment by bryanmgee** [comment]
@sfisher co-authors aren't emailed with the option to link their ORCIDs until a dataset is published (assuming the submitting author actually entered co-author emails); if an unpublished dataset has ORCIDs for multiple authors, it was pulled in via the Import Metadata function or an API. I think the current timing is okay as long as linking an ORCID doesn't come with any added functionality (e.g., allowing non-submitting co-authors of the same dataset to have editing privileges)
