### ISSUE TITLE
admin interface: see who is currently editing deposit

### ISSUE THREAD

**Issue by gjanee** [datadryad/dryad-product-roadmap#1250]
Admin interface: If an item is "in progress", it would be nice to see who is currently editing it, especially since it's already happened several times that somebody started editing something and then forgot about it, leaving the item in a locked state and leaving us wondering who has the lock.  (If there's already a way to see this information, apologies.)

**Comment by gjanee** [comment]
E.g., instead of just saying "In progress", display "In progress (Luis Franco)"

**Comment by sfisher** [comment]
I believe this is shown under the activity log (the little clock-looking icon).  However, we could add to the column in the table, also.
