### ISSUE TITLE
Menu display on search results page

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#1442]
When viewing search results, the About menu should go entirely in front of the map.

**Comment by ryscher** [comment]
![Screen Shot 2021-08-31 at 3 56 54 PM](https://user-images.githubusercontent.com/605143/131567973-f6432461-53f0-4c1b-8122-de915c22cc50.png)

**Comment by sfisher** [comment]
It's very difficult to position things like this now because of menu rearrangement.

I'm tempted to close, but maybe will make a `wontfix` tag for now for trivial things that might make no practical difference and we can decide if we really all agree to close them.

**Comment by ahamelers** [comment]
Fixed with the removal of maps & geoblacklight
