### ISSUE TITLE
After metadata clean up for disciplinary area (OECD) and Funding (Registry ID) -- expose search on explore data by either facet

### ISSUE THREAD

**Issue by dlowenberg** [datadryad/dryad-product-roadmap#1522]
Scott's note

---

We have funders already listed as a search facet.

We haven't added the Fields of Science.  IDK how much of a desire this is (ask a product manager!).  But it wouldn't be hard to do.  I think this is a legit desire still

**Comment by ahamelers** [comment]
Keywords are a search facet.
