### ISSUE TITLE
Optimize emails/tenant structure

### ISSUE THREAD

**Issue by dlowenberg** [datadryad/dryad-product-roadmap#1572]
- Improve auto-update of user account emails and tenants when submitters fill
	out the first page of the submission system -- may need to prompt for tenant verification
  - Make it possible for authors to attach their account to a tenant from the dashboard
  - Force submitters to periodically re-approve their member tenant (timeout after 1 year)

**Comment by ahamelers** [comment]
Replaced by #1725 and #2000
