### ISSUE TITLE
Maintenence info banner for curators

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#1645]
I edited and rebuilt these submission and they are currently still in "Processing" status
Please investigate.

Title: Are metapopulation species drivers of metacommunity structure in sandstone outcrop communities?
DOI: 10.5061/dryad.g79cnp5r5

Title: Data from: Vitamin D receptor hypermethylation and underexpression as biomarkers for pediatric adrenocortical tumors
DOI: 10.5061/dryad.2fqz612p7

**Comment by ryscher** [comment]
This is due to routine monthly maintenance. Normally, we haven't notified the curators about it, but perhaps we should...

**Comment by marisastrong** [comment]
Perhaps adding a banner to display messages indicating routine maintenance is occurring or other notifications
