### ISSUE TITLE
Allow curator PC to allow downloads to other machines

### ISSUE THREAD

**Issue by sfisher** [datadryad/dryad-product-roadmap#1811]
This would involve allowing scp or some other protocol access to the curator PC remote desktop.

It would allow curators to download previously unzipped files to a different machine for testing with other software.

IDK, this may be a duplicate ticket, but I couldn't find the other ticket.

**Comment by ryscher** [comment]
This is done. There is a web server running on the VE that allows remote acces to files. See https://github.com/datadryad/dryad-app/blob/main/documentation/external_services/curator_pc.md#web-access-to-data-files
