### ISSUE TITLE
Add "Article DOI" Field to "Internal Data" section of the Activity Log

### ISSUE THREAD

**Issue by Ariana-Orona** [datadryad/dryad-product-roadmap#1943]
Journals will frequently reach out to notify us that the related manuscript has been accepted and, normally, also provide the article DOI. If a dataset is in "Submitted" status and a note is left to add the article DOI during curator, the "Last Modified" date is updated and the dataset is pushed further back in the queue. The example here ([10.5061/dryad.xsj3tx9j9](https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=%2210.5061%2Fdryad.xsj3tx9j9%22&sort=relevance&commit=Search)) is also shown below.

Before note:
![Before](https://user-images.githubusercontent.com/80363462/186478890-7e53c79d-2688-4cf6-89ce-5a6a8148c270.png)

After note:
![After](https://user-images.githubusercontent.com/80363462/186478940-4212f6d4-d7e0-43dc-bc6b-43f326c12634.png)

Additionally, when lifting the "Embargo" status on a dataset to make the data files publicly available, we have to add the associated article DOI. This involves adding the DOI to the submission form, waiting for the dataset to finish processing, and then publishing the dataset. This may be especially difficult to do if the dataset is older and does not have certain required fields.

To add the article DOI to "Submitted" datasets without updating the dataset's position in the queue and to save time lifting the "Embargo" status on datasets related to a published article, we are requesting the option to add the article DOI to the "Internal Data" field of the "Activity Log."

I have removed the information from the photo below but, essentially, the "Article DOI" field should act similarly to the "Manuscript Number" field. 

![image](https://user-images.githubusercontent.com/80363462/186479445-db62a307-4489-4735-b131-f17561a79b05.png)

So, when adding the article DOI to the "Internal Data" the information should also populate in the submission form and a "Related Works" link should be created on the dataset landing page. I am unsure if the logic would make it so that, when the article DOI is added, a link is automatically created so we would also have to be sure that adding the article DOI to the "Article DOI" filed in the "Internal Data" did not result in duplicated links in the "Related Works" portion of the dataset landing page.

**Comment by ryscher** [comment]
Internally, we have removed publicationDOI in favor of the related works. We should probably rethink this interface to be more reflective of how the internal content is handled now.

**Comment by ahamelers** [comment]
I think this is resolved with the changes to related works over publicationDOI and auto publication of minor edits
