### ISSUE TITLE
Revisit permissions vs roles

### ISSUE THREAD

**Issue by sfisher** [datadryad/dryad-product-roadmap#1989]
We started out with only a couple of roles but the number keeps growing and requires code changes for every new one or change to existing role permissions.

We may want to go to a more granular permissions model to make fewer code changes in the future if we can come up with a sensible list of permissions.  The roles may then map to a set of permissions which could be how we do checks in the code rather than directly on the role and permissions could be changed in the database easily.  I'm thinking of a "role to permissions" type of mapping table.

Examples of permissions which I'm sure isn't a final list.  We'll probably need to look at how we currently differentiate things and think a little about how we want to in the future.

First step we'd have to get a list of actions we want to differentiate like the following (which isn't fully baked).

- Edit All Datasets
- Edit Tenant's Datasets
- Get Dataset assigned for curation
- Update curation state
- Take dangerous actions
- Update Salesforce
- Update Internal Data
- View reports
- Edit User Information (for merging/changing user role, etc)
- Edit Journals (?)
- Change payment (?)
- Others?

**Comment by ryscher** [comment]
- view admin pages (e.g., for Merritt team to see our Merritt status page)

**Comment by ryscher** [comment]
Related update: the `Tenant administrator` role currently has too many permissions on the `Activity log` page. It seems reasonable for them to be able to `Add note`, but they should not be able to `Create salesforce case` or `Add data`

**Comment by ahamelers** [comment]
A list of currently open tickets around roles & permissions:

- https://github.com/CDL-Dryad/dryad-product-roadmap/issues/1941
- https://github.com/CDL-Dryad/dryad-product-roadmap/issues/1959
- https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2032
- https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2081
- https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2134
- https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2228
- https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2287

Bonus somewhat-related tickets around tenant association:

- https://github.com/CDL-Dryad/dryad-product-roadmap/issues/1572
- https://github.com/CDL-Dryad/dryad-product-roadmap/issues/1725
- https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2000

**Comment by ahamelers** [comment]
I've started building a big permissions table: https://docs.google.com/spreadsheets/d/1slzcQOjqWnQSQfkwl720TLdl2Y8XMOzy9ANb5JOhqwA/edit?usp=sharing

Could use help perfecting it @ryscher @sfisher

**Comment by sfisher** [comment]
Thanks for doing this, Audrey.  I added a couple comments and IDK how helpful they are.

I think what you have reflects how things work as far as I'm aware (and without rechecking all the code).

I guess another question we can think about is how we'd like things to work in a more ideal world.  Like right now it feels like some of the more experienced curators have 'superuser' access which is fine since we trust them but in an ideal world they might have an additional role that is separate (which might leave out mananging the queues).

The API access also has a few wrinkles.  I don't really remember how it all works.  Each API account is associated with a user and that user has a role, but I think some publisher's have special additional permissions to set something for associating with a different user.  I think Ryan will remember details better without having to read code.

Another API OAuth mode is much more traditional and if some outside publisher uses it (RSpace) then the individual user is asked to verify access something like "RSpace would like to use your account for dataset creation" (authorize or not).  This is a much more standard model such as you've seen google/facebook use and it can also have special scopes passed to the authorization to say what access the user is granting.

**Comment by ahamelers** [comment]
I've begun spinning off subtask tickets for this.

**Comment by ahamelers** [comment]
Waiting for merge of https://github.com/CDL-Dryad/dryad-app/pull/1594
