### ISSUE TITLE
Clarify relationships between tenants, affiliations, and payments

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2000]
This is related to:
- #1725
- #1998

Authors are confused that they are asked to pay despite entering an Affiliation for an institution that is a member of Dryad. They do not understand that there is a difference between an Affiliation and their Tenant.

Curators can be confused when they update a Tenant in the User Management page and the payment information for associated datasets does not update. 

Thoughts on potential improvements:
- [ ] When a Tenant is changed on the User Management page, update the payment information for in-progress datasets. (We could update the Tenant assigned to the resource, but not if one of the two Tenants is a UC)
- [x] Make the Tenant setting more explicit for users. Yes, they should see the big logo when they have a tenant, but the lack of a logo doesn't mean much for them. Perhaps they could see it and request a change on a Profile page?
- [x] Allow users to change their tenant as in #1725
- [ ] Warn users when they select an Affiliation that does not match their Tenant

**Comment by ryscher** [comment]
When a user logs in to a tenant, their affiliation defaults to the tenant's `long_name`. If this name does not match the name in ROR, it will cause a mismatch in the submission system's autocomplete, and users will have to delete the name from the autocomplete in order to fill it in "correctly".

**Comment by ahamelers** [comment]
Waiting on merge of https://github.com/datadryad/dryad-app/pull/1623 for next steps

**Comment by ahamelers** [comment]
Blocked while we discuss #3337 for the following items:

> When a Tenant is changed on the User Management page, update the payment information for in-progress datasets.

If we are asking the user to reauthenticate their SSO for each submission, thus confirming their tenant for each submission, we probably don't want to change the tenant for submissions afterward, as the user may have authenticated with some other tenant on purpose!

> Warn users when they select an Affiliation that does not match their Tenant

Similarly, if they've JUST reauthenticated their SSO and confirmed their tenant, do we need to warn them if their affiliation doesn't match?
