### ISSUE TITLE
Manage cutoff dates

### ISSUE THREAD

**Issue by sfisher** [datadryad/dryad-product-roadmap#2006]
We have readme of any kind with one date and requiring readme.md as another date.

We will get more cutoff dates so maybe consolidate into the database or someplace else to track the differential handling for different dates.

(Or I would love to avoid differential handling if it's feasible because it makes our code more complex, prone to errors and it's also a pain to track many different policies for different people and rather have a unified handling, requirements and policies.)

**Comment by ahamelers** [comment]
Closing in favor of #3106
