### ISSUE TITLE
Clean feature branches

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2013]
Clean old feature branches from GitHub and ensure our process deletes branches as features are integrated into `main`.

**Comment by ahamelers** [comment]
I have deleted any branches that git *knows* have already been merged—meaning, they are easily retrievable from the git history if I shouldn't have deleted them 😄 

@ryscher @sfisher , if you could each go through your remaining stale/inactive branches and evaluate whether they can be deleted, that would be most helpful.

Someone with admin access can make deleting on merge an automated process: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

I do not have the necessary access to do so.
