### ISSUE TITLE
Keep revision history for Internal Data

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2024]
We sometimes run into issues with tracking the history of a dataset because the Internal Data can be changed without leaving a revision history. 

The fields in Internal Data were originally separate from the main metadata because they are more "administrative" and do not fit into the Datacite model. Unfortunately, this choice meant that we do not have an easily-accessible history.

Possible ways to introduce a history:
1.) Make the Internal Data part of the "regular" metadata, and version it alongside everything else. This may be tricky, since we need to handle all of the legacy content.
2.) Add a new table specifically to record changes to the Internal Data
3.) Whenever Internal Data changes, automatically record a note in the Curation Activity log.

**Comment by ahamelers** [comment]
# 3 was done in as part of fixing #3473 in https://github.com/datadryad/dryad-app/pull/1755

But I think a combination of # 1 and # 2 is preferable (make a new table, copy over all the info we want to maintain version [publicationName, publicationISSN, manuscriptNumber] and version it with the resource along with everything else)
