### ISSUE TITLE
Large zip file downloads (thinking and next steps)

### ISSUE THREAD

**Issue by sfisher** [datadryad/dryad-product-roadmap#2065]
https://github.com/CDLUC3/mrt-doc/issues/1246

This issue may be something Dryad wants to address, also.  It could be a collaborative ticket, so we should reference it on our project board, also.

**Comment by ryscher** [comment]
From Terry: Merritt Stage (UI and Access Servers) now supports requests for uncompressed zip files.  Add "format=zipunc" to the assemble-obj and assemble-version endpoint calls.  If you have a chance to give it a try, let us know.

**Comment by sfisher** [comment]
We've moved to uncompressed zips a this point which is a step in the right direction, but we may want to still evaluate other solutions that may mean we (or Merritt) don't have to create zip files on a server which causes a lot of load.

**Comment by ryscher** [comment]
- UX wants the ZIP link to be less prominent
- Curation wants individual files to be more prominent (e.g. #520)
- Merritt would like to reduce the load on their access servers by adding “more friction” to users before selecting ZIP creation
