### ISSUE TITLE
Add PPR column to 'Journals' webpage

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#2076]
Please consider the following suggested updates to the '[Journals](https://datadryad.org/stash/journals)' page on the Dryad website. 

1) Add new column titled "Automatic PPR" (or something similar). 
For integrated journals that have the auto-PPR feature configured, the cell should contain "true". 
For those titles that do not have it enabled, the cell should contain "false".
Additionally, please make the column sortable.

Having this information easily accessible will allow curators to better troubleshoot status questions/issues and confirm journal-specific configurations. 

2) The [Payment Plan](https://datadryad.org/stash/journals?direction=asc&sort=payment_plan_type) column contains following information for each journal: "SUBSCRIPTION", "DEFERRED", "[blank]". It would be easier to interpret this information if there was an explanation for these terms (including the blank cells) or different text options such as: 

"SUBSCRIPTION" with = "journal sponsored"
"DEFERRED" with = "publisher sponsored" _(Note: need to double-check my understanding!)_
[blank cell] = "no sponsorship"

**Comment by ryscher** [comment]
- SUBSCRIPTION = Fee is paid up front, based on estimated usage. May be a single journal, society, or publisher.
- DEFERRED = Slightly higher fees are paid after data is published, based on actual usage. Currently, this is only used by publishers, but in the past it was used by some individual journals.

**Comment by jleighherzog** [comment]
@ryscher : Curators reference that page to determine whether cost is covered and we also point authors to that page. So, because it's external facing, I think it would be helpful to clarify what the columns mean and the text within the columns.

**Comment by jleighherzog** [comment]
Revisiting this ticket: 
Please consider the following suggested update to the '[Journals](https://datadryad.org/stash/journals)' page on the Dryad website.

Add new column titled "Automatic PPR" (or something similar).
For integrated journals that have the auto-PPR feature configured, the cell should contain "true".
For those titles that do not have it enabled, the cell should contain "false".
Additionally, please make the column sortable.

**Comment by ahamelers** [comment]
@jleighherzog Please see https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2709 & provide comments!
