### ISSUE TITLE
Build web-to-lead as a proper form

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2093]
(Low priority, only needed if the form gets a lot of use)

The "interested" form (https://github.com/CDL-Dryad/dryad-app/pull/983) was built using Salesforce's Web-to-Lead functionality. This implementation is a useful first pass, but if we really want to keep the form, it could be greatly improved.

- [ ] Make the form submit to a Dryad controller instead of Salesforce
- [ ] Have Dryad use the Salesforce API to create a Lead object, rather than using the clunky field ID numbers that are in the current form
- [ ] Give the user feedback about required fields
- [ ] Provide an actual message when the CAPTCHA fails, instead of pretending it succeeded (seriously, why does Salesforce still redirect to the success page when it fails?)

**Comment by ahamelers** [comment]
After evaluation Sarah has decided to remove this form.
