### ISSUE TITLE
Evaluate Zenodo Data Replication

### ISSUE THREAD

**Issue by sfisher** [datadryad/dryad-product-roadmap#2095]
We've temporarily disabled replication over 50GB and this has increased stability a lot.  Still leaving this here in case we decide to revisit that decision later.

---

Data replication over 50GB is problematic to get to go in to Zenodo.  While they extended the limits by changing a setting for us, almost all of the items in this class fail when we try them (a couple have gone in after repeated tries).  The 200-300GB ones also take up spots in the queue and then fail after 24 hours and delay the items waiting behind them in line.

They also require developer intervention to avoid retrying and repeating the problems.

Zenodo data copies were never really considered a full copy (for better or worse) since it only stores the latest published version of a dataset rather than the full history or any previously published version.  This was by design and based on the requirements and discussion of our original meetings.

If we want this to work reliably, we should engage in tasks like:

- [ ] Work with Zenodo to ensure they can take up to 300GB and determine how long a dataset such as that would be expected to take to go in.  Also be sure their servers and other things have appropriate timeouts and similar.  (Since their main use case is 50GB limit they likely don't design things for 300GB.)
- [ ] Work with our own system to be sure we have an adequate timeout to accommodate the expected length of time it would take to send something like this to Zenodo.
- [ ] If we want this to go in faster for large items we may need some way of sending parts in parallel, which would be a major change.
- [ ] The large items probably need their own "slow and bulky" queue if we don't want to delay smaller items from going in more quickly in the express lane.

Or

Stop sending data or data over 50GB to zenodo.

**Comment by ryscher** [comment]
We have stopped sending data replicas to Zenodo -- https://github.com/datadryad/dryad-app/pull/1763
