### ISSUE TITLE
Update "Our platform" section

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2164]
This section is out of date.

- It mentions things like SWORD and GeoBlacklight that we're not using in standard ways. (Feb 15 2023, a potential customer asked if they needed to be SWORD-compliant!)
- The architecture diagram hasn't been updated in years
- The feature list could be revamped

---

- [x] add ROR
- [x] remove OAI-PMH
- [x] remove ResourceSync
- [ ] update the relationship between Shibboleth and ORCID
- [ ] ?? update the names and descriptions of Store/Harvest/Share, which don't really correspond to our internal structure
- [ ] add API
- [ ] add journal integration
- [ ] add COUNTER
- [ ] ?? add curation virtual environment
- [ ] ?? say something about dashboards for members

**Comment by ahamelers** [comment]
I've put the section content in a google doc and made it available for @ryscher and @sfisher to edit: https://docs.google.com/document/d/1iw-LLHzLD5aFOCoS2iEQJUFEWhrcllZS4Hbzm06bV-M/edit?usp=sharing
