### ISSUE TITLE
Ecological Monographs: metadata

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#2296]
**Priority**: Low 
**Impact**: Not sure. For these datasets, I don't find any messages in the Activity Log that indicate any auto-processes for the integration are actually working (no journal status updates in the notes, etc.)  
> 10.5061/dryad.pvmcvdnqc
> 10.5061/dryad.612jm646w

**Bug description:**

Based on the dates in the "Metadata Last Received" column, Dryad has not received metadata for _Ecological Monographs_ since December 1, 2022. Jess will follow up with Heather Carlo today. But, attached are some screen captures here that might be helpful for investigation. The details for each email look a bit different. 

**1) The metadata was successfully received on 12/1/2022:** 

![Screenshot 2023-02-15 at 9 30 12 AM](https://user-images.githubusercontent.com/76497320/219073858-947990cc-56b9-4efb-8f1e-991873090d36.png)

**2) A message that came through to the Gmail account on 01/11/2023 but was _not_ registered as having been received (10.5061/dryad.612jm646w)**

![Screenshot 2023-02-15 at 9 29 24 AM](https://user-images.githubusercontent.com/76497320/219073862-4f6e9dd0-8e2b-463d-9fde-d3de7da4eaf2.png)

**Comment by ryscher** [comment]
Metadata is flowing now. Last received today: 2024-07-16 14:30:12 UTC
