### ISSUE TITLE
Review system configuration for unassigned datasets

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#2328]
**Priority**: Low (datasets aren't often unassigned)
**Impact**: Need to ensure no submissions get lost or left unassigned in error. Need to accurately track actions. 

When a curator attempts to unassign a data submission, an error message appears AND there's no note in the activity log that an action was taken to unassign (there used to be). Can you investigate? 

Bryan has provided a video of what the process looks like for him. The gist is: 
1. Dataset returns to Bryan from AAR, logged in Activity Log
2. Bryan attempts to unassign the dataset from his account
3. System gives error saying you can't do that, BUT when the page is refreshed, it shows all of Bryan's datasets in 'Curation' status, the dataset that was unassigned disappears
4. If Bryan searches on all datasets in 'Curation' status, the dataset appears but Bryan is not assigned
5. If we check the Activity Log, there is no record of that unassignment
_Note: Also might be useful to check reassignment to ensure there's a note. When Curators transfer submission to another Curator to handle._

https://user-images.githubusercontent.com/76497320/220996474-dee2644b-b6bf-46ff-b850-eedd09d1f59e.mov

**Comment by bryanmgee** [comment]
Tagging onto this, I tried unassigning myself from a different [dataset](https://datadryad.org/stash/ds_admin/activity_log/86647?) that was in Curation because I had picked it up, edited the metadata, and resubmitted, _but_ had never sent it back to the author. The system allowed me to do that without the error message, changed the dataset status to 'Submitted,' and did log that action in the Activity Log

**Comment by ahamelers** [comment]
@jleighherzog Is this still an issue? As far as I can tell assignment is working fine (particularly on the new admin dashboard)

**Comment by jleighherzog** [comment]
I just tested the 'unassign' feature and it works for me. No error message.
