### ISSUE TITLE
UI and UX for compressed files

### ISSUE THREAD

**Issue by sfisher** [datadryad/dryad-product-roadmap#2349]
I believe we were looking at having the new landing page evaluated and fleshed out by UX https://www.figma.com/file/3qCbyYq7O221nvrHFzWn7z/Dryad-New-Look?node-id=102%3A .  This is just one part of the page.

---

According to notes from Karthik

## On the web
Once a submission has been published, create a new field called file_manifest and display a sorted list on the website. To avoid clutter to the interface, this would appear in a separate tab (More on this in a future UI issue collection).

## Via the API
Also by exposing this information via an endpoint, like so:

```
/datasets/doi/manifest
```

---

I'm assuming this "file manifest" appears under one of the tabs pictured on https://www.figma.com/file/3qCbyYq7O221nvrHFzWn7z/Dryad-New-Look?node-id=102%3A2 .  Probably the "file preview" tab? (that is often how operating systems show what is in zip files or allowing navigation with a file explorer into them).  Or possibly all the files inside zips also appear in the "files" tab?  But I think Files here are designed to be downloaded directly.

**Comment by ahamelers** [comment]
Closing in favor of #3624, #2983
