### ISSUE TITLE
API: Error message for invalid userId

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2399]
(reported by Weill Cornell) 

When submitting a dataset via the API, if the userId does not match one of the listed authors on the dataset, the error message may be misleading.

For example, this submission:
```
"authors": [{
"firstName" : "a",
"lastName" : "b",
"email" : "a@b.com",
"affiliation" : "aaaa"
}],
"userId": 3412341
```

Resulted in an error stating the author's email address was not present.

**Comment by ryscher** [comment]
This is a side effect of Dryad automatically adding the submitter as an author. If the submitter's email OR affiliation is missing, the "missing email" error will be displayed.

**Comment by alinvetian** [comment]
The current behaviour has changed and sending a `userId` value that is not part of the authors list, raises a`400 Bad Request` error with message `The userId orcid is not known to Dryad. Please supply a matching orcid in the dataset author list.`
