### ISSUE TITLE
Allow Superusers to withdraw data submissions from any status

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#2544]
_Note: Ryan & Jess discussed. Will address this ticket post-transition_

The Dryad Helpdesk frequently receives requests from authors to "remove" or "withdraw" datasets. For example, duplicate submissions identified or submissions related to manuscripts that were rejected in peer review. Authors have the ability to delete their submissions from their Dryad dashboard but, it would be easier to allow Dryad Superusers the option to:

1. withdraw datasets from any status (including "In Progress" with the author), or
2. allow option to proxy into the submitting author's account to withdraw submission (and leave a note)

In some cases, in order to withdraw a submission, Curators are required to use the Force Edit option to return the submission to an editable status. This workaround requires time to resubmit, rebuild, and set the final status for each submission. Additionally, while the status changes, authors might receive a flurry of conflicting status updates in their email inboxes.

**Comment by bryanmgee** [comment]
In particular, it would be ideal if superusers could delete datasets that are specifically "In Progress" and **that have never been submitted**. We are seeing a lot of these with AAAS submissions where an author leaves it in editing mode and then the manuscript is desk rejected or where they somehow create a duplicate (or triplicate) in the manuscript submission system and at least one is never submitted. These users are either unfamiliar with our site and don't know how to delete unsubmitted datasets themselves (which requires HD to explain it to them) or they just ignore the email with instructions.

**Comment by mahirst** [comment]
What's the progress on this one? It is becoming a time-suck for curators.
