### ISSUE TITLE
Review changes needed for DataCite 4.5

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2552]
https://datacite-metadata-schema.readthedocs.io/en/4.5/introduction/version_update.html

**Comment by ryscher** [comment]
The [4.5 schema is now released](https://datacite.org/blog/introducing-datacite-metadata-schema-4-5/). It looks like very little will affect us, but it would still be good to review, and then update the metadata we are sending.

**Comment by ahamelers** [comment]
The only change here we may want to take advantage of is sending our own publisher ROR ID to datacite—this would require editing and releasing a new version of the datacite-mapping gem https://github.com/CDLUC3/datacite-mapping
