### ISSUE TITLE
Related Work URL field cutting off URL with brackets

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#2554]
**Bug description:** I tried to add this DOI as a Related Work (article) to a dataset 
https://doi.org/10.1890/0012-9615(2001)071[0277:ECACDI]2.0.CO;2  but the system truncates it as https://doi.org/10.1890/0012-9615(2001)071 which breaks the link. The dataset is https://datadryad.org/stash/dataset/doi:10.5061/dryad.qjq2bvqmp 

**Steps to reproduce:** It appears to happen when a DOI/URL is entered which has square brackets in it. It just cuts off before the first one.

**Expected behavior:** Retain the whole URL so that the link works. Currently, it links to a non-existent URL.

**Comment by ryscher** [comment]
Scott fixed the immediate problem, but if people insist on creating DOIs with stupid characters, we should try to handle them  gracefully.

**Comment by jleighherzog** [comment]
Jess contacted Heather at ESA to communicate the issue (June 9)
