### ISSUE TITLE
Infill journal ISSNs (stash_engine_journal_issns)

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2578]
Many older datasets have ISSNs that don't match the ISSNs listed for current journals. This can cause `Identifier.journal` to give unexpected results. To fix, we need to update older journals to have multiple ISSNs.

To identify the ISSNs that are missing:
```
ii = StashEngine::Identifier.where(pub_state: 'published')
ii.each do |i|
    if i.journal.blank? && i.publication_issn.present?
        print "#{i.identifier} -- #{i.publication_issn}\n"
	end
end
```

**Comment by sfisher** [comment]
This post at https://community.crossref.org/t/how-do-i-find-all-issns-assigned-to-a-journal-title-in-crossref/3447  suggests downloading the titles or titles.csv file and just matching on title to get all the ISSNs.  Not sure if that helps.

**Comment by ahamelers** [comment]
I think I've incidentally gotten most of these doing #3694 (as part of #3710).
