### ISSUE TITLE
Investigate automated emails to link ORCIDs

### ISSUE THREAD

**Issue by bryanmgee** [datadryad/dryad-product-roadmap#2595]
Helpdesk has periodically received emails about authors not receiving the emails to link their ORCID to a dataset (when their email was provided by the submitting author). In the last month, this issue has now been identified for authors from UC Davis, UC Merced, and UW Madison (all member institutions) and seems to be happening to people who (1) have previously received emails for this purpose, so they know to expect it and what to look for; (2) do not seem technically challenged like some authors; and (3) happens repeatedly to these authors and is usually documented for all co-authors of a given dataset. The curation team has not identified any systemic issues with emails from our system being blocked by these institutions (contrasted with Stanford, for example), including emails sent to some of these authors from SF.

- [SF 25342](https://dryad.lightning.force.com/lightning/r/Case/5003h00000cKovlAAC/view)
- [SF 22663](https://dryad.lightning.force.com/lightning/r/Case/5003h00000bUPt6AAG/view)
- [SF 22592](https://dryad.lightning.force.com/lightning/r/Case/5003h00000bUGbhAAG/view)
- [SF 22858](https://dryad.lightning.force.com/lightning/r/Case/5003h00000bUk5CAAS/view) (possibly this is related to the datedness since the datasets were published; i.e. they deleted the emails)

It would be helpful to test the functionality of these emails and perhaps to see if they are coming from a gibberish-type email address (like the invoice emails) that could appear more 'spam-y' in nature and thus be intercepted in contrast to standard SF emails sent by curators.

**Comment by DragosIorgulescu** [comment]
Goals:
- update documentation on the invitation flow and better detail it
- determine how invitations and links are generated
- discuss next steps to see if we can avoid spam filters

**Comment by mahirst** [comment]
Another case: SF32925

Author is affiliated with Harvard University

**Comment by ryscher** [comment]
Audrey may have fixed this

**Comment by ryscher** [comment]
I believe this is working as expected now.
