### ISSUE TITLE
Targeted user testing -- data scientists

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2621]

**Comment by ryscher** [comment]
Blocked waiting for us to acquire data scientists in our test group.

**Comment by ahamelers** [comment]
- [ ] Create initial (simple) data scientist survey
- [ ] Send out email to user testers saying "Please fill out this survey if you are a data scientist!"
- [ ] Record responding users as data scientists for future targeted surveys

**Comment by ahamelers** [comment]
I sent the email! Will tag any survey respondents as "Data scientists"
