### ISSUE TITLE
Monitoring for new UI servers

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2634]
- [x] servers running (static help page)
- [x] database connection (dynamic page, such as journals)
- [x] disk space
- [x] cpu usage
- [x] memory
- [x] add an alert to the ALB Target group - when an instance transitions to unhealthy
- [x] add al alert for cost overage, ideally when we go over ~$350/day

**Comment by ryscher** [comment]
Dragos is working on an AWS dashboard, which will be useful. But we also want notification to the SNS topic [DryadAdminUrgent](https://us-east-1.console.aws.amazon.com/sns/v3/home?region=us-east-1#/topic/arn:aws:sns:us-east-1:708974194505:DryadAdminUrgent)

**Comment by ahamelers** [comment]
Is this completed or still in progress?

**Comment by ryscher** [comment]
Validated existing alarms, added a few more high-level alarms.
