### ISSUE TITLE
Reformat and link to Journals page

### ISSUE THREAD

**Issue by ahamelers** [datadryad/dryad-product-roadmap#2709]
In looking at restructuring the FAQ and other help page information to be more valuable to users, Bryan has asked what the status is of the journals page (https://datadryad.org/stash/journals) and if it should, or could once again, be made publicly available.

The curators have previously pointed users to this page to help them figure out if their submission is covered or to help define "integrated" journals, which are referred to throughout the FAQ.

- For this purpose, we could change the page to be more user friendly, translating system/dev terms to plain language, and edited to include some of the information from this spreadsheet the curators now refer to when telling users about integrated titles: https://docs.google.com/spreadsheets/d/1oLtBonVorHx7MdiA3PzVJb9NFaWLk73dIZM1bLKkcBQ/edit#gid=1538219073
- If other admin users use this page for different purposes, we may want to programmatically adjust what is shown on the page depending on whether or not the user is logged in and their role.

The first step would be to ask the rest of the Dryad staff who uses this page, and why, to gather requirements.

**Comment by ryscher** [comment]
Ensure that journals who only use the API will show up on the page as well.
