### ISSUE TITLE
Make geographic_authors_report runnable regularly

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2716]
This report takes too long to run, and the contents only change meaningfully for new datasets.

- Change the report so it runs on a particular time period (similar to the shopping_cart_report)
- Run it for the applicable time periods
- Ensure we have a process to run it regularly in the future (add to the monthly tasks for shopping_cart_report? or make a recurring ticket?)

**Comment by ahamelers** [comment]
See if the report can be replaced by functionality of the new admin dashboard (https://github.com/datadryad/dryad-app/pull/1703)

If not, how does the dashboard need to change to replace this report?

**Comment by ryscher** [comment]
Yes, the dashboard functionality should work fine for this purpose.
