### ISSUE TITLE
GREI -- monthly reporting

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2736]
Monthly metrics report of NIH-funded research. Report should be PDF, to be easily digestible by program officers.

Metrics to be included in monthly report:
- New and total numbers of items affiliated with NIH funding
- New and total amount of storage used by items affiliated with NIH funding
- Total numbers of items, views, downloads, and citations
- Average numbers of views, downloads, citations per item
- List of unique item types and total number of items per item type
- List of unique license types and total number of items per license type
- Frequency of citation counts for cited items (i.e. how many items are cited 1 time, 2 times, 3 times, etc.)

Include summary graphs to show trends:
- Total items per month
- Total storage per month

**Comment by ryscher** [comment]
Estimated -- 2 days work

**Comment by ahamelers** [comment]
- By "item" Ryan means a dataset. Each dataset gets a DOI and is represented in our database in the `satsh_engine_identifiers` table. Each time a dataset is revised it gets a new version, in the `stash_engine_resources` table. Most metadata/information/other connections about a dataset is linked on the resource level
- Dataset funders are recorded in the `dcs_contributors` level, they have `contributor_type` funder.
- All the funders/contributors which are part of the NIH are listed in a JSON object in the `dcs_contributor_groupings` table. The NIH is the only thing there (for now), the ROR entry is the one to pay attention to (the crossref one is there for historical reasons). The JSON list is pretty much just the list of Child Organizations from this ROR record: https://ror.org/01cwqze88
- `stash_engine_counter_stats` has the views/citations/downloads, check our existing code for how the table translates to that data
