### ISSUE TITLE
Templatize README template

### ISSUE THREAD

**Issue by ahamelers** [datadryad/dryad-product-roadmap#2751]
@jleighherzog 
> Looking at it now, I think it would be useful to place the instructions/guidance outside the template. I worry users might be confused as to where to begin to input their info and whether to keep the instructional text.

>Not this, but something like it:
![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/1749394/6b4c4e53-1735-4e21-bac9-0bbed42b7d2d)

---

There are a lot of design options, but to begin with we need the template itself (a markdown file) and the instructions meant to accompany it.

Working document
https://docs.google.com/document/d/1_Lg3xtLFwFbOI697bIuBPPLpQKqYLJ5I7j8UXVlXyIQ/edit

**Comment by ryscher** [comment]
Waiting for curator input.

**Comment by ahamelers** [comment]
The CDL UX team has shared some additional recommendations we may want to work on derived from user testing:

- In the help/documentation, prominently feature at least two examples of good READMEs: one for a simple tabular dataset with just a few files and one for a complex submission including code. Authors didn’t seem to have a problem with examples from outside their fields. 
- To clarify data description vs. README, consider putting a one- or two-sentence description of the contents / purpose of the page at the top of the Describe dataset page. E.g., something to the effect that this is to help people find your dataset and understand how it connects to publications, people, and other datasets. Then, on the README page, emphasize that it’s to help people use your dataset and should have all the details they need, etc. etc.

**Comment by jeremywalter** [comment]
From the current template, rather than requesting freeform and giving instructions that can be easily misunderstood/interpreted I suggest the following:

**Description of the data and file structure**
1) What files are in your Dryad data submission?

2) Define variables (including measurement metrics) for data in your submission.

**Code/Software**
1) What free/open software is needed to view your data?
2) If code/scripts are included with your submission, describe them here.

**Comment by ahamelers** [comment]
The new README editor opens up a lot of display options for instructions, I can add widgets and tooltips as required.

**Comment by jleighherzog** [comment]
@jeremywalter : Can you populate this ticket with the proposed edits, please?

**Comment by jeremywalter** [comment]
https://docs.google.com/document/d/1y5Z-yiSDZ5Sf7Qh_Nuinje-wnuUQFmm_HPRWkueDzBk/edit?usp=sharing

Here is a working document with 3 proposed versions. The last is the current template with a comment that could be used to highlight specific pain points.

**Comment by bryanmgee** [comment]
Following up on the dev/curator meeting today, it would also be good to add checks looking for retention of the template (or most of it) to get around people submitting the blank template with a space added somewhere to bypass the existing check

**Comment by jleighherzog** [comment]
@rcurty has suggested that we display each major heading within the README template (page 2) into separate sections, individual free-text fields with the option to link to 'Help' for each section (could link to a relevant Help page or hover-over example). Additionally, some fields can be made mandatory. Still, all fields should be combined to render a comprehensive .md file.

**Comment by ahamelers** [comment]
None of our good README examples (in the blog post above) are viewable on the page as HTML. Do we have any good README examples from this modern era? Would be easier to link to directly
