### ISSUE TITLE
GREI 1.3.7 Auto-approve simple version changes

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2754]
Some changes to published datasets are so simple and obvious that they don't need a curator's review. 
- [x] Develop a list of these changes
- [ ] Build code that allows auto-approval of versioned datasets that only have these changes

**Comment by ryscher** [comment]
@bryanmgee @lauradryad @jleighherzog I started a [list of potential auto-approvals](https://docs.google.com/document/d/1CuO4FdkWQTkGneeGTn3K31sv2v7rxmpKVCzz4d9FiUE/edit?usp=sharing) for your comment.

**Comment by ryscher** [comment]
Discussed the auto-approvals with the curation team. They agreed with everything except updating on author changes.

**Comment by ahamelers** [comment]
This would be when a new version is created for an already published dataset

**Comment by DragosIorgulescu** [comment]
Need to be aware of validations before publishing, as there is a callback in the curation activity which may fail otherwise

**Comment by ryscher** [comment]
The status updater runs from `lib/tasks/merritt_status.rake`, but the flow of control is a little confusing. The actual work of setting the status is performed in `Resource.prepare_for_curation` and `Resource.create_post_submission_status`.
