### ISSUE TITLE
Measure the publication gap

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2769]
To wrap up the projects with Metadata Game Changers, we want to collect statistics on the effectiveness of our recent changes regarding links between datasets and articles.

- Determine the percentage of datasets that are lacking a link to a `primary_article`
- Compare this percentage to last year's reports from Ted
- Determine whether we need to measure this percentage regularly

**Comment by ahamelers** [comment]
I've added this to the [metadata completeness calculations](https://docs.google.com/spreadsheets/d/1F1jof98qP45UXxmNmjSzhkq98oxBMVNanQ33EYfgVZY/edit#gid=1489168011). 42.69% of all submissions and 65.46% of published datasets have a primary article.
