### ISSUE TITLE
PubUpdater tweak -- removing from PPR

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2774]
If a published article is matched to an unpublished dataset, automatically send an email to the submitting author to notify them and request whether to continue and/or provide instructions to withdraw (check to ensure they can withdraw from PPR status)

**Comment by ahamelers** [comment]
Email draft:

```html
<p>Dear <%= @user_name %>,</p>

<p>A published article has been linked to your Dryad data submission ("<%= @resource.title %>"). As your manuscript is no longer under peer review, your data submission is ready to enter our curation process.</p>

<p>To initiate the curation process and proceed to publication, please follow these steps:</p>
<ol>
  <li><a href="https://datadryad.org">Login to https://datadryad.org</a></li>
  <li>Click on "My datasets" to view your list of data submissions.</li>
  <li>Click "Release for curation" on your dataset.</li>
</ol>

<p>If you will not be proceeding with the submission of this dataset, kindly contact us at <a href="mailto:<%= @helpdesk_email %>?subject=Withdraw DOI: <%= @resource.identifier_str %>"><%= @helpdesk_email %></a>, and we will withdraw your submission.</p>

<p>The Dryad Team</p>
```

@jleighherzog @ryscher Please review. Also, what do you thinking about sticking a warning in there, or replacing that final paragraph, with a message that we'll withdraw their submission in X months automatically?

**Comment by jleighherzog** [comment]
<p>Dear <%= @user_name %>,</p>

<p>The research article linked to your Dryad data submission has been published ("<%= @resource.title %>", DOI: <%= @resource.identifier_str %>). As your manuscript is no longer under peer review, the data should be made public.</p>

<p>To initiate the curation process and proceed to publication, follow these steps:</p>
<ol>
  <li><a href="https://datadryad.org">Login to https://datadryad.org</a></li>
  <li>Click on "My datasets" to view your list of data submissions.</li>
  <li>Click "Release for curation" on your dataset.</li>
</ol>

<p>If you do not want to publish your Dryad dataset, kindly contact us at <a href="mailto:<%= @helpdesk_email %>?subject=Withdraw DOI: <%= @resource.identifier_str %>"><%= @helpdesk_email %></a>, and we will withdraw your submission.</p>

<p>If we don't receive a reply in 14 days, we will automatically withdraw your submission from our platform.</p> 

<p>The Dryad Team</p>

**Comment by ahamelers** [comment]
14!! I was thinking 30, or 60 😆

**Comment by ryscher** [comment]
Our goal is always to publish data. And assuming we move forward with payment-at-submission, these datasets will already be paid when they get to this point. So I would prefer "If we don't receive a reply in X days, we will automatically publish your dataset".

**Comment by ahamelers** [comment]
> Our goal is always to publish data. And assuming we move forward with payment-at-submission, these datasets will already be paid when they get to this point. So I would prefer "If we don't receive a reply in X days, we will automatically publish your dataset".

But these will not have been curated at this time, and may have issues the submitter needs to be resolved. What is the solution if the submitter is not participating in the curation process?

**Comment by jleighherzog** [comment]
How about this? 

> Dear <%= @user_name %>,
> 
> The research article linked to your Dryad data submission has been published ("<%= @resource.title %>", DOI: <%= @resource.identifier_str %>). As your manuscript is no longer under peer review, the data should be made public.
> 
> To initiate the curation process and proceed to publication, follow these steps:
> 
> [Login to https://datadryad.org](https://datadryad.org/)
> Click on "My datasets" to view your list of data submissions.
> Click "Release for curation" on your dataset.
> If you do not want to publish your Dryad dataset, kindly contact us at [<%= @helpdesk_email %>](mailto:%3C%=%20@helpdesk_email%20%%3E?subject=Withdraw%20DOI:%20%3C%=%20@resource.identifier_str%20%%3E), and we will withdraw your submission.
> 
> If we don't receive a reply in 30 days, we will continue with our curation and publication processes. If you would like to withdraw your submission, please contact us at help@datadryad.org. 
> 
> The Dryad Team

**Comment by mahirst** [comment]
@jleighherzog Remove this: "If you do not want to publish your Dryad dataset, kindly contact us at [<%= @helpdesk_email %>](mailto:%3C%=%20@helpdesk_email%20%%3E?subject=Withdraw%20DOI:%20%3C%=%20@resource.identifier_str%20%%3E), and we will withdraw your submission."

We do not want people to use our PPR feature for free, and this sentence encourages that behavior.

**Comment by jleighherzog** [comment]
Dear <%= @user_name %>,

The research article linked to your Dryad data submission has been published ("<%= @resource.title %>", DOI: <%= @resource.identifier_str %>). As your manuscript is no longer under peer review, the data should be made public.

To initiate the curation process and proceed to publication, follow these steps:

1. [Login to https://datadryad.org](https://datadryad.org/)
2. Click on "My datasets" to view your list of data submissions
3. Click "Release for curation" on your dataset

If you do not take action or if we do not receive your reply within 30 days, we will continue with the curation and publication of your data submission.

The Dryad Team

**Comment by ahamelers** [comment]
Hmm, if we're going to automatically release the thing for curation maybe we should swap the order here:

```
<p>Dear <%= @user_name %>,</p>

<p>A published article has been linked to your Dryad data submission ("<%= @resource.title %>", DOI: <%= @resource.identifier_str %>). As your manuscript is no longer under peer review, the data should be made public.</p>

<p>We will automatically release your submission for curation and publication in 14 days. Please contact us at <a href="mailto:<%= @helpdesk_email %>?subject=DOI: <%= @resource.identifier_str %>"><%= @helpdesk_email %></a> if you have any concerns.</p>

<p>If you would like to initiate the curation process immediately, please follow these steps:</p>
<ol>
  <li><a href="https://datadryad.org">Login to https://datadryad.org</a></li>
  <li>Click on "My datasets" to view your list of data submissions.</li>
  <li>Click "Release for curation" on your dataset.</li>
</ol>

<p>Kind regards,</p>
<p>The Dryad Team</p>
```

Or even just:

```
<p>Dear <%= @user_name %>,</p>

<p>A published article has been linked to your Dryad data submission ("<%= @resource.title %>", DOI: <%= @resource.identifier_str %>). As your manuscript is no longer under peer review, the data should be made public.</p>

<p>You submission will be automatically released for curation and publication. Please contact us at <a href="mailto:<%= @helpdesk_email %>?subject=DOI: <%= @resource.identifier_str %>"><%= @helpdesk_email %></a> if you have any concerns.</p>

<p>Kind regards,</p>
<p>The Dryad Team</p>
```

Thoughts?

That last one would be the easiest to implement (we could just release it right when we send the email!)

**Comment by jleighherzog** [comment]
<p>Dear <%= @user_name %>,</p>

<p>A published article has been linked to your Dryad data submission ("<%= @resource.title %>", DOI: <%= @resource.identifier_str %>). As your manuscript is no longer under peer review, the data should be made public.</p>

<p>Therefore, your data submission will be automatically released for curation and publication. 

Please contact us at <a href="mailto:<%= @helpdesk_email %>?subject=DOI: <%= @resource.identifier_str %>"><%= @helpdesk_email %></a> if you have any concerns.</p>

<p>Kind regards,</p>
<p>The Dryad Team</p>

**Comment by jleighherzog** [comment]
Dear <%= @user_name %>,

A published article has been linked to your Dryad data submission ("<%= @resource.title %>", DOI: <%= @resource.identifier_str %>). As your manuscript is no longer under peer review, the data should be made public.

Therefore, your data submission will be automatically released for curation and publication.

Please contact us at [<%= @helpdesk_email %>](mailto:%3C%=%20@helpdesk_email%20%%3E?subject=DOI:%20%3C%=%20@resource.identifier_str%20%%3E) if you have any concerns.

Kind regards,

The Dryad Team
