### ISSUE TITLE
PubUpdater tweak -- journal titles

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2775]
Review how PubUpdater deals with journal titles. It is suggesting that a standardized journal title be overwritten with a non-standardized title. Is it really overwriting anything? We now rely on ISSN for most activities, and not the title.

Bryan reports these suggested changes:
- Proceedings of the National Academy of Sciences (suggested) --> Proceedings of the National Academy of Sciences of the United States of America (existing)
- Proceedings of the Royal Society B: Biological Sciences (suggested) --> Proceedings of the Royal Society B (existing)
- I thought I saw a few where G3 Genes|Genomes|Genetics was written differently, probably because those bars are stupid; the alternative formulation is G3: Genes, Genomes, Genetics, but I don't remember which way it was trying to change it and I can't find any now

**Comment by ahamelers** [comment]
It looks like the metadata overwritten currently does include both the ISSN and the publication name.

**Comment by ahamelers** [comment]
I've added a check so the pubupdater will only overwrite the ISSN and the publication name if the ISSN provided does not belong to the same journal as the one already set for the dataset
