### ISSUE TITLE
PubUpdater tweak -- improve article:preprint suggestion ratio

### ISSUE THREAD

**Issue by bryanmgee** [datadryad/dryad-product-roadmap#2779]
This will be a bit of a long ticket and has a few things: the core issue is that PubUpdater is correctly matching preprints at a much higher rate than published articles. Some data that I gathered:

- Out of 660 suggested matches, the ratio of _suggested_ articles to preprints is nearly 1:1 (294:278), but the match rate (_accepted_ changes) is nearly 1:2 (118:243). 
- If we look at accepted matches and the status of the dataset that was matched to, the disparity increases: only 47 published datasets had published articles matched (7.1% of the full set of suggested matches), which paled in comparison to the 159 published datasets that had preprints matched (nearly a 3.5:1 ratio). 
- I then looked at a different set of 200 suggested (and accepted) matches where the suggested "primary article" was a preprint. Of the 200, 62 already had the preprint in the dataset metadata (another 11 had the preprint listed as an 'Article' or 'Primary Article'). 72 datasets did not have a linked Primary Article but the preprint that was correctly suggested by PubUpdater indicated that the primary article was published. 

What we need/should consider:

- Get PubUpdater to also check whether a scholarly output is listed as a 'Preprint'
- Come up with some way to down-weight preprints, conference abstracts, theses, etc.; if this is not possible (it sounds complicated to me), we may need to consider filtering by DOIs to filter out preprint servers. Of the 200 that I looked at, 80% were from bioRxiv, with another 10 preprint servers making up the remainder. I think we could pretty easily identify a list of servers and their "core" DOI.
- The other thing, which I believe had been discussed, was seeing if there was a way to automatically scrape an associated preprint for the primary article, but I don't know how easy that is either. If this is feasible, then we could avoid filtering out preprints

Once we can figure out at least a short-term solution, we may want to remove any matches that were made more than X number of weeks/months ago, or perhaps just reset the entire thing to start from scratch (this would remove lingering "legacy" matches that resulted from behaviour that is now blocked by newly implemented rules, like matches where no changes are suggested). We may not want to do that until we sort out the ISSN replacement and journal name reformulation (#2775) bits as well. 

All of the data are in tabular format, but I need to document them for anyone to be able to fully understand how they were collected. Let me know if you want that!

**Comment by bryanmgee** [comment]
<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-2dbc6382-7fff-854c-23e6-37606b22195c">

Server | Publisher | DOI core
-- | -- | --
bioRxiv | Cold Spring Harbor Laboratory | 10.1101/
SSRN (Social Science Research Network) | Elsevier | 10.2139/ssrn/
Authorea | Wiley | 10.22541/au.
Research Square | Research Square LLC | 10.21203/rs.3.rs–
Copernicus GmbH | European Geosciences Union | 10.5194
chemRxiv | American Chemical Society (ACS) | 10.26434/chemrxiv-
preprints.org | MDPI AG | 10.20944/preprints/
ARPHA Preprints | Pensoft | 10.3897/arphapreprints.
OSF Preprints | Center for Open Science | …/osf.io/
ESS Open Archive | Wiley | …/essoar.

These are all of the preprint servers that I came across previously in my trawling (I am not 100% sure if all Copernicus preprints have the same prefix). Even just finding a way to address bioRxiv, Authorea, and Research Square would address 95% of the cases I saw.

**Comment by ahamelers** [comment]
> The other thing, which I believe had been discussed, was seeing if there was a way to automatically scrape an associated preprint for the primary article, but I don't know how easy that is either. If this is feasible, then we could avoid filtering out preprints

This would be nice, can we feed this back out to MGC?

> Come up with some way to down-weight preprints, conference abstracts, theses, etc.; if this is not possible (it sounds complicated to me), we may need to consider filtering by DOIs to filter out preprint servers.

It's not perfect, but a much simpler (and slightly more future proof) solution might be adding a filter against matches missing ISSNs. From looking at the current proposed changes, these seem like a mix of preprint servers and misnamed journals.

I don't think we want to cut out preprint matching entirely, but it makes sense to have a toggle or something to show "probably preprints" or not.

> Of the 200, 62 already had the preprint in the dataset metadata (another 11 had the preprint listed as an 'Article' or 'Primary Article').

Are we already removing all the matches where the match is already listed as some non-primary related article? We don't want people to have to accept these over and over!
