### ISSUE TITLE
Duplicate publicationISSNs

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2837]
The publicationISSN field in Internal Metadata was intended to only have one value per dataset. Some datasets have multiples. Curators have noticed that many multiples were introduced on 2023-2-20. This may have been the result of running an import process.

Determine whether we can reliably clean up these values by removing any duplicates introduced on 2023-2-20.

**Comment by ahamelers** [comment]
Duplicate of #2321 and made obsolete by #2024
