### ISSUE TITLE
Update to automatic country fee waiver based on World Bank status

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#2844]
**Priority**: Low
**Impact**: Fee waivers will not automatically be granted for submissions from countries that are categorized by the World Bank as low-income or middle-to-low income. If a waiver is needed, authors can submit a request for consideration.

1) Please make the necessary updates to the Dryad submission site so that no automatic waivers are granted based on country status ([list here](https://datahelpdesk.worldbank.org/knowledgebase/articles/906519))

2) Updated text provided below see the Cost section here: https://datadryad.org/stash/requirements

Dryad is a nonprofit organization that provides long-term access to its contents at no cost to users. We are able to provide free access to data due to financial support from members and data submitters. Dryad's Data Publishing Charges (DPCs) are designed to recover the core costs of curating and preserving data.

We’re sensitive to the fact that fees for individual researchers are a burden and create inequities. To better accommodate researchers who lack funds to pay the fee, for any reason, we’ve expanded our waiver policy so that any author may request one by contacting us at [help@datadryad.org](mailto:help@datadryad.org).

The base DPC per data submission is $150 USD. DPCs are invoiced upon curator approval/publication, unless the submitter is based at a member institution (determined by login credentials) or an associated journal or publisher has an agreement with Dryad to sponsor the DPC (see above).

**Comment by jleighherzog** [comment]
@jleighherzog : Need to update this ticket when decisions are made about the waiver request form. HOLD.

**Comment by jleighherzog** [comment]
Related ticket: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/3229

**Comment by ryscher** [comment]
For this ticket, we will just remove the automatic waivers, and add the related website updates in #3229. The form to justify waivers will be moved to a new ticket.
