### ISSUE TITLE
Auto-assign USCB-affiliated data submissions

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#2845]
**Priority:** Low
**Impact**: Submissions meant for UCSB curators to evaluate won't be claimed by the Dryad team

UCSB curators evaluate datasets submitted by UCSB-affiliated authors, providing support and guidance to their researchers. 

Could you configure the site so that all UCSB-affiliated submissions are _automatically_ assigned to UCSB Curator, **Renata Curty**? 

Possible to identify and isolate these submissions? 

Let me know if you have questions!

**Comment by ahamelers** [comment]
@jleighherzog it would make more sense to auto assign these randomly to any UCSB curator, based on permissions settings, rather than hard code a reliance on a single user. Any reason not to do this?

**Comment by jleighherzog** [comment]
@ahamelers : We've raised this previously but, I think that because we keep a direct line with Renata and I don't know how work is distributed on that side, assigning directly to her will be easiest.

**Comment by jleighherzog** [comment]
Oh, I see. Thanks for pointing that out. We can assign to Julien and Renata in rotation then (she confirmed the same). Is that less complicated?

**Comment by jleighherzog** [comment]
@ahamelers : If there's a less complex way to accomplish this, let's do it. Not urgent.
