### ISSUE TITLE
Test ROR v2

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2865]
[Version 2 of ROR](https://ror.readme.io/docs/ror-schema-api-v2-beta) will go live in early 2024. Before it is released, we should have our download/import code ready to handle the schema changes.

**Comment by ahamelers** [comment]
Major changes (from ROR community meeting):

- addition of created and last modified dates for each record (should be useful for querying!). ROR is backfilling these dates
- all name types (names, acronyms, aliases) now inside "names" with corresponding "types", each name can have a "lang" field. ROR is backfilling ISO 639-2 langs
- addresses & country condensed into "location"

Updated documentation: https://ror.readme.io/docs/schema-v2
