### ISSUE TITLE
README approval for landing display

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2874]
Add functionality for curators to flag a README as "approved". Only the approved READMEs will display on the landing page.

From Dev + Curators notes:

README file: Recommend removing from dataset landing page until we can get it to be exactly what we need and eliminate curator time to fix (5 min/submission). Consider embedded feature for curator-only display? 
Curators spending time reformatting; authors struggling to follow guidelines, costing time, costing authors time (sendback text)
- Option for curators to select to display README file on dataset landing page, if it’s acceptable/good; pub’d are good to go, we won’t revisit
- What about the position on the page? Last on page, preview stays

Sprint meeting on 2023/10/10: consider tying this implementation to the replacement of the markdown editor so we're not patchworking solutions; maybe a new editor will lead to better formatting by authors that doesn't require a lot of curator time

**Comment by ahamelers** [comment]
In slack Jess & Laura say the display checkbox for curators should be on the review page and the README on the review page should be expanded (for everyone)

**Comment by jleighherzog** [comment]
If we place it on the final page, can the default setting be to have it expanded in the view so when they scroll they see it all vs having it collapsed?
