### ISSUE TITLE
Allow frictionless for larger files?

### ISSUE THREAD

**Issue by ahamelers** [datadryad/dryad-product-roadmap#2880]
Currently the [tabular data check](https://datadryad.org/stash/submission_process#tabular-data-check) only runs on files less than 5MB. 

We've made quite a number of improvements to the speed of frictionless processing, including a general timeout of 10 minutes and a limit on the number of errors that are reported in each run. Can we increase the file size maximum for the check, under these improved parameters? To what size?

Test increasingly large CSV files with frictionless errors, and come up with a new file size limit for the frictionless check.

**Comment by ryscher** [comment]
Previous work on this issue: https://docs.google.com/document/d/17f3qG04LTGD4mfcB7go4zi7R40MPgMwV3gLwRhAMdPw/edit?usp=sharing

**Comment by ryscher** [comment]
Limits are controlled by the setting in `app_config.yml`, in the `frictionless` section.

**Comment by alinvetian** [comment]
Here are the test results:
![](https://files.slack.com/files-pri/T02BYNU0D-F07898F3CVC/image.png)

All the tests were done by using files without errors since the Frictionless script stops after finding first 10 errors.
