### ISSUE TITLE
Remove gulp and its dependencies

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2906]
Gulp is no longer useful. It only serves to complicate the installation process, because it has many outdated dependencies that conflict with dependencies elsewhere. (See #1984)

- [ ] Remove gulp from our configuration, and anything else that was added just to support gulp.
- [ ] Update the "UI library" documentation to indicate that we no longer have a standalone UI toolkit

**Comment by ahamelers** [comment]
Duplicated by https://github.com/datadryad/dryad-product-roadmap/issues/3249
