### ISSUE TITLE
Add journal_curator role

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2953]
Curators based at an institution use the `tenant_curator` role. Journals need an equivalent role for journal staff that are allowed to curate content.

The role should be able to:
- find and view datasets the same as a normal journal administrator (`JournalRole.admins`)
- edit datasets in the same way a `tenant_curator` would

Is this role best expressed entirely in the `JournalRole` objects? Or should there be role setting in the user as with the `tenant_curator`?

**Comment by ahamelers** [comment]
> Is this role best expressed entirely in the JournalRole objects? Or should there be role setting in the user as with the tenant_curator?

It would make the most sense with the current setup to put it in the journal role table, and to allow both `curator` and `org_curator`.

However, we should revamp all roles into a single table, and may want to do that instead, as it will increase efficiency and simplicity across the whole project, it's not an unreasonable amount of work, and this new role is not needed urgently.

https://docs.google.com/document/d/1MzMG0UqBswM0osSY-J_KOz9797ze_Ax3Jt7pcNw9-0Y/edit#heading=h.ar6s6lqjm9em

I've made this the new goal of our "revisit roles" ticket #1989 for next sprint, in a comment
