### ISSUE TITLE
PLOS pausing DPC coverage for PLOS Pathogens authors

### ISSUE THREAD

**Issue by mariaguerreiro** [datadryad/dryad-product-roadmap#2974]
Hello! 

PLOS will remain a Dryad member but will pause paying the DPCs for authors publishing with PLOS Pathogens. They would like to stop paying at some point in Q1 2024 (calendar year), around the time they will sunset the Editorial Manager integration too. They do not have a fixed date yet. What will you need from us, @ryscher , to ensure billing is processed accordingly, and how much lead time would you need to reflect these changes in the system?

Thanks!

Maria

**Comment by mariaguerreiro** [comment]
Making a note here that we discussed this at a recent meeting and Maria is putting together a document outlining an offboarding process. I will indicate in this ticket once we have confirmation from PLOS on our suggested timeline for pausing DPC coverage on behalf of their PLOS Pathogens authors, so no immediate action is required from you at this point in time.

**Comment by ryscher** [comment]
Do they want to pay for Q1, or have their final bill reflect activity through December?

**Comment by mariaguerreiro** [comment]
@ryscher Apologies - it seems I did not get notified for this last message.

They have not picked a firm date yet. I have suggested that they cover until end of March 2024. They would like however to have the flexibility of possibly paying for a little longer if necessary. How challenging would it be for us in terms of billing to extend that timeframe? 

Many thanks!

**Comment by mariaguerreiro** [comment]
@ryscher Have you had a chance to consider this, please? I'd be keen to get back to PLOS with our reply before the end of the week. Thank you!

**Comment by ryscher** [comment]
@mariaguerreiro We can end on whatever quarter they want, as long as we know beforehand. It would be a complete mess to end it and then quickly reinstate and end again.

**Comment by mariaguerreiro** [comment]
@ryscher Making a note here that PLOS will be pause the DPC coverage for their authors in PLOS Pathogens after April 30, 2024. At that time, I'd appreciate getting a list of which datasets have entered curation so that we know if there's anything in process that PLOS needs to be aware of.
Many thanks!

**Comment by mariaguerreiro** [comment]
@ryscher if you have a 30-day notice indicating that PLOS wants to continue DPC coverage until X date (rather than the original April 30 above), would you be able to work with that?

**Comment by ryscher** [comment]
Yes, 30 days is fine. Generally, even a few days of notice is fine. The thing that really matters is that they end at the end of a quarter, because the Tiered payment plans are processed quarterly. It becomes a big mess to disable the plan in the middle of a quarter and then manually construct an invoice for the partial quarter that was under the plan.

**Comment by mariaguerreiro** [comment]
Thank you, @ryscher! I am however a bit confused.

1 - Just to clarify, so the main issue is if DPC coverage is paused in the middle of the quarter and then reinstated, is it?

2- So, if on March 31 PLOS tells us that they would like to continue DPC coverage (originally intended to terminate on April 30), by May 31 instead, that's fine with you?

Thank you so much for your help as I get to understand what works best for everyone!

**Comment by mariaguerreiro** [comment]
@ryscher Did you have a chance to look at this please? Thanks!

**Comment by ryscher** [comment]
@mariaguerreiro 
1. The main issue is *any* change to a tiered payment plan within a quarter. It causes a serious amount of manual work. (I'm not a big fan of how the tiered plans calculate values based on prior months... hoping we come up with something more straightforward for the next iteration.)
2. If on March 31, they decide to terminate on June 30, that would be great. If they stick with the end of April or move to May, either one will be painful, since those are both in the middle of the quarter.

**Comment by mariaguerreiro** [comment]
Got it, thank you, @ryscher !

**Comment by mariaguerreiro** [comment]
Thanks for double checking @ahamelers . I am confirming with PLOS directly and will let you know asap. Thanks!

**Comment by mariaguerreiro** [comment]
@ahamelers The PLOS DPC sponsorship for PLOS Pathogens can be stopped. Thanks!

**Comment by ryscher** [comment]
Sponsorship is now disabled. 

Manually removed the payment information from two datasets that were in PPR. Applied waivers for two datasets that were published in early April (doi:10.5061/dryad.hmgqnk9rm, doi:10.5061/dryad.k3j9kd5gk)
