### ISSUE TITLE
Upgrade Ruby

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2984]
Our current version of Ruby, 3.0.4, is nearing end of life. Some servers have been upgraded to 3.0.6, but we really just need to go to a more recent version, likely 3.2.x.

**Comment by ahamelers** [comment]
The Ruby 3.0 end of life is now planned for the end of March: https://www.ruby-lang.org/en/downloads/branches/

This upgrade should also go with a Rails upgrade.
