### ISSUE TITLE
File previews for common file types

### ISSUE THREAD

**Issue by sfisher** [datadryad/dryad-product-roadmap#2993]
As part of the suggestions Karthik gave, he wanted to see file previews for common file types.  Zenodo also does this for some items.  We have (had) something for CSVs which I think maybe dropped out of our code at some point.

I didn't see this in the tickets, so I put this placeholder in case this is something people get to in the future.

Also may require some design thinking.

Related to https://github.com/orgs/CDL-Dryad/projects/1/views/15?pane=issue&itemId=22821524 and it seems like text file downloads are now saved rather than rendered and opened with the system viewer or other viewer which treats them better.

**Comment by ahamelers** [comment]
It would be reasonable to allow previews for:

- CSV, TSV
- Plain text files, markdown
- Most images
- PDF
- ZIP

I think zenodo also does most of these, with a max of 5MB for text and images and the first page of pdfs

**Comment by ahamelers** [comment]
I've implemented file previews for csv, tsv, plain text, and small web images.

PDF previews would require something like pdfJS, and zip content lists require us to look again at container_files and our https://github.com/datadryad/dryad-product-roadmap/labels/compressed issues. I'll create a separate ticket for these.
