### ISSUE TITLE
Move `publicationISSN` out of identifier internal data

### ISSUE THREAD

**Issue by DragosIorgulescu** [datadryad/dryad-product-roadmap#3019]
Requirements:
- investigate the current usage of the `publicationISSN` attribute
- modify / refactor any code that uses the `publicationISSN` directly and delegate to it through the `Identifier` model
- decide on how we will solve the relationship with the `Journal` model -- will create a separate ticket

**Comment by DragosIorgulescu** [comment]
I pushed a PR which makes some slight cleanup in the spirit of the requirements here, howver it does not look like `ISSN` is used in that many places.

Regardless, we now need to decide wether we want to:
- move the `ISSN` to `RelatedIdentifier`
- consolidate the `ISSN` from `InternalData` and `Journal` into one location / source of truth

**Comment by ahamelers** [comment]
Close in favor of more general #2666
