### ISSUE TITLE
Searching on admin site for "system (*)" results in a 403 forbidden error

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3023]
**Bug description:**

This came about while curating a dataset that had "Global Positioning System (GPS)" in the title - when copying the title into the search function, it led to a 403 Forbidden error. After some trial and error by @bryanmgee, he figured out that it seems to be when you write the word 'system' followed by anything in paratheses. 

**Steps to reproduce:**

Type "system (*)" into the search function on the admin site where the * is a wildcard. 

As a weird side note, whenever I trigger this, my browser (chrome) wants to translate the error message from Danish into English?

**Expected behavior:**
It searches the system and does not result in an error. We expect this syntax may continue to show up in titles.

**Comment by ryscher** [comment]
PR https://github.com/CDL-Dryad/dryad-app/pull/1553 was a start at fixing this. But note that it only changes the behavior for API searches, not searches performed in the UI.

The original request for this ticket was for searches on the "admin site". This is a term that curators typically use to describe [the curator's dashboard](https://datadryad.org/stash/ds_admin). On the dashboard, searches do not go through SOLR. Instead, they are transformed into SQL, in `app/models/stash_engine/admin_datasets/curation_table_row.rb`

**Comment by ahamelers** [comment]
This search works fine on the "New" Admin dashboard
