### ISSUE TITLE
Remove spaces/punctuation from entered keywords

### ISSUE THREAD

**Issue by bryanmgee** [datadryad/dryad-product-roadmap#3054]
Authors sometimes add keywords with a space or a period at the end (likely copied + pasted in from somewhere else). This has been less of an issue since restricting the displayed suggestions to the controlled vocabulary but still occurs when people freeform enter their own.

**Comment by ryscher** [comment]
Fixed by https://github.com/CDL-Dryad/dryad-app/pull/1479

**Comment by DragosIorgulescu** [comment]
We need to remove punctuation from keywords as well

**Comment by ahamelers** [comment]
> We need to remove punctuation from keywords as well

@DragosIorgulescu Currently if someone includes ',' or ';' entering keywords in the frontend, that triggers the division of what is entered into multiple keywords (the string `Testing, Keyword, Insertion` becomes an array with items `Testing`, `Keyword`, `Insertion`); you may need to be careful about the order of operations to keep that intact.

**Comment by alinvetian** [comment]
@ahamelers I think we should remove all punctuation signs from the beginning AND ending of each tag/keyword. What do you think?

**Comment by lauradryad** [comment]
This fix has caused an issue where we cannot end a keyword with a closing parenthesis:
![image](https://github.com/user-attachments/assets/c3dfe6ec-6a98-4c7a-ae3b-222bb2c5ba74)
 
Audrey says: there should probably have been a carveout for brackets or a check for opening ones

**Comment by ahamelers** [comment]
@lauradryad is the preferred solution to allow parentheses, or to treat parentheses as we treat commas (breaking the keyword into 2 there, `species-area relationship` and `SAR`)?

**Comment by lauradryad** [comment]
We would like to treat brackets like commas, breaking it into two keywords, please @ahamelers

**Comment by alinvetian** [comment]
`aa (ss) dd` text will be converted in 3 keywords `aa`, `ss` and `dd`
