### ISSUE TITLE
Investigate flagging of matched/unmatched funders on landing page

### ISSUE THREAD

**Issue by bryanmgee** [datadryad/dryad-product-roadmap#3055]
While doing shadowing with Audrey and Dragos, I came across a dataset for which none of the funders were flagged with an asterisk on the landing page, but they were all listed as unmatched in editing mode (several had to have the name edited/translated in order to match). We thought that maybe the system was not flagging unmatched funders at all, but I have since found a few that are correctly flagging unmatched funders. In perhaps a related vein, I have also picked up datasets where upon initial curation, the system displays certain entered abbreviations (e.g., NSF for National Science Foundation) as a match in editing mode, but if you add a new entry and freeform enter 'NSF,' it does not match. I think that this may be related to something around Import Metadata since they often come with unmatched author affiliations and duplicated author entries as well.

**Comment by ahamelers** [comment]
This is not an issue with the landing page or the front end; I believe it's with the API, and that funder namess inserted that way are not getting the " *" added at the end as they do when added through the front end.

**Comment by ahamelers** [comment]
Found that there was still some update code trying to exact match funder names not selected from the dropdown to the CrossRef funder list (which we no longer use, in favor of ROR) and not including the asterisk if a CrossRef match was found. So that could also be an origin of this issue.
