### ISSUE TITLE
Analyze API updates needed for data science tools

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3057]
- [x] Determine whether we need any API changes to work with Jupyter notebooks.
- [x] Review the documentation for [ROpenSci deposits](https://github.com/ropenscilabs/deposits) to determine whether we need API updates to support its needed features.

**Comment by alinvetian** [comment]
@ryscher What is the end scope of this? How do we want to interact with each of the API?
Related to [ROpenSci deposits](https://github.com/ropenscilabs/deposits), do we want to become there deposit service, like zenodo and figshare?

**Comment by ryscher** [comment]
Some discussion about ROpenSci deposits is happening in this ticket: https://github.com/ropensci/rdryad/issues/41#issuecomment-2367455549

**Comment by ryscher** [comment]
Goal for Jupyter: Write a notebook that can access dataset https://sandbox.datadryad.org/stash/dataset/doi:10.7959/dryad.h70rxwddz, and read the file `aTable.csv`. Put the contents of the "rutabaga" column into an array.

**Comment by alinvetian** [comment]
@ryscher 
1. Here is the info related ROpenSci deposits to https://docs.google.com/document/d/12uAxSqJNLMJkp_fUjzDvf_Fk3aNq-xiTlbG4M3fweXc/edit#heading=h.be7bfpxd7okr
2. For the Jupyter Notebooks I created 2 notebooks in this PR: https://github.com/datadryad/dryad-app/pull/1868
  - one for fetching data using public API endpoints
  - one for creating a dataset, attaching a file and try to submit it, using API credentials.
