### ISSUE TITLE
Determine future of GeoBlacklight

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3062]
Our GeoBlacklight setup is outdated. It requires a very old version of SOLR, which requires a very old version of Java. We need to either bring GeoBlacklight to a current version or replace it with something else.

- Review the current version of GeoBlacklight. Would we benefit from its features?
- Review the current version of SOLR. Could we transition to just using SOLR without GeoBlacklight?
- Are there any other alternatives that should be considered?

**Comment by ahamelers** [comment]
Geoblacklight is based on https://projectblacklight.org/—it mainly adds the map (which we're removing!)

Blacklight might be a reasonable fallback

**Comment by ahamelers** [comment]
Upgrading rails past v7.0.x requires geoblacklight 4.2, which introduces some other gem conflicts. We should figure out the direction of this ticket before attempting it.

**Comment by ryscher** [comment]
The current "Explore data" page has a JS error that originates in Geoblacklight. This error prevents the dropdown menus from working.
