### ISSUE TITLE
Admin site slower to load when using bookmarks

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3091]
**Bug description:**

In the last few weeks, it has taken longer to load admin pages. We primarily access the admin site through various bookmarks we have filtered the way we prefer to look at them and, though it used to be fairly instantaneous to load, it now takes upwards of 5 seconds to show up. 

Likewise, the pop-ups to change the status of a dataset often take several seconds to load and/or go away once you select an option.

Some of Laura's bookmarks (I believe all of the curators will have similar ones)

- https://datadryad.org/stash/ds_admin?action=index&controller=stash_engine%2Fadmin_datasets&curation_status=submitted&direction=asc&editor_id=92519&page=1&page_size=50&publication_name=&q=&sort=updated_at&sponsor_org=&tenant=
- https://datadryad.org/stash/ds_admin?action=index&controller=stash_engine%2Fadmin_datasets&curation_status=&editor_id=&page=1&page_size=50&publication_name=&sponsor_org=&tenant=
- https://datadryad.org/stash/ds_admin?commit=Search&curation_status=curation&direction=asc&editor_id=92519&publication_name=&q=&sort=updated_at&sponsor_org=&tenant=

**Comment by ahamelers** [comment]
I believe this is fixed?

**Comment by lauradryad** [comment]
Yah i think so
