### ISSUE TITLE
Metadata review -- how to measure completeness

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3093]
Review the metadata fields in a dataset. Which fields are guaranteed to be filled? For the other fields, which do we expect to be filled most of the time? Can we develop a description of a "complete" dataset and a measurement of how far each dataset is from being "complete"?

**Comment by ahamelers** [comment]
https://docs.google.com/spreadsheets/d/1F1jof98qP45UXxmNmjSzhkq98oxBMVNanQ33EYfgVZY/edit#gid=0

**Comment by ahamelers** [comment]
According to my queries we have 17,415 "complete" datasets by current standards, and 49,241 by pre-2021 standards. According to my queries there are 8,583 datasets that have been published, but are incomplete (presumably they were complete under some other, even earlier metadata completion standard for which don't have relevant dates)
