### ISSUE TITLE
Author unable to delete incomplete submission

### ISSUE THREAD

**Issue by bryanmgee** [datadryad/dryad-product-roadmap#3094]
We had an author email HD saying that they want to delete their incomplete submission (after getting the In Progress reminder email), but they get the "We're sorry, but something went wrong" error message when they try to do so. I just tested creating and then deleting a dataset myself on the live site and didn't have any issues. 

DOI: 10.5061/dryad.tht76hf5w
Title: Field Observations of Shell Construction Behavior of Lamprologine Cichlids

**Comment by ahamelers** [comment]
I've deleted this
