### ISSUE TITLE
Update to offboarding protocol: curation rotation for datasets

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3113]
**Priority**: Low
**Impact**: Reduce the burden on a single point person or need for manual reassignment to team

When curators are offboarded, please update the auto-assignment for any data submissions to be evenly distributed, in rotation, among current Dryad curators (excluding Jess)

**Comment by ryscher** [comment]
Note that this is for handling datasets that are
- versioned
- were originally curated by a curator who is no longer here (e.g., Bryan)

When this ticket is fixed, ensure that any datasets currently assigned to Jess get handed off to someone else.

**Comment by ahamelers** [comment]
@ryscher is there a current auto-assignment feature? If so, where can I find that?

**Comment by ahamelers** [comment]
@jleighherzog @ryscher As far as I can tell, this is already done!

```ruby
def auto_assign_curator(target_status:)
      target_curator = identifier.most_recent_curator
      if target_curator.nil? || !target_curator.min_curator?
        # if the previous curator does not exist, or is no longer a curator,
        # set it to a random current curator , but not a superuser
        cur_list = StashEngine::User.curators.to_a
        target_curator = cur_list[rand(cur_list.length)]
      end

      return unless target_curator

      update(current_editor_id: target_curator.id)
      curation_activities << StashEngine::CurationActivity.create(user_id: 0, status: target_status,
                                                                  note: "System auto-assigned curator #{target_curator&.name}")
    end
```

**Comment by ryscher** [comment]
We determined this was fixed.
