### ISSUE TITLE
Ensure views/downloads are processing

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3135]
DataCite has completed the transition of our COUNTER processes to the Dryad account. As of 2024-2-6, all datasets published within the last month are showing 0 views and downloads. Review our process for reading the information from DataCite.

https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/counter_overview.md
https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/counter_stats.md

**Comment by ahamelers** [comment]
I can see a couple of lines that worry me in `home/ec2-user/deploy/current/cron/counter.sh`

```
COUNTER_JSON_STORAGE="/home/ec2-user/deploy/shared/cron/counter-json"

cd /apps/dryad/apps/ui/current
```
`/home/ec2-user/deploy/shared/cron/counter-json` this directory does not exist, `cron` is an empty directory

`/apps/dryad/apps/ui/current` this is the previous CDL directory structure, I guess this was missed in https://github.com/CDL-Dryad/dryad-app/pull/1572/

**Comment by ahamelers** [comment]
Reassigning to @DragosIorgulescu since he has #3255

**Comment by ryscher** [comment]
It appears that documentation pages are badly out of date. They need to be updated.

Some relevant pull requests that have changed the behavior recently:
- https://github.com/CDL-Dryad/dryad-app/pull/1167
- https://github.com/CDL-Dryad/dryad-app/pull/1361
- https://github.com/CDL-Dryad/dryad-app/pull/1418
- https://github.com/CDL-Dryad/dryad-app/pull/1488

**Comment by DragosIorgulescu** [comment]
Tasks:
- [ ] Update docs -- we are passing stats to DataCite via js on the dataset page, and then making API calls to get stats info back
- [ ] Check why we are not getting actual numbers from DataCite

**Comment by ryscher** [comment]
Moving this back to Review, because I want to manually validate it after it has a chance to run for a day.

**Comment by ahamelers** [comment]
@ryscher Has this been validated?

**Comment by ahamelers** [comment]
I'm happy with this, both of the following published for the first time last month show metrics:
https://datadryad.org/stash/ds_admin/108720/activity_log
https://datadryad.org/stash/ds_admin/109172/activity_log

**Comment by ryscher** [comment]
Curators say there are still some datasets registering 0 downloads.

**Comment by ryscher** [comment]
Followup from Wendel's message:
```
- lib/stash/event_data/usage.rb
  - queries for views and downloads
  - called by cop_populate
- lib/stash/event_data/citations.rb
  - queries for citations
- cop_populate looks like it should do views and downloads -- but is it
     actually running? if not, what is calling the usage file????
  - triggered from cron/counter.sh, which isn't actually scheduled???
  - identifier calls build_counter_stat -- but where is it defined?
```

To do next:
- run the commands from `cop_populate` manually for a specific dataset, and see if its stats update as expected
- get `counter.sh` back in the crontab
- validate that everything is working again

**Comment by ryscher** [comment]
Verified that stats are processing now
