### ISSUE TITLE
Restrict README imports

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3145]
README editor should only allow import of files that are in Markdown format. Bryan was able to rename the extensions on a .txt and a .rtf (to README.md) and import both.

**Comment by ahamelers** [comment]
I don't know how anything would differentiate between a renamed .txt and a "true" .md—there's no real difference between these, a .txt file would be valid (though unformatted) markdown.

I have been looking at trying to error RTF files, but this seems very difficult to do reliably on the client side (which is where the markdown editor works, entirely)

**Comment by ryscher** [comment]
Closing as "no longer planned". We addressed the worst problems with #3345, and we will do more with upcoming redesigns to the README system.
