### ISSUE TITLE
Dryad Admin Site crashes during/after downloads

### ISSUE THREAD

**Issue by bryanmgee** [datadryad/dryad-product-roadmap#3165]
Myself, @lauradryad and @AmeliaCulpP1819 have repeatedly encountered issues in the past week where either during or immediately following a download from the Admin Site, the page freezes, and it's not possible to do anything in the Admin Site without closing out the window and logging back in again. This has happened on Firefox and Chrome and occurs sometimes in the middle of a download, sometimes right at the end of a download, and sometimes immediately after a download. We haven't been able to identify a clear pattern in terms of dataset size, file type, time of day, etc. This started happening to me in late November, but it stopped after a short while, and I was never able to reproduce it on demand. However, it has begun recurring (or newly occurring for others) in the past few weeks, sometimes multiple times a day, including relatively soon after initiating a new session.

**Comment by ryscher** [comment]
Is this a download of CSV files on the Admin page? Or you're downloading datasets that you reached from the Admin page?

**Comment by bryanmgee** [comment]
Sorry, should have been more specific – download of datasets from their landing page, while logged in from the Admin Site

**Comment by ryscher** [comment]
Problem is only triggered when downloading the ZIP for a dataset

**Comment by ahamelers** [comment]
@lauradryad is this still an issue?

**Comment by lauradryad** [comment]
@ahamelers I asked the team, and some said this still happens occasionally. The one thing that we definitely all still experience is that when we click the "download data" button, the pop-up that appears stays there long after the download is complete, and the page requires a refresh before you can interact with it again.

**Comment by ahamelers** [comment]
Okay, hopefully this will be fixed with the landing page release, but I won't automatically close this ticket to remind us to double check.

**Comment by ryscher** [comment]
I remembered seeing a dataset on sandbox that had this issue, but I can no longer reproduce it.

**Comment by ahamelers** [comment]
@lauradryad @mahirst has this (or any other weird thing) happened recently?

**Comment by ryscher** [comment]
closing pending further info
