### ISSUE TITLE
User unable to download published dataset from landing page in Chrome

### ISSUE THREAD

**Issue by bryanmgee** [datadryad/dryad-product-roadmap#3169]
We had an author email about [this published dataset](https://datadryad.org/stash/dataset/doi:10.5061/dryad.mp4jt67):

> When I try to download the full dataset or open the version file of August 26th, the download is immediately canceled and the link to the version file returns a broken site.
> 
> Is this a problem in the Dryad website or may it be a problem in my computer? I have tried to download the file both in Google Chrome and with Microsoft Edge, but both these browsers returned the same problem.

I tried the following:

- Firefox when logged into Admin Site, no issues via 'Download Dataset' button
- Firefox in incognito mode, 'Download Dataset' button is missing, but I can download it fine by clicking on the file
- Chrome in incognito mode, same issue as user, download does not initiate

And from @ahamelers in #3161: 

> This is very strange, it does seem to be a problem on Chrome only, for this specific file. You can see the issue just trying to download the individual file as well. No idea why it's only on Chrome, or what it is about this file (could it be the spaces in the filename?). The issue in this case seems to be on the AWS side: `dryad-assetstore-merritt-west.s3.us-west-2.amazonaws.com sent an invalid response.` `Failed to load response data: No data found for resource with given identifier`

**Comment by ahamelers** [comment]
https://stackoverflow.com/questions/38320996/s3-downloading-images-with-comma-in-filename-results-in-neterr-response-heade
