### ISSUE TITLE
API download issue

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3176]
I am trying to use the REST API to download the dataset for doi:10.5061/dryad.070jc. I keep getting error code 500 that an “unspecified error has occurred.” I tested it out at https://datadryad.org/stash/api and the download request gives the same error. However, https://datadryad.org/api/v2/datasets/doi%253A10.5061%252Fdryad.070jc can get the dataset record for this DOI. Any help would be greatly appreciated!

 (See also Salesforce ticket "Error using REST API for doi:10.5061/dryad.070jc")

**Comment by ahamelers** [comment]
The now gives the expected error: `The dataset is too large for zip file generation. Please download each file individually.`

**Comment by ahamelers** [comment]
Fixed with https://github.com/datadryad/dryad-app/pull/1617
