### ISSUE TITLE
Sorting datasets by "Size" in Admin Site doesn't sort perfectly

### ISSUE THREAD

**Issue by bryanmgee** [datadryad/dryad-product-roadmap#3185]
Regardless of whether you sort 'ascending' or 'descending,' the Admin Site doesn't always sort perfectly when using the Size column. Some examples:

![Screen Shot 2024-02-22 at 9 36 00 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/9285eaed-b576-4bff-910b-a5cff1588d11)
![Screen Shot 2024-02-22 at 9 35 46 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/86df9e99-4b26-4b74-b6a6-3f746ed06bd2)
![Screen Shot 2024-02-22 at 9 35 33 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/e8eba18a-8623-403a-b757-8410b6e830b1)

**Comment by ryscher** [comment]
To be considered with #3200

**Comment by ahamelers** [comment]
I think there might be a mismatch between the size depicted (the size of the current version) and the size used in the db calculation & sorting (maybe the size of all versions?)

In the new Admin dashboard (https://github.com/datadryad/dryad-app/pull/1703) both definitely use the same number.
