### ISSUE TITLE
Unable to download and view data files (DOI: 10.5061/dryad.jsxksn0hj)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3186]
**Priority**: Medium
**Impact**: Curation and publication work can continue

10.5061/dryad.jsxksn0hj
R Project for "Dispersing across habitat boundaries: uncovering the demographic fates of populations in unsuitable habitat"

Attempted to view and download files in the following ways but only "null" files were returned, unable to view data: 
- Reviewer URL
- Selecting files individually 
- "Download full dataset" button

<img width="508" alt="Screenshot 2024-02-22 at 8 48 37 PM" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/6db3b07e-9013-48a1-9118-c4a0fe07b118">

**Comment by ahamelers** [comment]
Individual files are now downloadable. Full dataset can be downloaded on Firefox, but not on chrome.

**Comment by ahamelers** [comment]
Okay, the problem here and the solution were in the database. Somehow the latest published resource here was set to `file_view: false`. All the files were copied from a previously published version so this broke in a very confusing way, I guess.
