### ISSUE TITLE
Dataset files cannot be downloaded on Chrome; needs approval on Safari

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3190]
**Bug description:**

On the [dataset](https://datadryad.org/stash/dataset/doi:10.5061/dryad.s38kf65), 10.5061/dryad.s38kf65, when you click the only file that appears to download in Chrome, you get this message:
![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/124197995/beb06722-17bc-4395-88cc-6a965cdd30b1)
When Using the download data button also just cancels the download. 

When I did it in Safari, the browser asked me if I wanted to download from AWS, I clicked approve, and then a whole folder downloaded (which I can't even see from the landing page). But when I clicked the Download full dataset in Safari, only that docx file downloaded.

**Comment by ahamelers** [comment]
Same issue as #3169

**Comment by ahamelers** [comment]
https://stackoverflow.com/questions/38320996/s3-downloading-images-with-comma-in-filename-results-in-neterr-response-heade
