### ISSUE TITLE
Add new column for total unclaimed datasets to Curation Stats page/download

### ISSUE THREAD

**Issue by bryanmgee** [datadryad/dryad-product-roadmap#3196]
The system currently displays the number of unassigned submitted datasets (these should all be new submissions that have yet to undergo curation) in this sort of real-time-updating quick view box, but this isn't included in the table view below or in the downloaded CSV report. This number is actually better than QueueSize for reporting because it ignores the accumulation of claimed (returned) datasets that linger because a curator is OOO, holidays, etc., and would be more useful to estimate/calculate turnaround times. Would be good to log that number of unclaimed datasets on a daily basis as well and report that out.

![Screen Shot 2024-02-26 at 3 55 11 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/2cc137be-8147-4ed6-a388-808d51acbc84)

**Comment by jleighherzog** [comment]
Can name it: unclaimed new submissions

**Comment by ryscher** [comment]
This will be considered as part of the overall reporting update in #3200.
