### ISSUE TITLE
Unable to use Download full dataset button on 10.5061/dryad.kd51c5bbf

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3206]
Downloading the individual files works okay, but the Download full dataset button leads to a Download error:
![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/124197995/c6b9c2e1-503c-4e6f-abaf-f97678f1c882)

Tried logged-in and logged-out of Chrome and Safari with no luck for the Download button.

**Comment by ahamelers** [comment]
Individual files are now downloadable. Full dataset can be downloaded on firefox, but not on chrome. Network response says "unauthorized." Same issue as #3186

https://datadryad.org/stash/dataset/doi:10.5061/dryad.kd51c5bbf

**Comment by ahamelers** [comment]
These issues are still occurring, in the chrome browser only. Not sure what to try next!

**Comment by ahamelers** [comment]
Okay, the problem here and the solution were in the database. Somehow the latest published resource here was set to `file_view: false`. All the files were copied from a previously published version so this broke in a very confusing way, I guess.
