### ISSUE TITLE
Ensure software/supplemental Zenodo objects link back to Dryad

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3213]
https://zenodo.org/records/7349132 should link back to https://datadryad.org/stash/dataset/doi:10.25338/B8535Z -- anything we need to change in the metadaa we're sending them?

**Comment by jleighherzog** [comment]
Another example of Zenodo record that doesn't link back to Dryad 
Dryad dataset: https://datadryad.org/stash/dataset/doi:10.5061/dryad.bnzs7h4j1
Zenodo files: https://zenodo.org/records/10533995

**Comment by ahamelers** [comment]
All of these do link to the Dryad DOI (scroll down to related works and see 'Is derived from'/'Is source of'). Maybe it just took a while to populate?

**Comment by jleighherzog** [comment]
I see that too. I think they relocated the Dryad link. If I remember correctly, it used to be in the "Details" section where people could see it.

**Comment by ryscher** [comment]
Agreed, the links used to be more prominent. This is likely a side effect of last year's redesign.
