### ISSUE TITLE
Add API Downloader that downloads to the D drive on the VE

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3216]
Currently, there is a Ruby program called API Downloader that downloads datasets to the logged-in curator's C drive folder. We would like a copy of that program that downloads to the D drive on the VE to avoid maxing out the C drive.

**Comment by ryscher** [comment]
- Actual downloads are performed by `C:\Program Files\dryad-app\script\file-download\download.rb`. It should be duplicated and updated, so the new version places result files in the D drive.
- Downloader convenience script is `C:\DryadData\SoftwareShortcuts\api_downloader.bat`. It should be duplicated with a name that indicates it is for D downloads, and it should be updated to point to the new copy of `download.rb`

**Comment by ahamelers** [comment]
Also update the downloader after #3317

**Comment by ahamelers** [comment]
@lauradryad the d drive downloader is `C:\DryadData\SoftwareShortcuts\api_downloader_d`. If a curator could test it, that would be great!

**Comment by lauradryad** [comment]
@ahamelers  Sorry about the delay! I just tried to use it and it still downloaded to the C drive in my own folder.

**Comment by ahamelers** [comment]
Thanks @lauradryad , I think I found my error, could you try again?

**Comment by lauradryad** [comment]
yes, that worked!!
