### ISSUE TITLE
HTML pasted into README editor broke the dataset and prevented it from being submitted

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3223]
**Bug description:**

Dataset 10.5061/dryad.mgqnk9963 originally came through with the attached text in the README editor (rendered tab, not the Markdown tab). The editor accepted this text, but when myself or the author went to the Review and Submit page, the whole page rendered smaller and then the Submit button was greyed out. Once I removed the HTML text from the README, I was able to submit. 
[README.txt](https://github.com/CDL-Dryad/dryad-product-roadmap/files/14592952/README.txt)

**Comment by ahamelers** [comment]
I've decided to escape all HTML tags in the final rendered HTML, since that's how the editor displays HTML and that's in line with the desired outcome for #3225 (making them match). Let me know any concerns about this solution!

**Comment by lauradryad** [comment]
So HTML is the only way we can add superscript and subscript to the READMEs right now - will this negate that then?

**Comment by ahamelers** [comment]
I can put `<sub>` and `<sup>` in a whitelist to allow them, and I can also try to have those display as actually subscript and superscript in the rich text editor, so there's not a discrepancy.

Is it fine to force things like `<i>`, `<b>` etc. to use markdown styles (`_italic_`, `**bold**`) or should I try to do the same for them? We could always make a bit whitelist of allowed HTML tags and escape everything else—but making all those HTML tags display correctly in the rich text editor would be more work.

**Comment by lauradryad** [comment]
I can only think of one README I've ever seen that had HTML in it properly, so I think escaping most of it is fine. I like the idea of putting the sub and sup in the rich text editor as well - it's often necessary for isotopes and chemical stuff

**Comment by ahamelers** [comment]
I whitelisted the tags in the final display, but displaying super/subscript in the README rich text editor is not a simple task, so I've made a new ticket for doing that and adding associated buttons to the editor for the next sprint.
