### ISSUE TITLE
Differences between README editor and final rendering

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3225]
**Bug description:**
The way that the README looks in the WYSIWYG editor is different from how it renders on the landing page. It seems the biggest difference relates to ordered and bulleted lists and their proximity to line breaks. Below is an image of the README editor versus how it rendered on the landing page. I did not get a shot of the markdown, but to fix how it looked on the landing page, I had to remove the line break between the numbered item and the first indented bullet point, and make sure there was a line break between the last indented bullet point and the next numbered item. 

![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/124197995/c492b733-b7e1-48ab-af02-fc03d424fddb)
![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/124197995/382eb5b0-045e-4e64-943b-b75490ea9c81)

We often have to play with the markdown and line breaks a good bit before it renders properly on the landing page, mostly when bulleted items are involved. 

I'm guessing this is causing authors to not use bullets very often in their READMES because it only really works if you add them in the Markdown tab.

**Comment by ahamelers** [comment]
@lauradryad Is it possible for you to attach the markdown file?

**Comment by lauradryad** [comment]
Here is an example I just came across, although slightly different (https://doi.org/10.5061/dryad.zkh1893h1). I attached the Markdown, which has line breaks in the final bullet list under "F2_longevity_data.csv" 
[README_eggviability.md](https://github.com/CDL-Dryad/dryad-product-roadmap/files/14643564/README_eggviability.md)
and then renders this way:
![Screenshot 2024-03-18 at 16 48 37](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/124197995/ab88cd14-277c-42a3-80bd-0d7bee283753)

I did not grab a screenshot of what the README editor looked like (sorry!)

**Comment by lauradryad** [comment]
Another one with tabs where the tabs show up in the MD and the WYSIWYG, but not on the landing page: 
[README.md](https://github.com/CDL-Dryad/dryad-product-roadmap/files/14676157/README.md)
README Editor: 
![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/124197995/eedd005d-66ae-4ef8-aea5-f1b53a46f404)

Landing page: 
![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/124197995/68dd03e4-0410-403f-87de-bd577a5e35d5)

**Comment by ahamelers** [comment]
> Another [one](https://doi.org/10.5061/dryad.69p8cz978) with tabs where the tabs show up in the MD and the WYSIWYG, but not on the landing page

So for this one, HTML just does this, it collapses white space unless you mark it to be kept with CSS, and there's nothing special about this element for us to recognize and mark. And, this should be made an actual table; the HTML is extremely inaccessible. Unlike a real table, a screen reader cannot read this at all—the landing page display is exactly what the experience of using a screen reader would be like to read this!

So, should I try to adjust the README display to similarly collapse the whitespace?

**Comment by lauradryad** [comment]
yes, please! we can change them into tables or make the author change it, but I think they are getting confused because it looks _okay_ on the rich text editor
