### ISSUE TITLE
Updates to Help page (Submission requirements)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3229]
Please edit [this Help page](https://datadryad.org/stash/requirements) to include updates to the paragraphs in the "Submission requirements" section.

Changes to Accepted Data bullet list: 
1) Added bullet to section to confirm that we will not accept transcripts for curation and publication
2) Updated final bullet point to highlight that Zenodo is optional, Dryad can host all files as long as they are CC0-compliant
3) In 'Preferred formats' section, edited acceptable format for README file
4) Modified 'Keywords' section
5) In 'Cost' section, updated text to remove mention of auto-waiver for country World Bank status

Accepted data
> 
> - Dryad does not accept any files with licensing terms that are incompatible with the [Creative Commons Zero waiver](http://creativecommons.org/publicdomain/zero/1.0). For more information, please see [Good data practices: Removing barriers to data reuse with CC0 licensing](https://blog.datadryad.org/2023/05/30/good-data-practices-removing-barriers-to-data-reuse-with-cc0-licensing/).
> 
> - Dryad does not accept data submissions containing personally identifiable information (PII). Any data involving human subjects must adhere to IRB regulations, obtain formal consent from participants for sharing, be properly anonymized, and be prepared in accordance with legal and ethical guidelines before being considered for publication. Please see [additional guidance on human subjects data](https://datadryad.org/docs/HumanSubjectsData.pdf). Additionally, due to the potential risk for indirect re-identification of research participants, Dryad does not accept transcripts from interviews, focus groups, observation studies, or images, audio, or video recordings derived from or displaying human subjects. Properly de-identified micro-level or aggregated quantitative data and summarized qualitative data derived from human participant research submissions are acceptable pending curator analysis if the requirements mentioned above are met.  

> - Dryad will host code, scripts, software, and/or supplemental materials. Because data files are not always compatible with the CC0 license waiver required for publication, you will have the option to upload files via Dryad for hosting on [Zenodo](https://zenodo.org/), which allows public software deposits with version control for the ongoing maintenance of software packages and additional licensing options for files uploaded as 'Software' or 'Supplemental information'. All files selected for upload and hosting by Zenodo will be time-released with the publication of the Dryad dataset and remain linked and accessible through the Dryad DOI.

Other section updates: 

Preferred file formats

> Most types of files can be submitted (e.g., text, spreadsheets, video, photographs, code) including compressed archives of multiple files. Dryad welcomes the submission of data in multiple formats to enable various reuse scenarios. For instance, Dryad's preferred format for tabular data is CSV, however, an Excel spreadsheet may optimize reuse in some cases. Thus, Dryad accepts more than just the preservation-friendly formats listed below.
> 
> Text:
> README files should be in Markdown (.md)
> Comma-separated values (CSV) for tabular data
> Semi-structured plain text formats for non-tabular data (e.g., protein sequences)
> Structured plain text (XML, JSON)
> Images: JPEG, PNG, TIFF, SVG
> Audio: FLAC, AIFF, WAV, MP3, OGG
> Video: AVI, MPEG, MP4
> Compressed file archive: TAR.GZ, 7Z, ZIP

> Keyword(s): Descriptive words that may help others discover your dataset. We require a minimum of 3 keywords for submission. Keywords can match those from your related research article or, if available, you can select from a controlled vocabulary for your discipline. 
> 
Cost
> 
> Dryad is a nonprofit organization that provides long-term access to its contents at no cost to users. We are able to provide free access to data due to financial support from members and data submitters. Dryad's Data Publishing Charges (DPCs) are designed to recover the core costs of curating and preserving data.

> We are sensitive to the fact that fees for individual researchers are a burden and create inequities. To better accommodate researchers who lack funds to pay the fee, for any reason, we’ve expanded our waiver policy so that any author may request one by contacting us at help@datadryad.org.

> The base DPC per data submission is $150 USD. DPCs are invoiced upon curator approval for publication, unless the submitter is based at a member institution (determined by login credentials) or an associated journal or publisher has an agreement with Dryad to sponsor the DPC (see above).

**Comment by jleighherzog** [comment]
@lauradryad: Can I get your eyes and edits on this before proceeding?

**Comment by jleighherzog** [comment]
Related ticket: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2844

**Comment by jleighherzog** [comment]
HOLD this ticket. @rcurty will offer some edits next week!

**Comment by jeremywalter** [comment]
"Please enter as many keywords, as applicable." -- I find this awkward/unnecessary, but otherwise it all looks great!

**Comment by mahirst** [comment]
I think it reads well. I'm glad that the "transcripts from interviews" was placed at the beginning of the list- it'll be super obvious to authors reading it who might have otherwise skipped through the list. For the Keywords section, maybe "We require a minimum of 3 keywords..." instead? Also, it might be worth stating that reusing keywords from the associated manuscript is ok.

**Comment by ahamelers** [comment]
@jleighherzog Please let me know when this is ready for implementation

**Comment by jleighherzog** [comment]
@ahamelers : This is good to go. I realize only the parts that have been updated and represented here so, if you prefer, I can provide the full page with all sections as they should appear.
