### ISSUE TITLE
Data files not uploading during second upload

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3233]
**Bug description:**
Two authors have tried to re-upload their revised datasets, but the uploading idles approximately midway. One author waited for over 6 days with no change in the upload progress.

**Steps to reproduce:**
**Article 1 DOI: 10.5061/dryad.m0cfxppb7**
SF31768

Verbatim message from author 1: 
18 March 2024: "Thanks so much for your help - we've made the appropriate adjustments. However, we're having trouble uploading the new folder to the website (now that we've included the Dropbox components, it's ~130GB). Is it normal for this upload to take upwards of a week? (I started the upload 6 days ago, but the status bar is still only halfway full)."

19 March 2024: "Yes, it's a zipped file. (see photo, our original is the 452MB file that successfully uploaded, while the new one is the 124GB file). I've also tried refreshing the page to restart the upload, but the progress bar doesn't move any further than this spot."
<img width="1080" alt="SF31768" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/108477568/1fc151c3-ce48-4d76-ba61-1f62bf51a51f">

**Article 2 DOI: 10.5061/dryad.t1g1jwt98** 
SF32118
Verbatim message from author 2: 
20 March 2024: "I have been having trouble lately with uploading files to Dryad after an initial submission. Have you heard of this issue before and is there a good fix?"

**Expected behavior:**
Expected that uploading revised datasets should not take over 6 days.

**Comment by ahamelers** [comment]
Hi @mahirst , thanks for this, there is an issue with with uploading massive files to AWS. This is one reason why [we recommend each file uploaded be less than 10 GB](https://datadryad.org/stash/requirements#file-size), though we recognize that's not always possible. We will use this ticket to investigate and increase how high we can get the web interface uploads to go as far as file size, and add some hard limits in the documentation and user error messages when users attempt to upload files that are too large.

As a workaround in the meantime, for this particular user and others in a similar situation, could you ask them to load their file somewhere else (for example, dropbox) and use the [cloud URL upload option](https://datadryad.org/stash/submission_process#upload-files) for this and similarly massive files?

**Comment by ahamelers** [comment]
- [ ] Increase size of files that can be uploaded through web interface (adjust chunk size if possible to decrease the number of "parts", see https://github.com/CDL-Dryad/dryad-app/pull/1541)
- [ ] Record/decide on hard file size limits for both upload types (URL and direct)
- [ ] Check file sizes and add error messages for overages on initial upload attempt (so the user doesn't find out halfway through the upload)
- [ ] List these file size limits in the documentation

**Comment by ahamelers** [comment]
The file size increase should hopefully have increased the size of a file that can be uploaded right up to the dataset size limit
