### ISSUE TITLE
Create workflow for AAS integration

### ISSUE THREAD

**Issue by ahamelers** [datadryad/dryad-product-roadmap#3243]
- [x] Finalize desired workflow for journal_curator role (#2953) with AAS, etc (see links)

    - https://docs.google.com/document/d/1aEEXQxOiuL_XGgMM128qp_fy54MVNItilo_XSSP3BHw
    - https://jamboard.google.com/d/1djvCWkGDGPjG69EM_16YLpwynyhHmtRoYZGeR4ja1MM/viewer

- [x] Set up workflow for qualifying submissions

**Comment by ryscher** [comment]
Use the permissions specified in https://docs.google.com/document/d/1N1Y2Vdj80qhk87P56G5vFTW3h-Vz_JAMPVkiUTHnR7A/edit

**Comment by ahamelers** [comment]
@jleighherzog did we ever get a definitive answer on the ability of journal curators to set "final" statuses, why this is different from tenant curators, and whether it should be? (It would be easier from a technical standpoint if curator roles for any type of member had the same permissions)

**Comment by ryscher** [comment]
We will call this done unless @jleighherzog decides otherwise.
