### ISSUE TITLE
Add Tenant: New York Institute of Technology

### ISSUE THREAD

**Issue by sarahklippincott** [datadryad/dryad-product-roadmap#3248]
**Tenant name:** 
New York Institute of Technology

**Logo location:** 
https://www.nyit.edu/files/scea/RGB_color_NYIT_Logo_full_tagline_darkbg.png

**Contacts to receive submission notices:** N/A

**RORs that are considered part of the tenant (including medical centers, alternate campuses, etc.)**
https://ror.org/01bghzb51

**Shibboleth info, if not in [InCommon](https://incommon.org/community-organizations/):** InCommon member, but they don’t have the Federation part yet. They use Okta SAML for SSO authentication.

**Membership model:** Annual membership fee only

Tasks:
- [x] add config to `config/tenants`
- [x] add logo to `app/assets/images/tenants`
- [x] deploy and test on stage (institution should log in to verify working as expected)
- [x] update `tenant_id` for users in the database who have emails with the institutional domain name

**Comment by ahamelers** [comment]
@sarahklippincott Is there a due date for this?

**Comment by ahamelers** [comment]
For authentication, we need the SAML entity ID and IP address range fallbacks

**Comment by sarahklippincott** [comment]
Our SAML EntityID for this integration will be http://www.okta.com/exkiiea33x6YYZI5k4x7 . Metadata is available at https://nyit.okta.com/app/exkiiea33x6YYZI5k4x7/sso/saml/metadata .

Our physical campus IP ranges are:

[64.35.176.0/20](http://64.35.176.0/20)

[216.37.96.0/20](http://216.37.96.0/20)

[64.187.240.0/20](http://64.187.240.0/20)

[64.29.24.0/21](http://64.29.24.0/21)

[199.243.207.32/28](http://199.243.207.32/28)

[147.97.4.0/24](http://147.97.4.0/24)
