### ISSUE TITLE
Update external HSI guidance (PDF)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3256]
Please update [this file](https://datadryad.org/docs/HumanSubjectsData.pdf) to include the following text: 

> Due to the potential risk for indirect re-identification of research participants, Dryad does not accept transcripts from interviews, focus groups, observation studies, or images, audio, or video recordings derived from or displaying human subjects. Properly de-identified micro-level or aggregated quantitative data and summarized qualitative data derived from human participant research submissions are acceptable pending curator analysis if the requirements mentioned above are met.

This could be added as a new, third paragraph in the first section "Dryad Requirements". Thoughts on this?

**Comment by ahamelers** [comment]
Hi @jleighherzog , previously you've updated the PDF and provided us with a new copy

**Comment by jleighherzog** [comment]
Here's the link to the updated file: https://docs.google.com/document/d/1bBwFn8kHbsUtj9PmyeieEdyyi7fcOj0bkr_B5_-zIKo/edit#heading=h.t7uximxspvd9

Note: I didn't link to this initially because I can't (and Jeremy can't) fix the issues with the page setup. The text should be continuous, without page breaks.

**Comment by ahamelers** [comment]
@jleighherzog please check and confirm the layout is now as desired

**Comment by jleighherzog** [comment]
@ahamelers : Good to go, thank you!
