### ISSUE TITLE
Filesize mismatches

### ISSUE THREAD

**Issue by ahamelers** [datadryad/dryad-product-roadmap#3269]
For file uploads, the file size recorded in the database sometimes does not match the file size of the file stored on S3. This later causes problems when downloading and generating the checksum for the file. This seems to particularly/exclusively be an issue with large zip files. Possibly a compression variance?

Edit:

I have now found many cases where the file size is wrong in files that also have an original_filename that does not match the upload_file_name. In all cases the file size given matches the other file, generally _in a previous resource_ , with the original_filename as its upload_file_name. This seems to be the #1 cause for this issue outside of files with actual upload problems.

If someone could find out where these incorrect original_filename and resulting upload_file_size values are coming from, and make them stop, that would go a long way to stopping the noise from this issue.

In the example below you can see the size for 'otutablezip' is actually just an (incorrect) copy of the size for 'taxatablezip'

```ruby
[#<StashEngine::DataFile:0x00007f1c10af1b98
  id: 3308207,
  upload_file_name: "taxatablezip",
  upload_content_type: "",
  upload_file_size: 12219459,
  resource_id: 302880,
  storage_version_id: 302880,
  upload_updated_at: Mon, 08 Jul 2024 21:51:10.000000000 UTC +00:00,
  created_at: Mon, 08 Jul 2024 21:51:10.000000000 UTC +00:00,
  updated_at: Wed, 10 Jul 2024 16:08:36.000000000 UTC +00:00,
  validated_at: Wed, 10 Jul 2024 16:08:36.000000000 UTC +00:00,
  file_state: "created",
  url: nil,
  status_code: nil,
  timed_out: false,
  original_url: nil,
  cloud_service: nil,
  digest: "2aeff7b7acb9dec2f525e1a24dd310f87f8a195c3d08694ad7df37128ba58ba6",
  digest_type: "sha-256",
  description: nil,
  original_filename: "taxatablezip",
  type: "StashEngine::DataFile",
  compressed_try: 0>,
#<StashEngine::DataFile:0x00007f1c118fe100
  id: 3307023,
  upload_file_name: "otutablezip",
  upload_content_type: "",
  upload_file_size: 12219459,
  resource_id: 302880,
  storage_version_id: nil,
  upload_updated_at: Mon, 08 Jul 2024 20:40:01.000000000 UTC +00:00,
  created_at: Mon, 08 Jul 2024 20:40:01.000000000 UTC +00:00,
  updated_at: Mon, 08 Jul 2024 20:40:01.000000000 UTC +00:00,
  validated_at: nil,
  file_state: "created",
  url: nil,
  status_code: nil,
  timed_out: false,
  original_url: nil,
  cloud_service: nil,
  digest: nil,
  digest_type: nil,
  description: nil,
  original_filename: "taxatablezip",
  type: "StashEngine::DataFile",
  compressed_try: 0>]
```

**Comment by alinvetian** [comment]
Maybe this is a related failed test:
```
RAILS_ENV=test bin/bundle exec rspec --force-color --format RSpec::Github::Formatter --format progress --tag ~skip spec/lib --seed 36083
```

Error: `expected no Exception, got #<Stash::ZenodoSoftware::FileError: Dryad and Zenodo file sizes do not match for eveniet.jpg (id: 201): Dryad size is 95019753 and Zenodo size is 85208457`

**Comment by ahamelers** [comment]
I've been running into cases where the file size is wrong in files that also have an `original_filename` that does not match the `upload_file_name`. In all cases the file size given matches the file _in a previous resource_ with the `original_filename`. I'm not sure yet how this happens or where that `original_filename` even comes from! Resource 300886 has been full of these, which I am slowly fixing by updating the file sizes to match the actual file with the `upload_file_name`.
