### ISSUE TITLE
Ubuntu installation error in VE personal profile (profile name: kathiyayini)

### ISSUE THREAD

**Issue by kailashap** [datadryad/dryad-product-roadmap#3272]
**Priority:** Low

**Impact:** Getting 0x8000FFFF error while trying to set up Ubuntu in Kathiyayini's VE profile. Here is a screenshot of the error message:

![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/135969153/4e5469ea-e241-4b95-b6db-2b24a1dde7f8)

**Comment by ryscher** [comment]
Before the install command can be run, please run `wsl --update`
