### ISSUE TITLE
Import metadata not working (DOI: 10.5061/dryad.0vt4b8h6c)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3277]
[House finch leg color changes with infection](https://datadryad.org/stash/dataset/doi:10.5061/dryad.0vt4b8h6c)
DOI: 10.5061/dryad.0vt4b8h6c

I've confirmed that the author has entered the journal title and manuscript number in the correct format (see attachment) 

![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/40996189-c75d-4e9c-86d7-f98213090ecd)

AND 

We've received the journal metadata for this dataset (below). Still, the import metadata feature isn't working for this one. 

> Journal Name: Journal of Avian Biology
> Journal Code: JAV
> Print ISSN: 0908-8857
> Online ISSN: 1600-048X
> Journal Admin Email: [jab@oikosoffice.lu.se](mailto:jab@oikosoffice.lu.se)
> Journal Editor: Michael Tobler
> Journal Editor Email: [jab@oikosoffice.lu.se](mailto:jab@oikosoffice.lu.se)
> MS Reference Number: JAV-03187.R2
> Publication DOI: 10.1111/jav.03187
> Article Status: accepted
> MS Title: House finch leg color changes with infection
> MS Authors: Coleman, Sarah; Adelman, James; Tillman, Francis
> Contact Author: Francis Tillman
> Contact Author Email: [frankietillman@gmail.com](mailto:frankietillman@gmail.com)
> Contact Author Address 1: 3774 Walker Ave
> Contact Author Address 2:
> Contact Author Address 3:
> Contact Author City: Memphis
> Contact Author State: Tennessee
> Contact Author Country: United States
> Contact Author ZIP/Postal Code: 38111
> Keywords: birds, color, disease, Mycoplasma gallisepticum
> Abstract: In numerous animals, dramatic coloration (e.g., bright red or yellow) often indicates potential fitness, but it is less clear whether subtle coloration in the same individuals (e.g., grey or brown) could also encode such signals. To determine if subtle coloration could indicate health in a bird species with colorful feathers, house finches (<i>Haemorhous mexicanus</i>), we used spectrometry to objectively quantify leg brightness and saturation before, six days after, and 13 days after captive individuals were inoculated with a naturally-occurring bacterial pathogen, <i>Mycoplasma gallisepticum</i>. We found that legs became less bright six days after infection (near the typical peak of infection), then more bright and less saturated at 13 days (entering the typical recovery period). These results suggest that subtle colors could reliably indicate current infection status, and therefore survival potential.

**Comment by jleighherzog** [comment]
Update: Author entered metadata manually (without import) and submitted successfully. However, would be useful to understand why the import feature didn't work in this instance.

**Comment by mahirst** [comment]
Another, confirmed by trying it out myself: Journal of Animal Ecology manuscript in progress number JAE-2022-00801

She hasn't submitted the data yet, so no DOI, but I told her to manually input the metadata while we investigate the issue. 

SF00032803

**Comment by lauradryad** [comment]
Had another instance with DOI 10.5061/dryad.kprr4xhcg, Ecological Applications. Received metadata through email address:

Journal Name: Ecological Applications
Journal Admin Email: [esajournals@esa.org](mailto:esajournals@esa.org)
MS Reference Number: EAP23-0311.R1
Article Status: accepted

SF: https://dryad.lightning.force.com/lightning/r/Case/500Pl00000B2gcjIAB/view

**Comment by mahirst** [comment]
Might delete this case later- not sure yet if this article was accepted.
No DOI yet. 
Journal name: Functional Ecology
SF00032926

![Screenshot 2024-04-17 at 1 17 13 PM](https://github.com/datadryad/dryad-product-roadmap/assets/108477568/2c52b14b-a480-495f-9f90-7f2d1976e690)

**Comment by ahamelers** [comment]
These manuscript numbers are _not_ in the database. Possibly a transition issue—is the email API working correctly with the new servers? Assigning @ryscher

**Comment by jleighherzog** [comment]
Another instance of the import metadata error: 

> Journal of Ecology 
> JEcol-2023-1146.R1
> SF [#32993](https://dryad.lightning.force.com/lightning/r/Case/500Pl00000BGAoLIAX/view)

"I am trying to upload my data in the Dryad repository, but when I click "Import Manuscript Metadata", it says: "We could not find metadata to import for this manuscript. Am I doing something wrong? I am leaving off the suffixes, as you mentioned."

**Comment by mahirst** [comment]
Another: Journal of Applied Ecology
but the ms is in progress, not accepted.
SF33100

"I have a paper in progress with Journal of Applied Ecology and am trying to upload my data to Dryad but am having problems loading the metadata from the manuscript. When I try to upload the metadata using the Journal and the manuscript number but I just receive and error "We could not find metadata to import for this manuscript"."

**Comment by lauradryad** [comment]
Journal: Oikos, MS ID: oik-10669
article: https://doi.org/10.1111/oik.10669

**Comment by lauradryad** [comment]
@ryscher did this pull in all past emails from that gmail account? I still have one that I can see the email but it doesn't import correctly (at least on sandbox).

![image](https://github.com/datadryad/dryad-product-roadmap/assets/124197995/c665c5d6-7dd2-4712-baad-6f0a0d636cbb)

Ecology ECOG-07149

**Comment by ryscher** [comment]
Sandbox doesn't pull in all of the emails. It only pulls in the ones we specify, by manually adding the GMail  label `dev-journal-submit`.

**Comment by lauradryad** [comment]
Excellent information, thank you!

**Comment by lauradryad** [comment]
@ryscher The author is still having trouble importing metadata on this one. It's the above manuscript I posted from 5 days ago.
