### ISSUE TITLE
Reinstate AWS alarms in Slack

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3283]
When CDL separated from our Slack channels, the #dryad-nagios channel was removed. Please create a new channel to receive the alarms from AWS, and direct the appropriate SNS topic to it.

If I remember correctly, Slack has an easy way to get an email address that connects to a channel. You should be able to create the channel, find the email address for it, and add the address to the SNS topic.

**Comment by ahamelers** [comment]
Dragos did this 😄
