### ISSUE TITLE
Improved logging around DOIs submissions to DataCite

### ISSUE THREAD

**Issue by DragosIorgulescu** [datadryad/dryad-product-roadmap#3288]
As discussed on slack, I think we should start with some logging around these requests:
- log when a dataset is published
- log when the DOI is submitted, and what the response of that request is
- add a recurring check with logs wether any DOIs are missing on the datacite side

The main goal is:
- determine if we are skipping any submissions, eg: if there are datasets published for which we don't make the request to Datacite, or if there are any requests to DataCite which don't return a 200 response
- determine if there is some significant delay on DataCite side between when a DOI is submitted and when it goes live, and if there is, incorporate that into our system. EG: add a in_progress / live / timed_out status we can keep track of for each of these submissions

**Comment by mahirst** [comment]
Low priority- a weird thing I found. I published this dataset published April 8, 2024 around 12:30pm EST. The DOI works! But, the Admin Dashboard shows a publication date of April 7, 2024 at 8PM (a sunday). But on the activity log, it has the correct date/time.

[Whole-body physiology model to simulate respiratory depression of fentanyl and associated naloxone reversal](https://datadryad.org/stash/dataset/doi:10.5061/dryad.3tx95x6pr)
DOI: 10.5061/dryad.3tx95x6pr
Resource ID: 287533
