### ISSUE TITLE
Unable to download file of published dataset (DOI: 10.5061/dryad.s38kf65)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3290]
[Data from: Genome-wide association meta-analysis of functional outcome after ischemic stroke](https://datadryad.org/stash/dataset/doi:10.5061/dryad.s38kf65)
DOI: 10.5061/dryad.s38kf65

Download is initiated but not completed. Please investigate.

**Comment by ahamelers** [comment]
I can't recreate this—what browser etc.?

**Comment by ahamelers** [comment]
@jleighherzog ping 😄

**Comment by ahamelers** [comment]
Duplicate of #3526
