### ISSUE TITLE
Datasets in "Processing" status (DOI: 10.5061/dryad.jsxksn0gc and 10.5061/dryad.xwdbrv1ms)

### ISSUE THREAD

**Issue by kailashap** [datadryad/dryad-product-roadmap#3298]
**Priority:** Medium

**Impact:** Datasets should be sent back to the author (from "Processing" to "AR")

Please investigate these datasets which are stuck in "Processing" status. The curator is unable to Force Edit to change the status.

- Bulk RNA-seq of macrophages isolated from Salmonella Typhimurium infected zebrafish embryos
  DOI: 10.5061/dryad.jsxksn0gc

- Do maternal allocations towards offspring quality and quantity ameliorate the effects of predators on offspring survival?
  DOI: 10.5061/dryad.xwdbrv1ms

**Comment by ahamelers** [comment]
I've set both to AAR
