### ISSUE TITLE
Curator unable to access VE (profile name: kathiyayini)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3302]
**Priority**: High
**Impact:** Kathiyayini is unable to use the virtual environment to curate datasets

After Kathiyayini logs in successfully, she's presented with a blank screen. 

![image (1)](https://github.com/datadryad/dryad-product-roadmap/assets/76497320/6fa402db-ea05-4526-9bd5-cf4fd57027b4)

Please offer guidance to troubleshoot.

**Comment by ahamelers** [comment]
I had this happen to me yesterday! I googled it and it was recommended to try to start the task manager. What I found indicated this can happen due to conflicts between screen resolutions (weird!)

However, I quit and reopened remote desktop and logged in again, and the problem ultimately resolved itself. (I think after I quit and logged back in twice!). While I feel bad offering such an imperfect solution, can you try that Kathiyayini?

**Comment by jleighherzog** [comment]
Thanks, @ahamelers. Passed this workaround to Kathiyayini via Slack. Will let you know the outcome.

**Comment by jleighherzog** [comment]
@ahamelers : Unfortunately, issue is still ongoing. Let me know whether there's more information we can provide. I'll ask Kathiyayini to check with her IT contacts.

**Comment by jleighherzog** [comment]
@ahamelers : Reply from Kriyadocs IT helpdesk: "No problem with the local system or server. This needs to be checked with the U.S Dev Team because the problem can be within the Virtual Environment"

Do you suppose Kathiyayini should attempt to uninstall and reinstall? Any suggestions? Kailasha and Evangeline have no issue.

**Comment by jleighherzog** [comment]
FYI:  Kathiyayini is able to access the curator account in the VE, issue only persists with the personal account

![image](https://github.com/datadryad/dryad-product-roadmap/assets/76497320/20ec5434-bbaf-496b-a103-df8d270eaa99)

**Comment by ahamelers** [comment]
> Should we try to create a new account for Kathiyayini ([kathiyayini@datadryad.org](mailto:kathiyayini@datadryad.org))? She's able to login in and access the Curator profile but not her personal account in the VE.

That's a reasonable idea @jleighherzog . I will steal this ticket and delete her current account and create a new one. Hopefully that will take care of #3272 as well.

**Comment by jleighherzog** [comment]
Great! It was Kailasha's idea
