### ISSUE TITLE
Associate dataset with Berkeley tenant (DOI: 10.5061/dryad.h70rxwds4)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3308]
**Priority**: Medium
**Impact**: Once corrected, author will not be charged the DPC. UC Berkeley should cover it. 

10.5061/dryad.h70rxwds4
Submitting author: Steve Beissinger
I've updated his user profile to reflect UC Berkeley and added his UC email address, however, I don't think that will do the trick to fix the payment because the submission has been initiated (although not yet submitted).

**Comment by ahamelers** [comment]
I've updated the tenant recorded for the version to ucb. I believe the responsibility for payment will now be successfully recorded when the dataset is submitted.
