### ISSUE TITLE
Dataset in "Upload Error" status (DOI: 10.5061/dryad.fxpnvx10r)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3311]
**Priority**: Medium-High
**Impact:** Author is unable to submit and curator is unable to access submission

Can you return this submission to 'Curation' status? 
10.5061/dryad.fxpnvx10r

Neither the curator (even attempted to force edit the dataset) nor the author are able to access the dataset.

**Comment by ahamelers** [comment]
For future reference, with upload error datasets, any superuser can try to send these again from this page:

https://datadryad.org/stash/submission_queue

Tickets should be created if repeated submission attempts fail, or if something odd is happening to that page (like datasets do not appear there, or the page itself does not load)

This submission has been re-enqueued; I'll keep an eye on it and close this only after it succeeds.
