### ISSUE TITLE
entityID change for Rockefeller University?

### ISSUE THREAD

**Issue by sarahklippincott** [datadryad/dryad-product-roadmap#3312]
The Rockefeller University will be changing the entityID of our IdP listed in the InCommon metadata sometime in the next 30 days, from [rushib.rockefeller.edu](http://rushib.rockefeller.edu/) to [sso.rockefeller.edu](http://sso.rockefeller.edu/).  When this happens will it prevent our users with existing Dryad accounts from accessing your service?  Will it possibly break existing institutional affiliations that were created using the retired entityID? What steps do we need to take, if any,  to ensure a seamless transition to our new IdP and entityID?

**Comment by ahamelers** [comment]
> When this happens will it prevent our users with existing Dryad accounts from accessing your service? Will it possibly break existing institutional affiliations that were created using the retired entityID?

No, and no (since association with an institution is a single event in our system, not re-performed unless changing institutions)

> What steps do we need to take, if any, to ensure a seamless transition to our new IdP and entityID?

Will both entity IDs work for any period of time, or will it be a specifically timed complete switch from one to the other?

**Comment by sarahklippincott** [comment]
Thanks @ahamelers I've relayed your question back to Rockefeller.

**Comment by ryscher** [comment]
I see both IDPs are available in InCommon now. I updated Dryad to use the new IDP, and it looks fine on our end. 

@sarahklippincott Please inform Rockefeller and ask them to let us know if they see any issues.

**Comment by sarahklippincott** [comment]
@ryscher Thanks! I let them know.
