### ISSUE TITLE
Datasets automatically going into PPR after curation

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3324]
After a curator touches a dataset, it should no longer automatically go into PPR, but we have had several instances of this happening:

- https://datadryad.org/stash/ds_admin/activity_log/126451? (doi: 10.5061/dryad.4tmpg4fjg)
- https://datadryad.org/stash/ds_admin/activity_log/130787? (doi: 10.5061/dryad.cjsxksnf3)
- https://datadryad.org/stash/ds_admin/activity_log/108388? (doi: 10.5061/dryad.44j0zpck5)

**Comment by mahirst** [comment]
Here's another: 
https://datadryad.org/stash/dataset/doi:10.5061/dryad.1zcrjdg0b 
doi:10.5061/dryad.1zcrjdg0b
Resource ID: 289989

**Comment by mahirst** [comment]
Another:
[Dogs do not use their own experience with novel barriers to infer others’ visual access](https://datadryad.org/stash/dataset/doi:10.5061/dryad.9cnp5hqsh) 
doi:10.5061/dryad.9cnp5hqsh
Resource ID: 290833

**Comment by lauradryad** [comment]
Some more: https://datadryad.org/stash/ds_admin/activity_log/121443? "Mechanisms of enhanced cardiorespiratory performance under hyperoxia differ with exposure duration in yellowtail kingfish"

and https://datadryad.org/stash/ds_admin/activity_log/131675? "The diversity of social complexity in termites"

**Comment by mahirst** [comment]
Another from Kathi
Resource ID 297347
doi:10.5061/dryad.prr4xgxt4

**Comment by mahirst** [comment]
Another from me
Resource ID 297620
doi:10.5061/dryad.qbzkh18rw

**Comment by lauradryad** [comment]
Another from me: 

resource id: 297042
doi: 10.5061/dryad.q573n5tp2

**Comment by mahirst** [comment]
Another from Kathi:

Resource ID: 297663
doi:10.5061/dryad.2v6wwpzw2

**Comment by lauradryad** [comment]
@ryscher @ahamelers This one is becoming quite an issue for us as datasets are getting lost while authors think we are curating them, and we think they haven't been resubmitted yet.

**Comment by mahirst** [comment]
Another:
Resource ID: 287973
doi:10.5061/dryad.9w0vt4bp8
