### ISSUE TITLE
Option to select individual files for download

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3325]
**Priority**: Low-Medium
**Impact**: Save curators time in evaluating submissions with many individual files; offer journal reviewers and future users more flexibility when accessing data files for peer review or reuse

Kailasha had the idea to include a checkbox next to each individual file that's accessible via the Reviewer URL so that curators, journal referees, and future users can _select_ specific files for download. Only files selected will be downloaded simultaneously. 

This flexibility would be beneficial for datasets like this one (see below) with over 100 individual files. And, helpful because curators and reviewers are forced to download individual files vs the entire data package when it exceeds a certain size. 

What do you think? 

![Screenshot 2024-04-23 at 8 34 36 AM](https://github.com/datadryad/dryad-product-roadmap/assets/76497320/38b6d947-ff62-40be-8a9a-9e32487b8443)

**Comment by jleighherzog** [comment]
@ahamelers : Yep, that would help meet the need. 

Feedback from Savannah: "I could certainly see this being a help! My wish list item for this specific feature would be the option to easily select all or select none, then adjust from there. Depending on the files of a certain submission, sometimes it's helpful to see 90% of the files, and other times it's helpful to see 10% of them. I could see a "select/de-select all" function being helpful as a baseline to then adjust from, if that makes sense"

**Comment by ahamelers** [comment]
We have two implementation options:

- Automatically sort large numbers of files into collections of up to 10GB each (indicate any files over 10GB should be downloaded individually)
- Allow users to select groups of files up to 10GB each for download

Both options would be complicated in non-overlapping ways to implement—it would be a pain to do one and then have to switch to the other. So it would be good to get user feedback on which option is preferred.

**Comment by ahamelers** [comment]
Curators like the idea of "Allow users to select groups of files up to 10GB each for download"
