### ISSUE TITLE
Change sponsorship of dataset from UC Davis to UC Irvine (10.5061/dryad.h18931zsh)

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3328]
The author previously worked at UC Davis and his affiliation was listed as such when he created this dataset, but he now works at UC Irvine. I have updated his user profile to Irvine, but would like to change the sponsorship of this new dataset to Irvine, if possible. 

https://datadryad.org/stash/ds_admin/activity_log/117556?

**Comment by ahamelers** [comment]
This is done
