### ISSUE TITLE
Set dataset status to "Withdrawn"

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3329]
**Priority**: Very low

Please set the status of these datasets to "Withdrawn"
These are "In Progress", assigned to me and I'm unable to edit the status

1) Manx shearwater annual survival is correlated with breeding season and outbound migration climatic oscillation carryover effects
DOI: 10.5061/dryad.1vhhmgqxq

2) Data from: Synchronized signaling in a communication network: the role of relaxed sexual selection in avoiding predators
10.5061/dryad.2gf8484

**Comment by ahamelers** [comment]
@jleighherzog Could you try setting these to withdrawn yourself again? We had a bug for a short while that wasn't allowing some status changes, but that's fixed now. Let me know if it still doesn't work and I'll make the changes in the database!

**Comment by ahamelers** [comment]
@jleighherzog It looks like these have never been submitted—is there a reason they should be "withdrawn" instead of deleted?

**Comment by ahamelers** [comment]
Done!
