### ISSUE TITLE
Set dataset status to "In Progress" with author (DOI: 10.5061/dryad.69p8cz98m)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3330]
**Priority**: Low

This dataset is assigned to me "In Progress". Dataset has not yet been submitted so, should remain "In Progress" but assigned to the submitting author (Atle Mysterud) so that it's accessible from their Dryad dashboard. 

> Using DNA metabarcoding to separate natural and human provided food in wild boar diet at the northern distribution range of Europe
> 10.5061/dryad.69p8cz98m

**Comment by ahamelers** [comment]
This should be done
