### ISSUE TITLE
Dev site issues — load balancer & ORCID

### ISSUE THREAD

**Issue by ahamelers** [datadryad/dryad-product-roadmap#3333]
- [x] 443 port "unhealthy." Possible certificate issue. Does this need to be fixed? Or should we use just Port 80?
- [x] ORCID login is also unavailable at dev.datadryad.org

**Comment by ahamelers** [comment]
Turns out only v3-dev.datadryad.org is registered with ORCID sandbox. So we can just use that.

**Comment by ryscher** [comment]
Check whether the security certificate is set for "dev" or "v3-dev". May want to have "dev" DNS just forward to "v3-dev"

**Comment by ryscher** [comment]
@ahamelers The dev sever should now be fully functional
