### ISSUE TITLE
New Mexico State University SSO issue

### ISSUE THREAD

**Issue by sarahklippincott** [datadryad/dryad-product-roadmap#3336]
**Bug description:**
Report from Jason <bengtson@nmsu.edu> that NMSU SSO connection appears to have stopped working. They requested the latest metadata for their connection, or our connection to their single sign-on. Please let me know if you follow up with Jason directly (or copy me on the email)?

**Comment by ahamelers** [comment]
I just tested it on our production site and this seems to be working fine (obviously I couldn't log in, not having the proper credentials, but we connected to the correct login screen).

If you received an email from Jason, could you forward it to the devs email address?

**Comment by sarahklippincott** [comment]
It came in as a voicemail because Jason said he was unable to contact us through our email addresses. I got a funny autoresponder when I emailed him back so I think it's possible the issue is on his end. I'm going to try following up with our other contacts at NMSU. Thanks for testing the connection. Will keep you posted.

**Comment by ryscher** [comment]
The immediate issue has been fixed. More investigation is needed to ensure the problem doesn't reappear when NMSU updates certificates in July.

**Comment by ryscher** [comment]
Closing, since the ongoing issue is now in #3366
