### ISSUE TITLE
Authors able to import non-markdown file formats to README editor

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3345]
Authors are able to import any type of file format into the README editor. We've had a few recently where they apparently imported a Word docx file which results in a README that looks like this:
![image](https://github.com/datadryad/dryad-product-roadmap/assets/124197995/4d7ece85-1a3f-43d9-97a5-65823c3ff0dd)

Perhaps there can be additional checks that alerts the author that it did not import correctly if it wasn't a markdown file specifically, as we end up sending back for these.

**Comment by ryscher** [comment]
@lauradryad We added some additional protections here, though it is still possible for users to get past the protections if they are determined. Let us know if you continue to see this problem.
