### ISSUE TITLE
Unable to create Salesforce case from dataset Activity Log (DOI:10.5061/dryad.2jm63xsx8)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3346]
**Priority**: Medium
**Workaround**: Will create a new case directly from Salesforce

Kailasha is unable to create a Salesforce case from the dataset's activity log

Title: Blood-CNS barrier breakdown drives TRPV4-mediated motor neuron degeneration
DOI:10.5061/dryad.2jm63xsx8

**Comment by kailashap** [comment]
Also, I'm unable to change the status of this dataset from 'Curation' to 'Action required'.

**Comment by jleighherzog** [comment]
@ahamelers : Possible to prioritize this ticket? We're unable to update the dataset status.

**Comment by ryscher** [comment]
Dataset is fixed. 

Underlying problem is that the user did not have a 'tenant_id'.
