### ISSUE TITLE
Add CAPTCHA to file downloads

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3351]
- Should be before file links are rendered (to prevent screen scraping)
- Do not add to PPR reviewer link results

**Comment by ahamelers** [comment]
I assume this should also not affect users who have direct file download URLS (like those following URLs found in our API)?

**Comment by ahamelers** [comment]
We used the AWS WAF `AWS-AWSManagedRulesBotControlRuleSet` rule to add a captcha on suspicious use of /stash/download URLS. It's set to block some bot types and captcha others, we can modify this as needed. I've bookmarked the management screen 😆
