### ISSUE TITLE
Update PPR auto-reminder to include DOI field

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3355]
**Priority**: Low
**Impact**: Authors frequently forward the PPR reminder email to Helpdesk with a request withdraw but only the title is available in the auto-notification. If the DOI is included, we won't need to search for it in the Admin site to populate the corresponding DOI field in Salesforce. 

Please add a dataset DOI merge field to the PPR auto-reminder notification.

**Comment by ahamelers** [comment]
@jleighherzog So, I will add the string right to the text, but as a workaround in the meantime, try clicking on the "kindly contact us" email link and checking out the subject line it creates
