### ISSUE TITLE
Update permissions for 'Curator' role

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3356]
**Priority**: Medium

Update the **Curator** role permissions to allow the option to view the Payment Information section in the dataset Activity Log

This is helpful for us to spot differences in SSO issues, easily confirm sponsorship and payment information. Currently, to confirm this, curators need to go into editing mode and view the last page of the submission form (costing time).

![image](https://github.com/datadryad/dryad-product-roadmap/assets/76497320/44c85bf9-a6c5-4c49-bf63-8723be4c59f3)
Is there a way to still keep any approved fee waiver information blinded for the Curator role?

**Comment by ahamelers** [comment]
> Is there a way to still keep any approved fee waiver information blinded for the Curator role?

@jleighherzog Sure, what do you want blocked? We could just block the 'Waiver basis' column and leave the rest (so they would still see if someone had a waiver, I think, but not why). I think that might be the least confusing thing to do.

**Comment by jleighherzog** [comment]
@ahamelers : I don't think blocking the reason will satisfy the concern raised by board members BUT I don't share the same concern. Curators will not approach or evaluate a submission any differently knowing there's a waiver. I think it's fine to leave the payment type and waiver basis visible for the 'Curator' role (leave as-is).

**Comment by ahamelers** [comment]
We can talk about concerns more in the next meeting maybe, but I do think the _fact_ of a waiver existing can't be hidden from people who can view the payment table. If the deposit has been paid for, and the table is hidden for only waiver recipients, then it will still be pretty obvious they have received a waiver.

**Comment by jleighherzog** [comment]
Ok, will add to our Monday agenda
