### ISSUE TITLE
Move JEB to OUP membership 

### ISSUE THREAD

**Issue by mariaguerreiro** [datadryad/dryad-product-roadmap#3365]
Apologies - hit enter too early!

The _Journal of Evolutionary Biology_ (currently under the Wiley agreement for quarterly DPC payment) should now be moved to Oxford University Press (OUP), effective April 1, 2024.

Can you please ensure this gets updated in the system and is reflected in the next quarter invoice reaching OUP, please?

@mark02139 According to this [documentation](https://docs.google.com/document/d/1KJK92W43MmhS_yMFk9xuzetLY4N0VhxI5hb5DMZptJY/edit#bookmark=id.g3d8f9hx0b2w), I updated SF. Can you confirm if all the information captured is correct? 

Thanks!

**Comment by mariaguerreiro** [comment]
Maria double checking DPC status.

**Comment by mariaguerreiro** [comment]
@ryscher Confirming that the information posted on the first comment on this issue is correct, so you can proceed with setting this up when you're ready; thank you!

**Comment by ryscher** [comment]
Updated connections. JEB is now sponsored by ESEB, which is in turn sponsored by OUP.
