### ISSUE TITLE
User unable to download files for DOI: 10.5061/dryad.dz08kps5d

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3367]
**Priority**: Medium-High
**Impact**: User is unable to download dataset

"I am a researcher at UC Irvine working with physician scientists to study on telomere length in bone marrow cancer patients.  I have been trying to use rdryad to automate downloads for this study ("10.5061/dryad.dz08kps5d”) but I am running into errors. I am interested in automating downloads for this particular study as model data. Could you please grant me API access and advise on the best download method?"

I'll attach some screenshots of what I experienced. For reference I am using the latest rdryad library on R 4.3.1. 

> First I tried to use the dryad_download function with the dryad doi ("10.5061/dryad . dz08kps5d") but experienced this error: 
> #refer to screenshot rdryad_**DownloadError1**
> 
> <img width="829" alt="rdryad_DownloadError1" src="https://github.com/datadryad/dryad-product-roadmap/assets/76497320/6cb4d262-0afd-43d1-8b58-94a5c8600ae6">
> Error in zip: :unzip(zfile, junkpaths = TRUE, exdir = extract_path) :
> zip error: Cannot open zip file
> /Users/patrickboada/Library/Caches/R/rdryad/10_5061_dryad_dz08kps5d.zip for reading in file zip.c: 141
> 
> 
> I then tried to retrieve the file ids in the dryad schema by using the user code posted on the rdryad github account. 
> 
> #refer to screenshot **rdryad_Downloads**
> With this I found the unique href numbers (e.g. /3048608)
> I confirmed these numbers by using python / beautiful soup to read the location of the filestream path for the study file links.
> 
<img width="747" alt="rdryad_DownloadIds" src="https://github.com/datadryad/dryad-product-roadmap/assets/76497320/cf5076f4-96ce-414a-aa41-ac1f09b61e12">
> 
> However, when I used the ids in the function dryad_files_download() I received an error 
> #refer to screenshot rdryad_**DownloadError2** & rdryad_DownloadError3
> Error in each_files_download(x, y, ...) : object 'file_ext' not found

**Download error #2**
<img width="754" alt="rdryad_DownloadError2" src="https://github.com/datadryad/dryad-product-roadmap/assets/76497320/791dfcf6-b490-405f-be75-5b3c3875d397">

**Download error #3**
<img width="749" alt="rdryad_DownloadError3" src="https://github.com/datadryad/dryad-product-roadmap/assets/76497320/bcfd71bf-649b-4599-b8ff-a3b95b082ebd">

Any help you could offer would be great! 

There are a lot of files to download for this study, and I want to make sure I don't have any data loss in the download. If there is a md5 record of data size to make sure I didn't lose any of the size, that would be amazing.

**Comment by ryscher** [comment]
@jleighherzog I'm not sure why rDryad is having problems with this file. I glanced through the source code, but I didn't see any obvious problems. The rDryad package is maintained by rOpenSci, so they may be able to provide more help on this specific failure.

Another way the author can get these files is through direct URL downloads, using the Dryad API. For example, the file that is listed in "Download Error #3" above can be obtained with:  https://datadryad.org/api/v2/files/3048608/download
