### ISSUE TITLE
Checksum calculation problems

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3369]
Dataset: doi:10.5061/dryad.jdfn2z3jn
Data file: 3124329
Resource: 291602
File name: MED_trend_TE_5000_2.txt.gz

The file could not transfer to permanent storage, because the checksum failed to calculate. When the submission was re-sent, the checksum failed again, even though this is a relatively simple small file. I manually downloaded the file from temp storage and calculated an MD5, and inserted this into the database. Processing continued as normal.

**Comment by ryscher** [comment]
Closing, since this particular issue is fixed. But the underlying problem is still unclear.

**Comment by ryscher** [comment]
This dataset had other problems -- there were many files listed in `stash_engine_generic_files` which had never been uploaded to the temporary storage. This may have been a side effect of the checksum problems, but I'm confused why the submission system allowed the user to proceed.

**Comment by ahamelers** [comment]
Checksum generation often fails if there is a difference between the upload file size and the file size in storage. See #3269

**Comment by ryscher** [comment]
Since the biggest problems are not easily reproducible, we will wait until the problem happens again. Under #3269, we will improve the quality of the file sizes.
