### ISSUE TITLE
Author ORCiD invite links duplicated 18 times in a dataset

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3374]
Medium-low priority

doi:10.5061/dryad.bk3j9kdkm
Resource ID: 294837
[Multinational evaluation of genetic diversity indicators for the Kunming-Montreal Global Biodiversity Framework](https://datadryad.org/stash/dataset/doi:10.5061/dryad.bk3j9kdkm)

I was helping a corresponding author locate the links for coauthors to add their ORCiD. Each author in the list is associated with an email address, but nobody received an email inviting them to link their ORCiD. I was under the impression that corresponding authors could see these links on the dataset submission page, but apparently not in this case. So, I created a list of the author names (there are 33 authors) and their ORCiD-associating links below each name. I noticed a pattern with some of the links because I was making sure there were no mistakes in my copy-and-paste flow. Anyway, I asked ChatGPT to look for duplicate links because I noticed at least 4 duplicates. See chat here: https://chatgpt.com/share/cf8ceeb4-2a14-46d6-8420-4f6fed15b0d1

18 links are duplicated for this dataset submission. Laura wondered if there is a limit to the number of links that can be generated per author list. I told the author that I would escalate this to the development team. You can see our email thread here: https://dryad.lightning.force.com/lightning/r/Case/500Pl00000D76cHIAR/view

Thank you in advance :)

**Comment by ryscher** [comment]
Likely related to #2595

**Comment by ryscher** [comment]
This duplicate link appears to be associated with authors that have no email address listed. When the author has no email, the ORCID link should not be shown, and a message should be displayed in its place.
