### ISSUE TITLE
Abandoned datasets -- monthly reminders

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3378]
See https://docs.google.com/document/d/1pGzPalpx_TO38DHqCmv7UgK7MmvP6kZdGmoBVAr9kHk/edit

Set up monthly reminders for all items as listed in the table.

**Comment by ryscher** [comment]
May be related to #3123

**Comment by ahamelers** [comment]
https://docs.google.com/document/d/1D1d422Zk5YKbax_Hp92zIciu9m0dR7JmNDMoLMa92CY/edit
