### ISSUE TITLE
Abandoned datasets -- withdrawing

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3379]
See https://docs.google.com/document/d/1pGzPalpx_TO38DHqCmv7UgK7MmvP6kZdGmoBVAr9kHk/edit

- [ ] Set up final/withdrawn notifications for all datasets according to the schedule in the table
- [ ] When notifications indicate that the dataset is being withdrawn, also move it to withdrawn status

**Comment by ryscher** [comment]
The curators added a requirement -- they need the ability to reset the time on a dataset, so it can have a longer time before automatically being withdrawn.

**Comment by ahamelers** [comment]
https://docs.google.com/document/d/1D1d422Zk5YKbax_Hp92zIciu9m0dR7JmNDMoLMa92CY/edit

**Comment by alinvetian** [comment]
> The curators added a requirement -- they need the ability to reset the time on a dataset, so it can have a longer time before automatically being withdrawn.

What should be the restrictions for changing this date?
- user permission restrictions?
- dataset status restrictions?

**Comment by ahamelers** [comment]
@alinvetian 

Users should be `min_curator?`

I don't know that there should be dataset status restrictions. The curators could really use this for any status where email is automatically sent.

**Comment by lauradryad** [comment]
Agreed with Audrey, just need curators to be able to do it, preferably just the superuser (not sure what that is technically called). It should just be able to reset the timeline of whatever status it's in currently, i.e., if it's in PPR, we need to be able to reset the one year timeline to withdraw.

**Comment by ahamelers** [comment]
> Agreed with Audrey, just need curators to be able to do it, preferably just the superuser (not sure what that is technically called). It should just be able to reset the timeline of whatever status it's in currently, i.e., if it's in PPR, we need to be able to reset the one year timeline to withdraw.

I _think_ this setting will allow curators to delay email sending whenever someone is like "I'm getting too many emails and can't deal with this for 3 months", which is something I think Bryan requested. Should we really limit it to superusers only? There aren't that many of you

**Comment by lauradryad** [comment]
Yes, it would be nice for this for both use cases, delaying the withdrawal and just stopping emails for a while. There are certain times when it does take an author two years in PPR to get a manuscript published, for example. I'll ask about the superuser (it's just that these requests come through HD, so it would only be a few of us doing it anyway)... does min_curator or whatever you wrote above include our non-Dryad curators and member people too?

**Comment by ahamelers** [comment]
> does min_curator or whatever you wrote above include our non-Dryad curators and member people too?

It includes curators and superusers, so external curators yes, external admins no.

**Comment by lauradryad** [comment]
Just superusers, please.

**Comment by ahamelers** [comment]
There's also a setting for internal curators only. We have a lot of settings 😄
