### ISSUE TITLE
Unable to edit/update submission status in Admin dashboard

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3384]
**Priority**: High

1) I'm unable to set the status of this dataset to "Curation" status: **10.5061/dryad.9w0vt4bfv**
I select the status from the drop-down menu and when I click "Submit" nothing happens. 
I also tried to select AAR but that status didn't stick either. 

2) I was unable to select "unassign" from the Curator column for this dataset and was forced to assign it to a curator: **10.5061/dryad.573n5tbgd**

I tried using Chrome and Safari.

**Comment by ahamelers** [comment]
Some bugs around the form parameters, only affecting certain submissions so not caught by tests. Will do a bug fix deployment and then these actions will be possible again.

**Comment by jleighherzog** [comment]
Thanks! I was able to push it through.
