### ISSUE TITLE
Delete user profile (HD request)

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3387]
We received a request to delete this person's account. They don't appear to have any objects in the system. 

https://datadryad.org/stash/user_admin/user_profile/111697

Goktug Islamoglu
[ORCID profile (opens in new tab):0000-0002-9487-3296](https://orcid.org/0000-0002-9487-3296)

**Comment by ryscher** [comment]
Account deleted.
