### ISSUE TITLE
Transfer dataset 10.5061/dryad.hqbzkh1qw to new corresponding author

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3389]
Dataset: 10.5061/dryad.hqbzkh1qw "A multi-site test of herbicide protection seed technologies for sagebrush ecosystem restoration"

New corresponding author:
Name: Magdalena Eshleman
Email: maggie.eshleman@TNC.ORG
ORCID: [0000-0003-0763-9037](https://orcid.org/0000-0003-0763-9037)

She has logged in to the system already and has consented to the change.

**Comment by ahamelers** [comment]
Done
