### ISSUE TITLE
Move dataset from published to PPR (10.5061/dryad.qfttdz0qv)

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3390]
Dataset 10.5061/dryad.qfttdz0qv was published yesterday, but the author let me know that they had selected the PPR button upon submission. I'm not sure what happened, but the dataset did briefly cycle through the PPR status, but I didn't notice until after I published.. please move this back to PPR status. 

https://datadryad.org/stash/ds_admin/129006/activity_log

**Comment by ahamelers** [comment]
Done!
