### ISSUE TITLE
Dataset status shows "In Progress" despite attempts to place in PPR status

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3400]
Title: Desiccation tolerance of Cissus quadrangularis assessed in a greenhouse experiment
DOI:10.5061/dryad.gtht76hvn

Evangeline selects the pencil icon in the Status column and selects PPR from the dropdown menu. The action is recorded in the Activity Log but the status remains "In Progress" and unchanged. Please investigate!

**Comment by ahamelers** [comment]
The UI should not allow the curator to change the status when the is "In Progress". This is a bug.

I understand changing the status to any other status at will may be a desired curation feature (mentioned by @mahirst)—if so please make a ticket and it can go on the major features board—for example we'd have to adjust the system and make sure anything 'in progress' went through the submission action before entering any other status, so the files would be saved to permanent storage (as well as other considerations I may not know about).

**Comment by ryscher** [comment]
Note that "Processing" status also allows curators to change it.... hope the same fix applies to this.

**Comment by ahamelers** [comment]
> Note that "Processing" status also allows curators to change it.... hope the same fix applies to this.

It does! Please merge in the PR
