### ISSUE TITLE
Update Help page re: vouchers

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3402]
Update the [Cost section](https://datadryad.org/stash/requirements#:~:text=datasets%2C%20preprints%2C%20etc.-,Cost,-Dryad%20is%20a) of the Dryad Help page to include the following text: 
"Dryad's data publication charge cannot be paid using vouchers." 

**Cost**

Dryad is a nonprofit organization that provides long-term access to its contents at no cost to users. We are able to provide free access to data due to financial support from members and data submitters. Dryad's Data Publishing Charges (DPCs) are designed to recover the core costs of curating and preserving data.

We are sensitive to the fact that fees for individual researchers are a burden and create inequities. To better accommodate researchers who lack funds to pay the fee, for any reason, we’ve expanded our waiver policy so that any author may request one by contacting us at [gro.dayrdatad@pleh](mailto:dev@null?subject=Fee%20waiver%20request&body=DOI:%20(Please%20insert%20the%20DOI%20of%20your%20submission)).

The base DPC per data submission is $150 USD. DPCs are invoiced upon curator approval for publication, unless the submitter is based at a [member institution](https://datadryad.org/stash/join_us#members) (determined by login credentials) or an [associated journal or publisher](https://datadryad.org/stash/journals) has an agreement with Dryad to sponsor the DPC.

Effective June 2024, Dryad's data publication charge cannot be paid using vouchers.

**Comment by ahamelers** [comment]
I think the second and third paragraph should be swapped
