### ISSUE TITLE
Ensure use of "polite" CrossRef API

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3406]
I think we checked this at some point in the past, but we should verify that we are using the "polite" form of requests to CrossRef, including an email address in the header. More info in [this blog post](https://www.crossref.org/blog/rebalancing-our-rest-api-traffic/).

**Comment by alinvetian** [comment]
In order to use `polite` pool, all we need is to set `mailto` in Serano configuration, and we do have it set:

```
Serrano.configuration do |config|
  config.base_url = APP_CONFIG.crossref_base_url
  config.mailto = APP_CONFIG.crossref_mailto
end
```
