### ISSUE TITLE
PPR Link stuck in "preparing download"

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3411]
For this PPR link (https://datadryad.org/stash/share/A1JCVuSWPbEv9phzi7YKRN-LkRn-g94L5s2QUPOwy9A) (the only one reported so far), clicking the PPR link takes you to this screen:
![image](https://github.com/datadryad/dryad-product-roadmap/assets/124197995/2f433d12-01df-48cd-b74b-e6488777f827)

But it never downloads or even starts. Tried Chrome and Edge, two different users. I am able to download the data fine from the landing page, just not the PPR link. 

Tied to SF 00034242.

**Comment by lauradryad** [comment]
I think this might be all PPR links

**Comment by ahamelers** [comment]
It's because of the new captcha stuff—having the download start automatically apparently breaks this (too bot-like?!). I'll just turn off the auto download so users will just have to click the button.

**Comment by ahamelers** [comment]
I've deployed the fix. Also removed the PPR link from this ticket 😆

**Comment by lauradryad** [comment]
> I've deployed the fix. Also removed the PPR link from this ticket 😆

Oh, does that mess something up? keeping a PPR link in here

**Comment by ahamelers** [comment]
> Oh, does that mess something up? keeping a PPR link in here

Just that they're meant to be secret/for privileged use, and this github board is totally public!

**Comment by lauradryad** [comment]
yes... correct. Thank you for the reminder!!
