### ISSUE TITLE
Create Salesforce Case button not redirecting to SF

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3413]
**Bug description:**
Me, Laura, and Jess have all noticed that the "Create SalesForce Case" button on the activity log no longer works as it should (as of yesterday afternoon, when we started curating new datasets again). Usually, clicking on it creates a SF case and redirects us to SalesForce. Now, we all get redirected to an error page (see screenshot). However, clicking on the button *does* create a SF case, so the current workaround that we have until the issue is fixed is to refresh the activity log page and click on the open SF case link under the "Salesforce cases" header.

![Screenshot 2024-06-07 at 10 15 07 AM](https://github.com/datadryad/dryad-product-roadmap/assets/108477568/6eec7a08-3455-4f35-8449-f5c5262b710d)

**Comment by jleighherzog** [comment]
Example: https://datadryad.org/stash/ds_admin/134097/activity_log

**Comment by ryscher** [comment]
I believe this is due to an update in Salesforce. Devs have started receiving the following error:
```
An ActionController::Redirecting::UnsafeRedirectError occurred in admin_datasets#create_salesforce_case:

 Unsafe redirect to "https://dryad.lightning.force.com/lightning/r/Case/500Pl00000E7CHLIA3/view", pass allow_other_host: true to redirect anyway.
 app/controllers/stash_engine/admin_datasets_controller.rb:112:in `create_salesforce_case'
```

**Comment by mahirst** [comment]
Also, not sure if this is part of the issue, but the button looks like this now for all of us, with the case outside of the box. Not important, but might be related?
![Screenshot 2024-06-07 at 10 23 30 AM](https://github.com/datadryad/dryad-product-roadmap/assets/108477568/a69f296e-9ae0-4d7f-a9f4-6077a92266e4)

**Comment by ryscher** [comment]
Ok, functionality is fixed. The button display will improve when we next deploy.
