### ISSUE TITLE
Activity log Note from Dryad System links to Stripe login

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3420]
**Bug description:**
Not urgent. Isn't affecting curation. Just a funny bug.

Several activity logs have links in the Notes section that shouldn't be there. They redirect to the Stripe login page.

Here are some examples!

https://datadryad.org/stash/ds_admin/119961/activity_log
https://datadryad.org/stash/ds_admin/124125/activity_log
https://datadryad.org/stash/ds_admin/133888/activity_log
https://datadryad.org/stash/ds_admin/133005/activity_log

**Comment by lauradryad** [comment]
Note to dev: it's specifically the "in_progress_reminder CRON - reminded submitter that this item is still `in_progress`" note in the activity log that is linking.
