### ISSUE TITLE
Uploaded Zenodo file is invisible (DOI: 10.5061/dryad.4b8gthtn2)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3424]
The Zenodo file is invisible in this [dataset](https://datadryad.org/stash/dataset/doi:10.5061/dryad.4b8gthtn2) (DOI: 10.5061/dryad.4b8gthtn2). 

The file name, size, and license information are available in the 'Review and Submit' section of the editing page but the associated Zenodo URL is missing. Also, there is no trace of this file on the [reviewer-sharing](https://datadryad.org/stash/share/0BUlxg9aCAzP3diZjI_FnYuIYcz-Im3oojdileU1Sw4) page. We even tried to delete and reupload the file but it is still invisible. What could be the reason?

**Comment by jleighherzog** [comment]
@ryscher : @ahamelers : Can we increase the priority of this ticket?

**Comment by jleighherzog** [comment]
Jess will find out whether we can we host this on the Dryad site.

**Comment by ryscher** [comment]
The file is R code, and is listed as software. 

File is queued for upload to Zenodo; we will clear and restart the queue.

**Comment by jleighherzog** [comment]
Uploaded file for hosting on Dryad.
