### ISSUE TITLE
returnURL behavior

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3426]
In a sample sandbox dataset (identifier 31195), ownership was explicitly assigned to user “Niko Bozovic” (userId=43805). When using the "editLink" URL to assume ownership, Dryad unexpectedly returns a 403, but only when the returnURL parameter is included. Also, the 403 does not include an explanation of the problem.

**Comment by ahamelers** [comment]
Info about returnURL: https://github.com/datadryad/dryad-app/blob/main/documentation/apis/embedded_submission.md#allow-users-to-edit-metadata-about-the-dataset-and-upload-data-files

**Comment by ryscher** [comment]
This dataset is https://sandbox.datadryad.org/stash/ds_admin/31195/activity_log, doi:10.7959/dryad.2jm63xsjt
Add note

**Comment by alinvetian** [comment]
@ryscher I do not think the issue is in the code.
https://sandbox.datadryad.org/stash?aaa=http%3A%2F%2Flocalhost
https://v3-dev.datadryad.org/?aaa=http%3A%2F%2Flocalhost

From what I see in the headers the 403 is returned by the AWS ELB
