### ISSUE TITLE
Dataset 10.5061/dryad.931zcrjs5 second published version not on Zenodo

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3429]
We first published this dataset (https://doi.org/10.5061/dryad.931zcrjs5) on May 20th (record: 294824), and a copy of the repository was also put on Zenodo, as intended.

Author versioned their dataset with updated files on June 11 (record: 298489), which we also published, but the [Zenodo instance](https://zenodo.org/records/11218452) did not update (it still only lists one version on May 20). 

It is important that it is updated correctly in the Zenodo instance because 1) the initial files on May 20th had an error that the author has now corrected and 2) when googling the dataset title, the Zenodo record is the first hit which is why people are going there instead of Dryad recently.

**Comment by ryscher** [comment]
I removed the files from view in the Zenodo record, and updated the abstract to point to the actual dataset at Dryad.

Additionally, scheduled a discussion with Jess about how we're handling Zenodo for future content.
