### ISSUE TITLE
Remove version history page and replace with actual activity log

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3430]
When accessing a dataset from a user profile, this is the path it currently takes:

https://datadryad.org/stash/user_admin/user_profile/3

When you then click on a dataset, it takes you to a version history page that is not very helpful:
https://datadryad.org/stash/edit_histories?resource_id=72046 

Instead of hitting this version history page, we would prefer that clicking on the dataset name takes you to the activity log of the dataset.

**Comment by ahamelers** [comment]
Oh this is so weird, this shows when a normal user edits a dataset, but not anything about what they are actually editing, and buried in the least accessible place humanly possible.

Just a note to myself to look at these totally obsscure things as a potential place to start to modify for #3399!

**Comment by ahamelers** [comment]
I've modified it so the link and edit buttons in the first column work the same way as on the admin dashboard first column, and the clock in the last column is now a link to the activity log

**Comment by lauradryad** [comment]
Thank you!
