### ISSUE TITLE
Dryad system put a PPR dataset into "in progress" for no apparent reason- need it put back in PPR

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3431]
**Bug description:**

The author wants their dataset to be in PPR, so I put it into PPR on 14 June. According to the activity log (linked below), the PPR notification was sent to the author and the journal, as per usual. However, three days later the Dryad System created a new resource ID and put the dataset in "in progress" status. I cannot put it back into PPR, only curation or withdrawal.

I'm not sure what's going on here, but I just need the dataset put back into PPR, please!

Activity log: https://datadryad.org/stash/ds_admin/129374/activity_log 
DOI: 10.5061/dryad.vt4b8gv0p
Resource ID: 299445

**Comment by ahamelers** [comment]
@mahirst 

1. You sent version 3 to action required
2. The author created version 4 (presumably to do the action required?)
3. You set version 3 to PPR
4. Version 3 is in PPR, Version 4 is in progress

What should I actually do here? Has the user completed their changes in version 4, so that should be submitted and set to PPR? Should version 4 be deleted—or would that destroy the user's changes? Could you double check on the preferred course of action with the user?

**Comment by ahamelers** [comment]
@mahirst The easiest course of action would be for the user to either delete version 4, or finish and submit it. Or if they give us the go ahead, we can delete it for them.

**Comment by mahirst** [comment]
@ahamelers It looks like the author didn't create that newest version, though. Wouldn't it have the author's name in the "action taken by" column? Like in this dataset: https://datadryad.org/stash/ds_admin/110622/activity_log

**Comment by ahamelers** [comment]
@mahirst it does!
<img width="1179" alt="Screenshot 2024-06-18 at 10 52 06" src="https://github.com/datadryad/dryad-product-roadmap/assets/1749394/66194e08-cdeb-4ca5-8d2a-01aad8f8a3da">

**Comment by mahirst** [comment]
Oh. I see now! It's the same Resource ID as it was before. But why did the system take it out of PPR 3 days after I put it in PPR? I'm confused, but I guess I just need to ask the author to click the submit button and explain that they cannot just x out of their browser if they enter the dataset.

**Comment by mahirst** [comment]
@ahamelers Anyway, we can close this ticket. Sorry for the confusion!

**Comment by ahamelers** [comment]
@mahirst Different versions can have different and conflicting states
