### ISSUE TITLE
Stop auto-assigning Salesforce cases to whomever claimed the dataset in admin site

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3435]
Currently, when a curator claims a dataset, any and all Salesforce cases with that dataset's DOI in the DOI field are auto-assigned to that curator. We would like this feature turned off when the Salesforce ticket is already claimed by another user. 

The "Create SF case" button on the activity log should still create a SF ticket that is already assigned to the user who clicked the button, but we do not want other cases with that DOI to be reassigned to the curator who claims the dataset. (We can see all cases related to that dataset in the Salesforce section of the Activity Log). 

Background: this is also creating problems when a user submits a Help Desk query to an already-curated dataset and includes their DOI in their subject line - the SF case gets automatically assigned to the curator who claimed the dataset, instead of going through the normal HelpDesk channels (circumventing our HD process).

**Comment by ahamelers** [comment]
This is very silly, but the code ended up doing exactly the opposite of intended—it's only changing the owner if there IS an owner 🤦

**Comment by ryscher** [comment]
Note that this was not a bug. It was working exactly as requested in #1958.

**Comment by ahamelers** [comment]
But there was a bug with the code for this ticket!
