### ISSUE TITLE
Create dataset through API bug

### ISSUE THREAD

**Issue by alinvetian** [datadryad/dryad-product-roadmap#3437]
**Bug description:**
When trying to create a dataset through API endpoint and you get an error (for example the one from here https://github.com/datadryad/dryad-product-roadmap/issues/2399) an empty dataset remains in the database and the user needs to delete it manually.

**Steps to reproduce:**
Follow the steps from https://github.com/datadryad/dryad-product-roadmap/issues/2399

**Expected behavior:**
No dataset should be created

**Comment by ahamelers** [comment]
@alinvetian Have you checked that this is the case for other errors as well, or is it just the one from #2399?

@ryscher Should the dataset not be created at all, or should it be created with the API submitter as the user? Or some other option?

**Comment by alinvetian** [comment]
There are 2 cases where the API creates a dataset without data and it remains assigned to the API user that triggered the call. The resource is created in here https://github.com/datadryad/dryad-app/blob/main/app/models/stash_api/dataset_parser.rb#L131 and then the error is `raise` and the resource remains without any data.

In other cases, like `missing title`, the dataset gets created with all sent data and is assigned to proper user.
