### ISSUE TITLE
Prepare new version of admin dashboard for major use

### ISSUE THREAD

**Issue by ahamelers** [datadryad/dryad-product-roadmap#3440]
Basic requirements:
- [x] Write extensive automated tests
- [x] Copy or recreate all the curation editing popups
- [x] Copy or recreate the curation editing tests

Additional features:
- [x] https://github.com/datadryad/dryad-product-roadmap/issues/1248
- [x] https://github.com/datadryad/dryad-product-roadmap/issues/2465
- [x] Expand filters unless viewing an unmodified saved search
- [x] Reload results & change pages without reloading page

**Comment by ahamelers** [comment]
Waiting for:

1. Approval from curators and stakeholders, additional testing, etc.
2. Diagnosis of the repeated 504 errors & whether we need to modify this further (remove total counts, adjust CSVs allowed, etc.)

**Comment by ryscher** [comment]
Please test how it scales with different sizes of result sets. We want it to keep working when we have 10x the data.
