### ISSUE TITLE
High priority- Delete first version dataset with sensitive information

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3449]
High priority

**Data issue description:**
Three species in a dataset were listed, none are on the IUCN red list, so they weren't flagged. The dataset was published. The author came back saying the State govt requires the first version to be removed because the coordinates are too precise for those species and may affect conservation efforts.

Please remove Version 1 of this dataset:

doi:10.5061/dryad.pc866t1rz
Current Resource ID: 301030
Previous published Resource ID: 279328

**Comment by ryscher** [comment]
- Removed visibility of the first published version (resource 279328) in Dryad 
- Updated Zenodo to have a thousand year embargo on the original data files
