### ISSUE TITLE
AWS disk space warnings

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3450]
When the prod2 server ran out of disk space, we didn't receive any warnings until the space was already gone. Review the warnings that are in place and ensure we get notified earlier. Probably at 75% and 90%.

**Comment by alinvetian** [comment]
AWS alarms are set up as following:
1. For all `production` and `stage` machines ar 80% and 90%
2. For dev `machine` only at 90%

The alarms are messaging on `dryad-alerts` Slack channel, like the already existing ones.

There is a PR for updating the documentation on how to install and configure `amazon-cloudwatch-agent`
