### ISSUE TITLE
Change corresponding author of dataset

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3451]
The authors of this dataset would like the corresponding author to be changed. I received consent from the current corresponding author and the new one. Consent statement, name, ORCiD, and email of the new corresponding author are listed below.

doi:10.5061/dryad.3xsj3txq8
Resource ID: 300352

"I consent to being the owner of the data set 10.5061/dryad.3xsj3txq8."
Charles R Gallistel
ORCID ID 0000-0002-4860-5637
randy.gallistel@gmail.com

**Comment by ahamelers** [comment]
Hi @mahirst , this user doesn't seem to have an account on Dryad

**Comment by mahirst** [comment]
@ahamelers Thanks for pointing that out! I directed him to make one, and he just said he made one.

**Comment by ahamelers** [comment]
Okay great! This is done
