### ISSUE TITLE
Autocompletes and browser autofill

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3452]
When a browser suggests an autofill value for a field, and that field would normally be an autocomplete, the autocomplete doesn't happen, and the form doesn't pick up the value.

[Short video demonstrating the problem](https://www.loom.com/share/f87844e36dd1453fa1aa60e181c7b2b4?sid=dc418759-8cf5-4c89-b4d7-f9165553686a)

**Comment by ahamelers** [comment]
There are like 14 different 'National Institutes of Health' from different countries, I don't think we can auto match these!

We could try to do something like select the first one and show that it is selected. But the user would still need to wait for the dropdown to load...

Probably the best intermediate option is to turn off browser autocomplete as an option for these fields

**Comment by ryscher** [comment]
Yes, if you can disable the browser's autofill, that would solve the problem.
