### ISSUE TITLE
Delete one user and transfer dataset 10.5061/dryad.7h44j102h

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3458]
A user logged in with two separate ORCID accounts. They only created one dataset so far, but they created it under the ORCID they no longer want to use -- so we need to transfer ownership of that dataset (10.5061/dryad.7h44j102h | Resource ID: 296874) to ORCID 0000-0003-2929-9766.

Additionally, we can delete the user with the ORCID 0009-0007-8319-5614. 

I know there is a merge function within the manage users page, but I wasn't sure what happens when you merge two users with different ORCIDs so I didn't want to try.

**Comment by ahamelers** [comment]
I used the merge feature, ready to edit in the correct ORCID in the database if it kept the wrong one, but it just so happened to keep the one we wanted. Victory!
