### ISSUE TITLE
Dataset stuck in processing for a few days

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3476]
Dataset (resource ID 301768) has been stuck in processing since June 28. The author contacted HD and said that he uploaded from his local machine so it shouldn't be a link problem. SF 34856

**Comment by ahamelers** [comment]
Looks like it's just a lot of files, the error we saw was "item has been processing for more than a day, so marking as errored", and nobody was checking upload errors over the weekend.

I've resubmitted it to continue processing. Maybe it will complete this time 🤷

**Comment by ahamelers** [comment]
Seems to have gone through!
