### ISSUE TITLE
Unable to update dataset status

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3478]
Unable to change the status of the following datasets from "Submitted" to "Curation" (new datasets):
- 10.5061/dryad.pzgmsbcwh
- 10.5061/dryad.brv15dvhz

Similar issue experienced in this ticket: https://github.com/datadryad/dryad-product-roadmap/issues/3384

**Comment by ahamelers** [comment]
@jleighherzog Could you try again?

**Comment by jleighherzog** [comment]
@ahamelers : Resolved! Thanks.
