### ISSUE TITLE
PRIORITY: Remove published version

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3482]
DOI: 10.5061/dryad.djh9w0w7r

Please remove data files published on June 14, 2024.
Author provided valid reason for removal re: patient privacy, risk of re-identification

The data files published on June 28th should be retained.
I'll post a note for future users re: removal.

**Comment by jleighherzog** [comment]
@ahamelers : Will you be able to address this while Ryan is OOO?

**Comment by ahamelers** [comment]
I've removed those files from view on Dryad and Zenodo
