### ISSUE TITLE
Formatting error on article DOI in Preliminary Information section

### ISSUE THREAD

**Issue by Savannahbutler** [datadryad/dryad-product-roadmap#3483]
I'm running into an issue with [this Dryad submission](https://datadryad.org/stash/dataset/doi:10.5061/dryad.4j0zpc8k8) (DOI: 10.5061/dryad.4j0zpc8k8) 

This submission came in as a 'manuscript in progress', but the related article was published between the initial Dryad submission and now. I deleted the manuscript number from the internal data, attempted to move it to a 'published article' and added the [article](https://doi.org/10.1016/j.marpol.2024.106082) DOI (10.1016/j.marpol.2024.106082) but it's throwing an error and not allowing me to submit as a 'published article'.

attempting to update with article DOI:
![image](https://github.com/datadryad/dryad-product-roadmap/assets/114602548/2e7b5e3c-b260-4607-8aac-c25a7dc9598b)

error upon trying to submit:
![image](https://github.com/datadryad/dryad-product-roadmap/assets/114602548/ee9c96af-28aa-491f-9ed8-077fa83bf8c2)

**Comment by ahamelers** [comment]
@Savannahbutler Could you try it with the URL format? (https://doi.org/...) Let us know if that works.

Either way, I could have sworn we'd already made the DOI entry here as loose as possible, but we can check again.

**Comment by Savannahbutler** [comment]
@ahamelers I have tried in both URL format and just the DOI, and Laura attempted as well on this specific dataset without any luck!

**Comment by ahamelers** [comment]
@Savannahbutler So sorry for the delay on this! That "error" message wasn't useful at all. Here's what was actually the problem:

You have to delete the entry for the same article, under Related Works, as a related 'Article', before you could add it as a primary article! 🤦
