### ISSUE TITLE
Manage User option

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3484]
I merged two profiles for a user. In this view, I selected "Submit" and "Cancel" but there was no action, nothing happened. I expected it would return to the first view (search results). Is it a little bug or as it should be?

![Screenshot 2024-07-04 at 10 22 53 AM](https://github.com/datadryad/dryad-product-roadmap/assets/76497320/c9820f8c-6ef0-4e50-9c0c-44fc577755e4)

**Comment by ahamelers** [comment]
It should change what's shown in the roles box at the top right. I could make it flash or something?

**Comment by jleighherzog** [comment]
Ok, I just expected that selecting one of those options would close the view and return to the main account page. Fine to leave as-is.
