### ISSUE TITLE
Update in payment plans needed [Urgent]

### ISSUE THREAD

**Issue by mariaguerreiro** [datadryad/dryad-product-roadmap#3485]
**Bug description:**
There are a handful of organisations with outdated payment plans in the system. This has affected Q1 quarter invoicing and is affecting Q2 invoicing too - please prioritise as we need to ship the DPC invoices for Q2 asap.

@ryscher Please could you:

1. Update the payment plans in the system for these organizations – including ensuring these are updated in (https://datadryad.org/stash/journals):

- American Genetic Association – Tiered
- American Ornithological Society – Tiered
- American Society of Plant Taxonomists – Tiered
- Society of Systematic Biologists – Tiered
- The Institute of Botany, Chinese Academy of Sciences – Tiered - please change DPC sponsor to Wiley too
- The Royal Society – Tiered

2. Regenerate the shopping cart reports and tiered summaries that inform the quarter invoicing for Q1 and Q2 2024, please.

Many thanks!

**Comment by ahamelers** [comment]
@ryscher I've made all the changes requested, please regenerate the reports

**Comment by mariaguerreiro** [comment]
Thanks @ahamelers !

**Comment by mariaguerreiro** [comment]
@ryscher Just as an additional bit of information, The Institute of Botany, Chinese Academy of Sciences is showing up on this report as a sponsor - https://github.com/datadryad/journal-payments/blob/main/tiered/tiered_2024/tiered_2024_Q2/2024-Q2_tiered_summary.csv - but their journal ("Journal of Systematics and Evolution") is showing up correctly on https://datadryad.org/stash/journals with DPCS sponsored by Wiley, so it seems there's a discrepancy in the data. I'd be grateful if you could look into this as well, to ensure we list this journal's published data under the Wiley invoice. 

Many thanks!

**Comment by mariaguerreiro** [comment]
@ryscher Since you're on this, please can you also ensure that sponsorship for the ESA journals are correct in https://datadryad.org/stash/journals. In the Shopping cart reports on GitHub, the output seems correct for Q2, but in https://datadryad.org/stash/journals the Ecological Society of America should only be listed as a sponsor for _Ecological Monographs_, so please update the following titles:

- Ecology - No sponsor
- Ecological Applications - No sponsor
- Ecological Mongraphs - Ecological Society of America
- Frontiers in Ecology and the Environment - No sponsor
- Ecosphere - No sponsor

Many thanks!

**Comment by ryscher** [comment]
@mariaguerreiro Note that your last comment is a change from ticket #2458. Expect future authors to be confused about the change.

**Comment by ryscher** [comment]
All information for Q1 & Q2 is now regenerated. Note that there are some cases where internal modifications have changed the values, such as when an author asks us to remove a published dataset, and it is re-published at a later date. I'll leave it up to @mariaguerreiro how to actually invoice for these differences.

**Comment by mariaguerreiro** [comment]
Thank you so much, @ryscher !

Regarding ESA, they had moved to only cover for Ecological Mongraphs last year already. I will confirm Jess and Sarah are aware, in case we get queries.

Do you have a sense of which cases were affected by this? "Note that there are some cases where internal modifications have changed the values, such as when an author asks us to remove a published dataset, and it is re-published at a later date. I'll leave it up to @mariaguerreiro how to actually invoice for these differences." 

Many thanks!

Maria

**Comment by ryscher** [comment]
I don't have a good sense of the differences. They are not large. When I was spot-checking, I noticed that some of the values were slightly different. I put in the effort to track down a couple, and they had reasonable explanations, but the differences were not enough for me to justify doing a more detailed analysis. If you see any issues that should be investigated, let us know.

**Comment by mariaguerreiro** [comment]
Thank you, @ryscher ! Could I ask you to look into and generate the 2023 figures for the Rockefeller University Press for me, please?

It seems we updated their payment plan in the system halfway through the year, when they should have been on the tiering plan from Jan 2023 onwards, so I believe there are a handful datasets we need to bill them for, but I'd like to validate that with your report, please.

**Comment by mariaguerreiro** [comment]
@ryscher Have you had a chance to look into this, please? Thank you!

**Comment by ryscher** [comment]
For 2023
- Journal of Cell Biology published 10 datasets
  10.5061/dryad.866t1g1vh
  10.5061/dryad.kwh70rz8m
  10.5061/dryad.rbnzs7hgg
  10.5061/dryad.s7h44j1bw
  10.5061/dryad.j6q573nk8
  10.5061/dryad.zpc866td7
  10.5061/dryad.9p8cz8wn3
  10.5061/dryad.n8pk0p31b
  10.5061/dryad.34tmpg4qz
  10.5061/dryad.0zpc8672t
- Journal of Experimental Medicine published 4 datasets
  10.5061/dryad.5hqbzkhb8
  10.5061/dryad.np5hqbzzz
  10.5061/dryad.j0zpc86kn
  10.5061/dryad.bnzs7h4h4
- Journal of General Physiology published 2 datasets
  10.5061/dryad.3bk3j9kr0
  10.5061/dryad.jq2bvq8gj
- Life Science Alliance published 0 datasets

**Comment by mariaguerreiro** [comment]
Thank you!
