### ISSUE TITLE
SUNY Brockport SSO configuration not working

### ISSUE THREAD

**Issue by sarahklippincott** [datadryad/dryad-product-roadmap#3486]
**Bug description:**

From our contact at SUNY Brockport, their SSO configuration seems to be broken:

> Here are the steps I'm doing:
> 1. https://datadryad.org/stash/sessions/choose_login
> 2. Click "Login or Create your ORCID iD"
> 3. choose " Or.. Sign in through your institution"
> 4. Fillin "SUNY The College at Brockport" and click Continue
> I notice that the logo does not populate, which is a sign that something is wrong.
> 

I've forwarded an email to devs@datadryad.org with additional details.

**Comment by ahamelers** [comment]
Signing in through ORCID isn't connected at all to logging into a tenant institution, they are 2 separate actions.

    Login with ORCID
    Select and login (on the Dryad site) to tenant institution

There's no separate authentication set up for most of the sponsored SUNY institutions, so users should select 'State University of New York' from our institution list for now. This is an IP address authentication, so users who aren't signing in from a campus IP address (assuming SUNY provided us with the full range for all the covered institutions!) may need to email the helpdesk using an email address from the appropriate institution to have the member institution manually added to their account.

**Comment by sarahklippincott** [comment]
@ahamelers Here's the logo file for finishing this set-up:
![bptlogoallinonecolorjpeg (1)](https://github.com/user-attachments/assets/a31c7afd-29fc-40c3-8f26-478f181d4d21)

I'm coordinating with Catherine at the SUNY consortium to make sure we didn't miss anyone else.
