### ISSUE TITLE
Landing page rendering oddly when window is made narrow - left side cut off

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3487]
**Bug description:**

When we open certain datasets to see the preview landing page in a window that is not full-size, it cuts off the left side of the screen (this does not usually happen). See example photo of left edge:

![image](https://github.com/datadryad/dryad-product-roadmap/assets/124197995/ed587ac1-ce74-484d-af91-caa7d8503567)
Resource ID 303063

Also happening with this one https://datadryad.org/stash/dataset/doi:10.5061/dryad.zs7h44jhz (resource ID 297469)

**Steps to reproduce:**

We have opened it in Chrome, Edge, and Firefox with the same results (several of us). If you look at the window full-screen it's fine, but when you start to shrink the window width-wise, it starts cutting off the left side until the window is reallythin, when it corrects itself. 

**Expected behavior:**
We should always be able to see the left margin

**Comment by kailashap** [comment]
Same issue in this dataset DOI: 10.5061/dryad.vt4b8gtz8 ([landing page](https://datadryad.org/stash/dataset/doi:10.5061/dryad.vt4b8gtz8))

**Comment by mahirst** [comment]
Examples identified by Evangeline and Kathi: 
10.5061/dryad.m905qfv9p
resource ID: 303934

10.5061/dryad.w9ghx3fz4
Resource ID: 303687

10.5061/dryad.brv15dvg6
Resource ID: 303603
