### ISSUE TITLE
Unable to edit status of dataset (DOI: 10.5061/dryad.ht76hdrqj)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3488]
10.5061/dryad.ht76hdrqj

Dataset status is "In Progress" but in Activity Log it's "Curation". 
I'm unable to move into editing mode to assist the author. Can you update the status to "Curation" please?

**Comment by ahamelers** [comment]
@jleighherzog version 2 is in curation (I do not know how you did that), but version 3 is in progress with the author. Could the author submit or delete the in progress version? If you want to modify the in progress version, could you try forcibly editing it?
