### ISSUE TITLE
Revert published dataset back to PPR 10.25338/B8XS8T

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3499]
This author has two published versions of their dataset, but also did not realize what "publishing" meant and now needs the PPR functionality for a double-blind review. 

Resource ID of latest pub'd version: 303188 (previously pub'd version 244160). Let me know if we need to talk about this one.

**Comment by ahamelers** [comment]
I've done this, but the dataset has 3 citations apparently so this action is pretty suspect. Definitely we should keep an eye on it and publish it again in max 6 months

**Comment by ahamelers** [comment]
Also, when it is published, we should back date the publication date, and we should also re-publish 244160 with a backdated publication date!

**Comment by lauradryad** [comment]
Yah I know.. I've put a reminder in to look at it again. It was just a weird situation because they needed the PPR functionality again and def didn't understand the process we have. -- also the citations are just the related works, those are still backwards (it lists things that the dataset cites, not that have cited the dataset, exactly)

**Comment by lauradryad** [comment]
And the author changed their mind. Please undo everything. My apologies.
