### ISSUE TITLE
Add dataset back to user's account (merge issue)

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3500]
**Bug description:**
I received an email from an author that they had logged in to Dryad two separate ways (once before 2020 and then recently), so I merged their accounts and made sure that the correct ORCID number was shown on their account; however, it seems that all their datasets that had been ported in in 2020 are now not attached to this user. 

ORCID: 0000-0002-7232-1757

Resource ID of dataset that were under her account (and should be again):

- 28020 (10.5061/dryad.723m1)

**Comment by ahamelers** [comment]
Looks like the user account that owned it was a curator (at that time). Weird! Fixed.
