### ISSUE TITLE
Transfer dataset ownership (DOIs: 10.5061/dryad.zs7h44jj6 & 10.5061/dryad.kh18932g7)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3508]
Please transfer ownership of the datasets below from 

Patric Champgne | [patrickchampgne@gmail.com](mailto:patrickchampgne@gmail.com)
ORCID:  0000-0001-9125-8493
to 
Stephanie Avery-Gomm's | [Stephanie.Avery-Gomm@ec.gc.ca](mailto:Stephanie.Avery-Gomm@ec.gc.ca)
ORCID: 0000-0003-2882-0978

The two datasets to be transferred are:

Identifying Tide-Dependent Islands in Atlantic Canada: A Satellite Analysis Approach Using Advanced Cloud Filtering Techniques.
DOI: 10.5061/dryad.zs7h44jj6 

Nova Scotia Coastal Islands Geospatial Database
DOI: 10.5061/dryad.kh18932g7

**Comment by ahamelers** [comment]
Done
