### ISSUE TITLE
Unpublish #304970 (10.5061/dryad.bk3j9kdmj)

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3510]
I accidentally published the wrong dataset. Please remove the published version of this dataset and revert to its previous status (submitted.. or curation if that's easier).

**Comment by ahamelers** [comment]
Done

**Comment by ahamelers** [comment]
Is that a duplicate of https://datadryad.org/stash/dataset/doi:10.5061/dryad.bk3j9kdmj ?
