### ISSUE TITLE
Design BioRxiv interaction

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3517]
BioRxiv wants a submission workflow that differs slighly from our current API.

Desires:
- New API feature that allows submission of manuscript info, but instead of automatically redirecting the user to the editURL, trigger an email that invites the user to submit, and include the editURL in the email. This feature could be a completely new API call, but it may be easier to add as a flag in the submitted metadata.
- New search API feature that allows a constraint for a particular journal or journal_org, scopeable to arbitrary date ranges. This feature must allow scoping to BioRxiv content.

**Comment by ryscher** [comment]
Design is in the BioRxiv meeting notes; will be moved into a new ticket for implementation.

**Comment by alinvetian** [comment]
We need a new email template for this email? Cc: @lauradryad
