### ISSUE TITLE
Add dataset to user's Dryad account (ORCID currently not connected to old dataset)

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3518]
Resource ID 8620 was created in 2016 by an author who does have a Dryad account through ORCID, but this dataset was not connected to her ORCID so she can not see this one on her dashboard

Her account is 0000-0002-1560-6772. Please add her ORCID to that dataset and that dataset to her account (not sure if that's all the same process).

**Comment by ahamelers** [comment]
I merged the users and added the ORCID to the dataset author list
