### ISSUE TITLE
Dataset 10.5061/dryad.s38kf65 files inaccessible

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3526]
Resource ID 22912: We are unable to access the uploaded document, and this is one where the corresponding author's ORCID is also not linked. A user reached out to say that they want to access the document, but I also could not. 

It also has no author email address (or affiliations for that matter - I'm not sure when we started requiring those)

**Comment by ahamelers** [comment]
This is one of those 'comma in the filename' ones, it's an AWS problem I think, adding it to Ryan's big list.

I wonder if we should just start removing the commas? Would that be crazy, just to do a big comma sweep removal on AWS and in our database? I don't know if @ryscher has time to look at any other solutions...

**Comment by ahamelers** [comment]
Oh, also I should note, just like the others (#3190, #3169, #3188) this is a problem on Chrome only and the file is downloadable on Firefox. So that's a temporary solution for people who need the file @lauradryad !

**Comment by lauradryad** [comment]
Thanks! This is also the same dataset as the ticket #3290

**Comment by lauradryad** [comment]
@ahamelers can you take the comma out of this file specifically? I had just realized that this is one is fairly popular and we've gotten asked about it multiple times.

**Comment by ahamelers** [comment]
@lauradryad I have managed to fix all of these! All these old files should be accessible on chrome now. Could you please close out any salesforce tickets associated with this error?
