### ISSUE TITLE
Change name of Zenodo instance to match Dryad dataset 10.5061/dryad.02v6wwqc0

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3527]
Author updated the name of their dataset post-publication (new version is Resourc ID 299577) and the name change did not go to Zenodo. Author wants the titles to match. 

Zenodo link: https://doi.org/10.5281/zenodo.11491149 and the title should be "Transitions between colour mechanisms affect speciation dynamics and range distributions of birds"

**Comment by ahamelers** [comment]
Ah interesting, the new title was waiting in there but it needed to be 'published'. This is done.
