### ISSUE TITLE
Published dataset was versioned but changes didn't go to Zenodo

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3532]
From author [my additions in brackets]:
"I submitted a Dryad upload (10.5061/dryad.hhmgqnkm7) [resource ID 305551 of most recently published version] with some code files that were moved to Zenodo (https://zenodo.org/records/7473207)[this is the backup, not a software/supp one]. I had to change some of the description of the Dryad file (removing an incorrect DOI link) but Zenodo was not updated."

Can we push the new version to Zenodo as well? The info that's currently on Zenodo is incorrect.

**Comment by ahamelers** [comment]
@lauradryad What information on Zenodo is incorrect? The abstract etc. all look right to me

**Comment by ahamelers** [comment]
Okay, done
