### ISSUE TITLE
PPR ticket for Audrey

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3533]
02748 Resource ID is the specific question - was an email sent to the author and journal on that one even though the system immediately realizes it should be put into Curation again because it was already in Curation status (can you put the “was it in curation previously” check before the “does the journal require this to be in PPR” part so that it doesn’t cycle through both statuses (PPR and then Curation) in a row like that?

**Comment by jeremywalter** [comment]
Perhaps related: I edited a dataset released from PPR today and the system sent it back to PPR (taking it out of my work queue so I had to go searching for it to figure out what happened to it): 
![image](https://github.com/user-attachments/assets/e8537e7a-fc23-4a57-8ca8-e6cd1230d19c)
