### ISSUE TITLE
Resolve uncertainty about allow_blackout embargos

### ISSUE THREAD

**Issue by ahamelers** [datadryad/dryad-product-roadmap#3535]
Journals from 2 publishers are still using the automatic 1 year embargo.

1. Find out if this is still required and
2. Get rid of the check if not or
3. Add a notification to the publication date popup warning curators of the auto embargo

**Comment by ryscher** [comment]
Maria is following up with the journals to determine whether we can switch them to the standard process.

**Comment by ahamelers** [comment]
@mariaguerreiro Is there any update on this?

**Comment by mariaguerreiro** [comment]
@ahamelers I have been away, I will aim to contact these journals this week, thanks.

**Comment by mariaguerreiro** [comment]
@jleighherzog I should have asked you to look into this, but just wanted to let you know that I approached these two publishers and cc'ed you.
Thanks!

**Comment by mariaguerreiro** [comment]
@ahamelers Ryan told me that the Alliance of Crop, Soil, and Environmental Science Societies (ACSESS) and the British Editorial Society of Bone and Joint Surgery were the two publishers, but I cannot find the journals associated with the  British Editorial Society of Bone and Joint Surgery with a Dryad integration. They're not members and I do not see their titles on https://datadryad.org/stash/journals, so where do I find this information, please?

**Comment by ahamelers** [comment]
@mariaguerreiro https://datadryad.org/stash/journal_admin?q=&sponsor=51

You're right, they have no payment plan! The auto-embargoing must be data from an old integration in our system, that we're honoring just to make things difficult for ourselves 😆 I'll just remove that—so it's only ACSESS we need to worry about.

**Comment by mariaguerreiro** [comment]
Great, thanks for letting me know!

**Comment by mariaguerreiro** [comment]
@ahamelers ACSESS is fine with changing the setting to remove the embargo, but we want to have the option to implement an embargo in specific cases, so we can remove this as a default setting for their journals, thanks!
