### ISSUE TITLE
Correct ORCiD for corresponding author

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3538]
One of Kathi's datasets had an ORCiD/author name mismatch. The corresponding author asked for the ORCiD to be updated so that it matches his name.

doi:10.5061/dryad.nk98sf82j
resource ID: 307793

The corresponding author is Yogesh Goyal with the ORCiD 0000-0003-3502-6465

Thank you!

**Comment by ahamelers** [comment]
Hi Molly,

This is done, but now the submitting user is not in the author list, and the corresponding user has no Dryad user account. Someday soon (when we allow multiple editors) this will be no problem, but for now, this means trying to edit the dataset may result in some confusing errors when you try to submit.  

Please keep an eye on this and let me know how it goes. The best solution would be for Yogesh Goyal to create an account, become the owner of the dataset, and make any future edits needed, but if that does not happen we may need to switch the ORCID back to Rohan Sohini's temporarily and only correct the ORCID when it is ready for publication.
