### ISSUE TITLE
Add examples to README wizard

### ISSUE THREAD

**Issue by ahamelers** [datadryad/dryad-product-roadmap#3539]
README examples to be provided by curators.

**Comment by mahirst** [comment]
10.5061/dryad.jdfn2z3j3
This README is exceptional for showing how to set up, access, and run neural network deep learning code. It can also be referenced for code/software data more generally.

10.5061/dryad.h70rxwdq5
This README outlines the different types of file formats and their contents, as well as usage, purpose, compatibility, accessibility, recommended software, and organization of the data files.

10.5061/dryad.rr4xgxdg6
This README is great for describing the contents of MATLAB files. 

10.5061/dryad.nzs7h44xg
This README details several file types, including genomic data.

10.5061/dryad.18931zd25
This README includes good detail for genomic VCF files and companion scripts.
