### ISSUE TITLE
High priority, quick task: Put published dataset back into PPR status

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3540]
Please put the published dataset with resource ID 307028 back into PPR status. Thank you!

**Comment by ahamelers** [comment]
@mahirst The latest version wasn't actually submitted, now that that's been set to peer review that might be a problem. Can it be deleted and the previous version set to PPR?

**Comment by mahirst** [comment]
@ahamelers Yes!

**Comment by ahamelers** [comment]
Done!
