### ISSUE TITLE
High priority (sorry): transfer ownership of dataset

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3555]
Sorry for making this a higher priority, but there were some situations.

Please transfer the ownership of this dataset:
DOI 10.5061/dryad.pg4f4qrzk
Resource ID 308035

to:
Sydney Bird 
ORCiD 0009-0000-9199-3885

**Comment by ahamelers** [comment]
This user is already set as the owner of the dataset, and I've also made sure the author orcids are correctly set.

**Comment by mahirst** [comment]
Sorry for the confusion, the old owner is Shelby Fleischer. They want it changed to Sydney Bird. It's currently set as Shelby Fleischer as the owner

**Comment by ryscher** [comment]
I confirmed that Sydney Bird is the owner of the current version. For extra measure, I set Sydney Bird as the owner for all versions.
