### ISSUE TITLE
Cannot create a SalesForce case for a dataset -- error setting tenant_id

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3563]
I'm trying to AR a dataset, but the SF button leads to an error page and then a "this page doesn't exist" page. I've also refreshed the page to see if clicking the button creates an SF case, but it does not. I also asked the team to check and see if the error pops up on their end (spoiler alert: it does).

Resource ID: 308028
doi:10.5061/dryad.80gb5mkzw

![Screenshot 2024-08-05 at 4 06 12 PM](https://github.com/user-attachments/assets/4292fe85-eb91-4377-9670-97be02319142)

**Comment by ryscher** [comment]
The immediate problem is fixed. The problem was that the user account did not receive a `tenant_id`. I'm assuming this step is skipped when the account is "created" by an API call.

Keeping this ticket open so we can find and correct the underlying problem.

**Comment by ryscher** [comment]
Proposed solution: When the ORCID login completes, and the tenant selection screen is shown, automatically set the tenant_id to `dryad`, and allow the tenant selection screen to override it.
