### ISSUE TITLE
Remove fee waiver from dataset sponsored by JEB

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3564]
Hi again! I've got a dataset where the fee was auto-waivered (back when that was a thing), but the author just included journal metadata, and the journal is a sponsoring journal.

Please remove the waiver, so that JEB will sponsor this dataset.

Resource ID: 308170
Activity log: https://datadryad.org/stash/ds_admin/93701/activity_log

**Comment by ryscher** [comment]
Payment info updated
