### ISSUE TITLE
Zenodo instance not active on published dataset with 'software'

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3565]
Had a HD email that an author's Zenodo link is broken. When I go to the Zenodo DOI, it also goes to the 'DOI not found' page. I tried to edit the dataset, but I cannot get the Software files that way either in reviewer mode. 

DOI 10.5061/dryad.3n5tb2rr2
Resource ID: 287251
zenodo doi: https://doi.org/10.5281/zenodo.10537213

**Comment by ryscher** [comment]
Fixed
