### ISSUE TITLE
Large file download

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3566]
Assist with large download for 10.5061/dryad.ncjsxkt3h

**Comment by ryscher** [comment]
File downloaded to the VE for curators to deal with. Have not put it into Dryad yet, in case curators determine something should be changed.

**Comment by lauradryad** [comment]
any updates on this one?

**Comment by ryscher** [comment]
User reported that some files were missing when we unzipped the large zip. User provided an expanded directory for us to cross-reference, but our credentials to their server stopped working.

**Comment by ahamelers** [comment]
Is this now resolved?

**Comment by ryscher** [comment]
Dataset is updated in Dryad. Curation still ongoing....
