### ISSUE TITLE
Empty CEDAR  files

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3567]
Sometimes CEDAR users do not enter anything in the CEDAR editor, but a file is added to the dataset. This file may contain just a stub, or the full metadata schema with none of the actual fields filled out. We want to only save the file if a user actually entered something.

Example: doi:10.5061/dryad.qz612jmq1 was published with a stub in the DisciplineSpecificMetadata.json

**Comment by ahamelers** [comment]
CEDAR controller was saving blank json. We should clean these up in the database and potentially republish.
