### ISSUE TITLE
Updating the "Fees" section on the "Join us" page

### ISSUE THREAD

**Issue by mariaguerreiro** [datadryad/dryad-product-roadmap#3568]
Hello - can we please update the wording on the Fees section as outlined in this document:

https://docs.google.com/document/d/198L-HxmjOblPisBWygLLpIqldYsa6DwwVHvXkZ5cc5k/edit?usp=sharing

Many thanks!

Maria

**Comment by ahamelers** [comment]
Hi @mariaguerreiro , do we keep the descriptions of the membership levels and fees, and the table for publishers?

**Comment by ahamelers** [comment]
Received clarification from Ryan
