### ISSUE TITLE
American Medical Informatics Association

### ISSUE THREAD

**Issue by mariaguerreiro** [datadryad/dryad-product-roadmap#3569]
Can you please reinstate AMIA under a deferred plan, please? I believe I changed this on the Admin dashboard, but it is my understanding that you need to update the payment plan in other places of the database. Many thanks!

**Comment by ahamelers** [comment]
As far as I know, changing the payment plan of the associated journals in journal management, as you have done, is all that is necessary. @ryscher ?

**Comment by ryscher** [comment]
Confirmed that this is done
