### ISSUE TITLE
Confirm metadata template for Wildilfe Biology

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3570]
This is the existing, incorrect template for _Wildlife Biology_:
> Journal Name: Wildlife Biology
> Journal Code: **ECOG**
> Online ISSN: **1600-0587**
> Journal Admin Email: [me@wildlifebiology.org](mailto:me@wildlifebiology.org)
> Journal Editor: Maria Persson
> Journal Editor Email: [me@wildlifebiology.org](mailto:me@wildlifebiology.org)
> MS Reference Number: WLB-2023-01227.R4
> Publication DOI: 10.1002/wlb3.01227

The JOURNAL CODE and ISSN are incorrect which made the Import Metadata feature fail. The journal office confirmed that they have made the changes on their end. Sharing in case we need to make updates on our side. 

This is the correct metadata template: 
> Journal Name: Wildlife Biology 
> Journal Code: **WLB**
> Online ISSN: **1903-220X**
> Journal Admin Email: [me@wildlifebiology.org](mailto:me%40wildlifebiology.org)
> Journal Editor: Maria Persson
> Journal Editor Email: [me@wildlifebiology.org](mailto:me%40wildlifebiology.org)
> MS Reference Number: WLB-YEAR-NUMBER (e.g. WLB-2023-01232)
> Publication DOI: 10.1002/wlb3.NUMBER (e.g. 10.1002/wlb3.01232)

**Comment by ahamelers** [comment]
I don't believe anything needs to change on our end. We're already expecting the correct template

**Comment by ahamelers** [comment]
@jleighherzog We are still receiving the incorrect (Ecography-coded) template for Wildlife Biology manuscripts, as of today, so it looks like the journal office has not completed the change on their end. Any idea when the template will be fixed on the journal side?

**Comment by jleighherzog** [comment]
@ahamelers : Thanks for letting me know. I contacted the editorial office today (Michael Tobler)

**Comment by jleighherzog** [comment]
Received a notification today that another template on their side has been edited! Should work now.
