### ISSUE TITLE
Delete latest version of dataset 10.5061/dryad.8gtht76wm

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3573]
I'm not sure what happened but somehow the author created a new version a minute apart which removed all the files they uploaded.

![image](https://github.com/user-attachments/assets/dbdeaa45-2506-4b77-821a-7d942f4aa255)

Please remove the August 8 version (resource ID 309604) so it reverts to the August 7 version with all the files (309603). It should go into curation from there. I believe those are the correct resource IDs, but if you can check, the one with all the .tif files uploaded is the one that should be retained.

**Comment by ahamelers** [comment]
This is done. Not sure of the cause, but it may have to do with the intermittent slowness people have been experiencing off and on. I notice trying to edit or delete an in progress version of this specific dataset takes a long time.
