### ISSUE TITLE
Dataset link on user profile page should go to Activity Log

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3576]
**Problem description, and links to relevant helpdesk tickets:**

In the fix for this ticket (https://github.com/datadryad/dryad-product-roadmap/issues/3430), the link goes to the landing page of the dataset, but this does not allow us to grab the DOI (which is usually what we need) when the dataset is in progress, so we would prefer if this link went to the Activity Log OR there was also a button where we could get to the activity log from this view.

**Comment by ahamelers** [comment]
Is there not a clock link that goes to the activity log?

**Comment by lauradryad** [comment]
![image](https://github.com/user-attachments/assets/d7243bc3-050b-4e07-a829-405859d22b3c)

no clock - we can't even see the whole title

**Comment by ahamelers** [comment]
there must be a problem with the icon or with the permissions to make it appear. Will fix.
