### ISSUE TITLE
API updates for BioRxiv

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3581]
Followup from #3517 

API updates to accommodate the workflow used by BioRxiv:
1. When creating a dataset through the API, a new flag `triggerSubmitInvitation` may be added to the dataset JSON. When this flag is true, Dryad will trigger an email to the dataset owner (as specified in the JSON) that invites them to complete their Dryad submission. Note that an error will be thrown if the flag is true but the dataset owner does not include an email address.
2. [Search API](https://github.com/datadryad/dryad-app/blob/main/documentation/apis/search.md) enhancements:
    - Add a parameter for `modifiedBefore` to complement the existing `modifiedSince`, allowing selection of an arbitrary date range, which may be a single date.
    - Add a parameter for `journalISSN` to complement the existing tenant filter.

**Comment by alinvetian** [comment]
@ryscher do we want to save the value that was sent for `triggerSubmitInvitation` ?

**Comment by ryscher** [comment]
I don't think we need to save the value in the dataset, but we could log the fact that an email was sent in the curation activities.

**Comment by ryscher** [comment]
I sent draft email text to @lauradryad for review.

**Comment by ryscher** [comment]
Let's move forward with this email text until we hear otherwise:

```
<p>Dear <%= @user_name %>,</p>

<%= journal_name %> has informed us of your recent manuscript titled "<%= manuscript_title %>", and you are invited to deposit data associated with the manuscript to Dryad. 

To upload your data to Dryad, please visit https://datadryad.org/ and select 'submit now' (you may be prompted to log into Dryad). Please note that the journal name and manuscript ID <%= manuscript_id %> are essential fields in the submission form. You will be able to upload files up to 300GB via the web interface. For further information on submitting data to Dryad please see this webpage: https://datadryad.org/stash/submission_process#upload-methods

Once you have uploaded your data, please include the Dryad DOI in the Data Accessibility section of your manuscript. 

Your Dryad entry will be made public once it has been reviewed by our curation team.

Please let us know if you have any questions about this process.
```

**Comment by lauradryad** [comment]
Sorry! Was waiting on edits:

<p>Dear <%= @user_name %>,</p>

<%= journal_name %> has informed us of your recent manuscript titled "<%= manuscript_title %>", and you are invited to deposit data associated with the manuscript to Dryad. 

Please visit the Dryad site to (review our instructions)[https://datadryad.org/stash/requirements] for preparing your data and uploading files prior to initiating your data submission. To upload your data to Dryad, please visit https://datadryad.org and select 'Submit now' (you may be prompted to log into Dryad). Follow the prompts in the submission form and select to either keep your dataset in Private for Peer Review, which will prevent it from being curated and published, or submit it to our curation queue to have it published. 

After submission, Dryad will send you an email acknowledgment of your data submission that includes two important links and further instructions.

If you have any questions, please contact Dryad at <a href="mailto:<%= @helpdesk_email</a>.

**Comment by alinvetian** [comment]
`editLink` should be present in the email.
 I added this template as placeholder https://github.com/datadryad/dryad-app/pull/1826/files#diff-2783a4624b528019807afc298eefe364c4effbecf09823f10e10e4d5c6a9e1d5

**Comment by ryscher** [comment]
Right, here's a slightly updated version that includes the editLink:
```
Dear <%= @user_name %>,

<%= journal_name %> has informed us of your recent manuscript titled "<%= manuscript_title %>", and you are invited to deposit data associated with the manuscript to Dryad.

Please visit the Dryad site to <a href="https://datadryad.org/stash/requirements">review our instructions</a> for preparing your data and uploading files prior to initiating your data submission. To upload your data to Dryad, you may use the following link:

<%= @edit_url %>

You may be prompted to log into Dryad. Follow the prompts in the submission form and select to either keep your dataset private during peer review, which will prevent it from being curated and published, or submit it to our curation queue to have it published.

After submission, Dryad will send you an email acknowledgment of your data submission that includes important links and further instructions.

If you have any questions, please contact Dryad at <a href="mailto:<%= @helpdesk_email %>?subject=Dataset with DOI: <%= @resource.identifier_str %>"><%= @helpdesk_email %></a>.
```
