### ISSUE TITLE
PPR message in dataset not showing at the right time

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3582]
Had a dataset today where the MS data was entered in the dataset and the activity log shows that the MS was accepted in April. 
![image](https://github.com/user-attachments/assets/a4766d3c-a366-4dc3-b84c-d530d9b7733c)

However, when I go in to edit the dataset, the box on the review page still says that the dataset will go to PPR because the manuscript has not been accepted yet:
![image](https://github.com/user-attachments/assets/72ceaf0b-ca10-4071-97ba-c11217125017)

This is confusing authors, thinking that they have no agency to push this through the system (yes, I know they can look at the status of the dataset in their dashboard, but they aren't always doing that). 

I'm not sure when they entered the journal metadata because we can't see the dates when that happened anymore on the activity log.

Resource ID: 310946 but the one accepted was 280532

**Comment by ahamelers** [comment]
I think this will be fixed when https://github.com/datadryad/dryad-app/pull/1810 is released
