### ISSUE TITLE
Reactivate Email Notifications for UCSB Deposits

### ISSUE THREAD

**Issue by rcurty** [datadryad/dryad-product-roadmap#3587]
We have noticed that we are no longer receiving email notifications for new deposits submitted or published. The last notification we received from no-reply-dryad@datadryad.org was on July 25, 2024.
Could you please verify the issue and reactivate the notifications for us?

**Comment by ryscher** [comment]
Hi Renata, we currently have notifications set to rds@library.ucsb.edu -- Is this correct?

**Comment by rcurty** [comment]
@ryscher Yes, this is the correct email address that includes everyone on our team. We received a new notification today at 11:24 a.m. It seems that notifications are back to normal.
