### ISSUE TITLE
2 bookmark bugs in the new Admin Dashboard

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3589]
I found two little bugs in the new admin dashboard. Screenshots are attached.

1. After bookmarking a "saved search" on my Chrome browser, the "results" number at the top right of the admin dashboard does not match the actual number of results. For example, when there are 5 results in a saved search, clicking on the bookmark for that saved search shows any number from 0, 1, 79k to 84k. My screenshot: ![Screenshot 2024-08-15 at 11 51 55 AM](https://github.com/user-attachments/assets/e2bbac37-bee2-44f4-a119-9c532dfe09db)
2. From Laura: Page numbers disappear- when you click the link it says 1 result and no additional pages, but that's the queue so obviously that's wrong. 
Laura's screenshot where there are about 200 results for this particluar search:
![image](https://github.com/user-attachments/assets/7a9928dd-e248-4f2f-8cd9-425b0aff57c8)
Link that Laura uses: https://datadryad.org/stash/admin_dashboard?clear=true&search=2&sort=queue_date&direction=asc&page_size=50&page= 

(MH) Interestingly, when I click the link Laura shared, I don't have the issue.

**Comment by ahamelers** [comment]
The count & page number calculation is taken from an existing count check if possible. This is meant to be reset when on the first page of results, but for some reason this wasn't working with the bookmarked "clear" parameter. I think I've fixed it by having it reset explicitly when the clear param is included.
