### ISSUE TITLE
ORCID Integration & Ownership Transfer

### ISSUE THREAD

**Issue by rcurty** [datadryad/dryad-product-roadmap#3591]
Ref Deposit: 10.5061/dryad.547d7wmh3 (published)

The depositor has requested that the corresponding author be changed to Craig Montell (cmontell@ucsb.edu), ORCID: [0000-0001-5637-1482](https://orcid.org/0000-0001-5637-1482). Craig reported that he hasn't received the automatic email to link his ORCID and needs assistance.

"Hi Renata,

This manuscript associated with this dataset has been accepted for publication and the dataset is now ready to be released for curation/published. Is it possible to transfer "ownership" of the dataset to Craig Montell (who I have included on this email)? I am new to Dryad and it appears that the submission is tied to my ORCID ID. 

Thanks,
Geoff "

**Comment by ahamelers** [comment]
Hi Renata,

I've given ownership of the published version to the requested user.
