### ISSUE TITLE
PubUpdater Search has no results for 'Published'

### ISSUE THREAD

**Issue by jeremywalter** [datadryad/dryad-product-roadmap#3592]
**Bug description:** Filtering search results for 'Published' produces no results in PubUpdater

**Steps to reproduce:** https://datadryad.org/stash/publication_updater?list_search=&status=published

**Expected behavior:** Previously this search yielded thousands of results. Also the recommended [workflow](https://docs.google.com/document/d/1Gmv0n4ID_9WA7cRP0KgMN4XB-Ea0eTGh1lU2G0LE-ZI/edit?usp=sharing) for PubUpdater starts with using this search to focus on datasets that most need DOI linkages.

**Comment by ahamelers** [comment]
Not a bug, they've just all been processed
