### ISSUE TITLE
New homepage rotation images: August 2024

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3596]
I'm taking over this task for Sarah until further notice :)

Image link: https://unsplash.com/photos/man-in-white-crew-neck-t-shirt-holding-white-smartphone-q2BpMaqzDNQ

Caption:
Photo by [[Jeswin Thomas](https://unsplash.com/@jeswinthomas)] on [Unsplash](https://unsplash.com/photos/man-in-white-crew-neck-t-shirt-holding-white-smartphone-q2BpMaqzDNQ)

**Comment by ahamelers** [comment]
I don't know that this image works very well
<img width="1258" alt="Screenshot 2024-08-26 at 13 50 48" src="https://github.com/user-attachments/assets/51c23f0f-8473-4c30-a190-be022c1f9851">

**Comment by ahamelers** [comment]
At these dimensions and with the overlay, it's pretty hard to see most of this image. Is this what you were expecting?

<img width="1277" alt="Screenshot 2024-08-26 at 13 56 04" src="https://github.com/user-attachments/assets/18c1c026-be3c-4a08-a506-e0006652c834">

**Comment by mahirst** [comment]
True, how about this one? I'm using images that Sarah collected, but I think I can find more. 

Image link: https://unsplash.com/photos/black-and-white-printed-textile-ynlW4w7OHDs

Caption:
Photo by [[USGS](https://unsplash.com/@usgs)] on [Unsplash](https://unsplash.com/photos/black-and-white-printed-textile-ynlW4w7OHDs)
