### ISSUE TITLE
PPR usage report

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3598]
As part of the analysis on changing the payment process, we need a report on how often PPR is used.

Make a report for all datasets that have ever had a PPR status. It should include at least these fields: DOI, created_at, current curation status

**Comment by alinvetian** [comment]
@ryscher Do we want this as a page in the app so that admin can see it, or a one time only CSV export?

**Comment by ryscher** [comment]
This only needs to be a one-time report, so please do it in the easiest way possible.

**Comment by ryscher** [comment]
Alin sent this report via email. Thanks!
