### ISSUE TITLE
Fee waiver report (01/01/2024-08/23/2024)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3599]
Possible to pull a report to share with Cxore that lists all fee waivers applied to datasets between January 1, 2024 to August 23, 2024. This information should be recorded in the Payment Information section of the Activity Log. 

Report should include: 
- DOI
- Waiver status
- Waiver basis
- Current data status, if possible

We're working confirm whether the waiver information we have matches what Cxore is pulling.

**Comment by ahamelers** [comment]
@jleighherzog Is this still needed?

**Comment by jleighherzog** [comment]
No. Will close this. The manual counts we have should suffice.
