### ISSUE TITLE
Journal emails for PPR/published

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3604]
When testing journal emails for ACS, it was unclear whether the PPR/published emails are being properly triggered on the sandbox system. Trying to track down whether this is a config issue or a problem that affects production as well.

**Comment by ahamelers** [comment]
The curators received communications from a journal office about these emails just last week (because there was an issue with which journal ISSN was set). So I believe the production emails are going out.

https://dryad.slack.com/archives/C06GTNUBG1H/p1724163706358569

**Comment by ryscher** [comment]
On non-production systems, the emails are normally disabled by config flag `send_journal_published_notices`. To send a test message:
1. Add the appropriate email addresses to the journal config. It's a good idea to add yourself, so you can verify the email is sent.
2. Update `send_journal_published_notices` for the Rails environment you're using. BUT BIG CAVEAT: Do this on server 1 of the group! (See below)
3. Restart puma to pick up the new config
4. Create the dataset and process it as needed
5. Revert the flag, so we don't accidentally send emails to journals when doing future tests.
6. Restart puma again

Details for next time we have to dig into this....The PPR status change doesn't happen in the Rails application as the dataset is originally being submitted. When the dataset is submitted, this happens:
1. Whichever server was connected to the submitter's browser is the server that puts the dataset into "processing" status and kicks off the thread to copy files to the long-term store.
2. Only one server (typically server 1 of the group) is running the status_updater, so that server picks up the processing status and checks whether the copy is complete.
3. When the status_updater determines that the dataset is processed, it updates the dataset's status and fires emails. However, because the status_updater is running in the same environment as the Rails application, any logging information goes to the main Rails application log. (And maybe the thread actually runs in Puma???)
4. This means that even if the initial submission occurs on server 2, relevant log output will appear on server 1.
