### ISSUE TITLE
To asterisk or not to asterisk?

### ISSUE THREAD

**Issue by ahamelers** [datadryad/dryad-product-roadmap#3610]
We add asterisks to affiliation and funder names in some circumstances—as in, they are recorded in the database as a part of the name—to alert curators to them being 'unmatched'.

This addition of asterisks is not very reliable (#3055) and isn't very noticeable in cases where it does work.

- What is the asterisk meant to indicate, exactly? Just that the name as entered is not associated with a ROR ID?
- If this is the case, wouldn't it be easier, more reliable, and ultimately more easily noticeable not to go to the bother of adding and removing asterisks to the name depending on the viewer, but instead just to programmatically highlight in some vivid color institution names that have empty ROR ID columns in the database?

**Comment by ryscher** [comment]
Sorry, the asterisks date back to the time when Ryan was learning Rails, and didn't know better ways to handle the situation. Yes, let's revamp them. 

The meaning of an asterisk is currently: "This value is not tied to a controlled vocabulary. Maybe the submitter couldn't be bothered to click on the vocabulary term. Maybe the value is not in the vocabulary. Regardless, the associated dataset won't show up correctly in searches and reports that depend on the vocabulary."
