### ISSUE TITLE
Published resources with file_view false

### ISSUE THREAD

**Issue by ahamelers** [datadryad/dryad-product-roadmap#3615]
Many resources are published but with `file_view` set to false, and this does not seem intentional. Depending on whether the files were published previously, this means individual files are still downloadable, but the zip button does not work for non-privileged users. (See #3206 , #3186 )

There are, right now, 6005 affected resources from 4981 identifiers:
```ruby
StashEngine::Resource.joins(:last_curation_activity).where(file_view: false, last_curation_activity: {status: 'published'
})
```

This doesn't have a clear cause, many of the latest seem to be auto-published ones, but this was clearly a problem during the transition as well and the oldest affected was published in 2018.

- [ ] Why is this happening? How are resources being published without file_view being set to true? Find and fix this!
- [ ] Fix the affected resources (do we need to do any additional checks to verify, or can all 6005 be set to `file_view: true`?)

**Comment by alinvetian** [comment]
The issue is coming from [here](https://github.com/datadryad/dryad-app/blob/ad903d767329adac5340dc3aa6a9912976431308/app/models/stash_engine/curation_activity.rb#L368-L369): 

```
      resource.update_column(:file_view, false) unless changed # if nothing changed between previous published and this, don't view same files again
      resource.update_column(:file_view, false) unless resource.current_file_uploads.present?
```

**Comment by ryscher** [comment]
Ryan will investigate the use of file_view before we do a large DB update

**Comment by ryscher** [comment]
I agree with Alin, the problem stems from having the two separate conditions for setting `file_view` to false in ;`CurationActivity`. We cannot just blindly set all of these to true, though. We want to only set them true when there truly is a change to the files (e.g., `changed || resource.current_file_uploads.present?`

**Comment by ahamelers** [comment]
> We cannot just blindly set all of these to true, though. We want to only set them true when there truly is a change to the files (e.g., changed || resource.current_file_uploads.present?

Why? The file_view value seems to be used in all the download permissions checks to say whether the files for a given resource should be downloadable, whether or not any of those files are new. Should all the downloading permissions checks be changed?

**Comment by ryscher** [comment]
The original purpose was that we only wanted to display a version on the landing page if the files are different than the previous version. I don't think we anticipated it to be used for download permissions. I think if the metadata for a version is published, the files should be downloadable.

**Comment by lauradryad** [comment]
another instance of this: 273184

**Comment by ahamelers** [comment]
> I don't think we anticipated it to be used for download permissions. I think if the metadata for a version is published, the files should be downloadable.

@ryscher for embargoed datasets meta_view is true and file_view is false to indicate _exactly this_: visible metadata with files that cannot be downloaded
