### ISSUE TITLE
Report: Repeat customers

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3616]
1. Submitting authors who submitted in the past
2. Submitting authors who coauthored in the past
3. Coauthors who submitted in the past
4. Coauthors who coauthored in the past
5. Average number of submissions per author (submitting author)

**Comment by alinvetian** [comment]
For point 2. `Submitting authors who coauthored in the past` does the number need to reflect only the submitter authors that were first (in the past) coauthors and then submitters?
Same question for point 3.

Cc @sarahklippincott

**Comment by sarahklippincott** [comment]
@alinvetian Yes, that's correct for 2 and 3

**Comment by alinvetian** [comment]
The report was sent by email
