### ISSUE TITLE
Please delete Resource ID 312536

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3619]
This was a duplicate dataset that is no longer needed. We don't need to retain anything from it and it was never submitted.

**Comment by ahamelers** [comment]
Hi @ryscher , there are a couple of tickets about deleting resources. How do I make sure the associated files are deleted from storage as well? Or is that done automatically (or, are the plans to run some kind of automated check and delete unassociated files in the future)?

**Comment by ryscher** [comment]
Dataset was never submitted, so I ran `destroy` on the Resource. Files will be cleaned automatically by the status_updater.
