### ISSUE TITLE
Please set up a VE accounts for new curators

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3626]
Priority = low (within 3 weeks)

Please set up a virtual environment (VE) account for 

Menaha Vijayakumar
menaha@datadryad.org

Mirjana Brujic
mirjana@datadryad.org

**Comment by jleighherzog** [comment]
@ryscher : Please prioritize

**Comment by ryscher** [comment]
Accounts created and instructions sent.
