### ISSUE TITLE
Change ownership of data submission

### ISSUE THREAD

**Issue by jeremywalter** [datadryad/dryad-product-roadmap#3630]
The lead author replace the submitting author with his own information, but the ORCID is already attached from the original submission. Ownership needs to be changed:

Resource ID: 314809
DOI: 10.5061/dryad.8cz8w9h0c
Previous owner: cheng guo -- author has been replaced, but ORCID still attached to corresponding author

Please change corresponding author/owner to:
Rafal Tokarz
Columbia University
rt2249@cumc.columbia.edu

SF 36467

**Comment by jeremywalter** [comment]
@ahamelers -- currently this submission has the corresponding author/ORCID matchup fixed, but it's still the wrong corresponding author. The request is:

Change corresponding author to: 
![image](https://github.com/user-attachments/assets/4713d18d-3c21-4f39-82c5-a16da7676de3)

Let me know if I'm missing something here or going about this wrong. Molly had taken this from me, but it seems to be stuck now.

**Comment by ahamelers** [comment]
@jeremywalter Do you mean that I should remove the email address from the other author? Currently both authors have emails listed.

**Comment by ahamelers** [comment]
@jeremywalter Disregard my previous comment, I see the issue. It looks like the user deleted the version with my author list/ownership changes, setting it back to a previous version without them. I'll be sure to change more versions this time!

**Comment by ahamelers** [comment]
it should be all right now for the last 3 or 4 versions
