### ISSUE TITLE
"DOI" is replicated in automated emails

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3639]
**Bug description:**
I noticed that "DOI" is duplicated in automated emails in all instances that have this: 
DOI: <%= @resource.identifier_str %>
I believe this happens because @resource.identifier_str contains "doi:" and then the actual DOI.

If the DOI is 10.5061/dryad.cnp5hqccb, for example, then the resulting automated email shows this:

DOI: doi: 10.5061/dryad.cnp5hqccb

**Comment by ahamelers** [comment]
@mahirst @lauradryad Didn't you also want this changed so it's always `DOI: https://doi.org/10.5061/dryad.cnp5hqccb` ?

**Comment by lauradryad** [comment]
I only want it changed in the Submitted to Queue email because that's where they grab it from for their data availability statement
