### ISSUE TITLE
Revert dataset to previous version (10.5061/dryad.zcrjdfnkw)

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3642]
The author accidentally created and submitted a new version after the initial publication, but would like this to be deleted.

The version to retain is: 279561
The version to be deleted is: 309599

**Comment by ahamelers** [comment]
@ryscher once again, I can clear out the 3 or 4 "delete a version" tickets that are open if you can tell me or point me to documentation for what to do for the files!

**Comment by ryscher** [comment]
Destroyed most recent version (309599)
