### ISSUE TITLE
FEBS metadata templates [URGENT]

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3643]
Can you help me sort out the issue that FEBS is having with their metadata communications? 

The 'Import Metadata' function isn't working for this submission: 

> Title: [To be replaced with a title](https://datadryad.org/stash/dataset/doi:10.5061/dryad.m37pvmdbx)
> DOI: 10.5061/dryad.m37pvmdbx

Here's the metadata email: 

> Ref: FJ-24-1028
> Title: Dryad Test #2
> Author: Ruffell, Daniela
> 
> 
> Dear Dr Ruffell,
> 
> Thanks for confirming your desire to deposit one or more datasets to Dryad before the review process commences at The FEBS Journal for your article entitled "Dryad Test #2". In this email, we are passing along information required by Dryad to facilitate the deposition. Please use this URL to complete the data deposition before you start full submission process to The FEBS Journal:
> 
> http://datadryad.org/submit?journalID=JBOT&manu=1234567
> 
> Once you deposit your data package to Dryad, it will receive a unique and stable DOI, which is sent to you for inclusion in the submitted article. Please include the reviewers' link in the 'Dataset URL' field of the datasets question during full submission. Please also ensure that you include the provisional DOI  in the 'Database and Identifier'' field of the datasets question. In the event your submission is rejected after peer review, authors can contact Dryad and arrange for their data package to be transferred to another journal.
> 
> Please let us know if you have any questions; otherwise, we hope the data deposition goes smoothly and we'll look forward to receiving your full submission.
> 
> Best wishes,
> 
> The FEBS Journal Editorial Office
> 
> —------
> 
> Journal Name: The FEBS Journal 
> Journal Code: FJ
> DOI: https://febs.onlinelibrary.wiley.com/journal/17424658
> Print ISSN: 1742-464X
> Online ISSN: 1742-4658
> Journal Admin Email: [febsj@febs.org](mailto:febsj@febs.org)
> MS Reference Number: FJ-24-1028
> Article Status: Submitted
> MS Title: Dryad Test #2 
> MS Authors: 
> Contact Author: Daniela Ruffell 
> Contact Author Email: [ruffell@febs.org](mailto:ruffell@febs.org)
> Keywords:  
> EndDryadContent

**Comment by jleighherzog** [comment]
@mariaguerreiro

**Comment by mariaguerreiro** [comment]
Thanks @jleighherzog Quick note to say that the ticket title should say FEBS and not Canadian Science Publishing. Thank you for raising this with Dev!

**Comment by ahamelers** [comment]
I don't see anything wrong with this template, and it looks like we've previously successfully received FEBS Journal manuscripts and updates, most recently on September 3. But this test manuscript didn't make it into the database. Assigning to @ryscher so he can look into the email mechanisms

**Comment by ryscher** [comment]
Current FEBS emails are fine. The specific email referenced in this ticket is not. It has weird formatting, including newlines in some places between the field names and the values. It is also completely missing the values for "MS Authors".

**Comment by jleighherzog** [comment]
@ryscher : This metadata email is from a live submission. Does the format look okay? 

Journal Name: The FEBS Journal
Journal Code: FJ-24-1493
DOI:
Print ISSN: 1742-464X
Online ISSN: 1742-4658
Journal Admin Email: [febsj@febs.org](mailto:febsj@febs.org)
MS Reference Number: FJ-24-1493
Article Status: Submitted
MS Title: Left-handed conformations of glycyl residues may confer protection against aggregation
MS Authors: Mishra, Purva ; Potlia, Rajesh; Sandhu, Kuljeet
Contact Author: Dr Kuljeet Sandhu
Contact Author Email: [sandhuks@iisermohali.ac.in](mailto:sandhuks@iisermohali.ac.in), [kulsinsan@gmail.com](mailto:kulsinsan@gmail.com)
Keywords:
EndDryadContent

**Comment by ryscher** [comment]
Yes, that email was processed correctly.
