### ISSUE TITLE
High priority- error message occurs when clicking "Proceed to README" button from Upload files tab in submission system

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3644]
**Bug description:**
I've had two authors (and Kailasha noted a third case) where they clicked on the "Proceed to README" button at the bottom of the Upload files tab in the submission system and were presented with an error message.
<img width="650" alt="image001" src="https://github.com/user-attachments/assets/98254a87-ae26-4791-b5f1-b07b8e6998df">

**Steps to reproduce:**
I entered the dataset and also encountered the error. Note that this does not happen for all datasets, and if you go straight to the README tab, it bypasses the error message.

Example cases:
doi: 10.5061/dryad.stqjq2cbx
Resource ID: 316273

doi: 10.5061/dryad.zgmsbcck4
Resource ID: 315974

**Comment by lauradryad** [comment]
And another: 10.5061/dryad.wh70rxwxb Resource ID: 316049

**Comment by ahamelers** [comment]
This should be fixed now, sorry for the delay. I made a PR for this but did not merge and deploy it immediately as I didn't know how urgent it was
