### ISSUE TITLE
Add Tenant: SUNY ESF

### ISSUE THREAD

**Issue by sarahklippincott** [datadryad/dryad-product-roadmap#3646]
**Tenant name:** SUNY College of Environmental Science and Forestry (ESF)

**Logo location:** https://experts.esf.edu/rep/esploro/lightLogo?institution=01SUNY_ESF

**Contacts to receive submission notices:** 

**RORs that are considered part of the tenant (including medical centers, alternate campuses, etc.)** https://ror.org/00qv0tw17

**Shibboleth info, if not in [InCommon](https://incommon.org/community-organizations/):** 
IP Range
132.174.255.148
149.119.7.0/24
104.167.160.0/24

Technical contact: dmoore@esf.edu

**Membership model:** Part of SUNY consortial membership

Tasks:
- [x] add new tenant and logo to database on stage and production
- [ ] test on stage (institution should log in to verify working as expected)
- [x] update `tenant_id` for users in the database who have emails with the institutional domain name

**Comment by ahamelers** [comment]
This is done

**Comment by sarahklippincott** [comment]
@ahamelers this tenant has specific branding preferences concerning their name. Is it possible to have the full tenant name ("SUNY College of Environmental Science and Forestry") in the dropdown rather than "SUNY ESF"?

**Comment by sarahklippincott** [comment]
@ahamelers Thanks! Yes, it would be great if admins could make name changes.
