### ISSUE TITLE
Clean up migrated users

### ISSUE THREAD

**Issue by ahamelers** [datadryad/dryad-product-roadmap#3647]
There are 2040 users with `-migrated` in their emails and ORCIDs. Many are duplicates of real users. Only 1 of these migrated users seems to have any resources associated with them.

1. Can the remaining 2039 be deleted?
2. Can the 1 migrated user with a submission be converted into a normal user?

**Comment by ryscher** [comment]
Yes, we can remove them. These are left over from the transition to v2, when we needed to match old accounts that only had an email with new accounts that had an ORCID. By now, the "migrated" accounts are no longer useful.
