### ISSUE TITLE
Clean old tenant views

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3651]
I believe the files in `app/views/tenants` have not been used since we introduced the v2 system in 2019. Confirm that they are not used anywhere, and delete them.

**Comment by ahamelers** [comment]
It looks like, on the review screen, we are in fact showing data deposit agreements for.... a grand total of 2 tenants (UCD and UCSB)

```ruby
<% if current_tenant.data_deposit_agreement? %>
    <p>
      <span><%= check_box_tag 'agree_to_dda', 'yes', false, class: 't-review__agree-to-license js-agrees' %></span>
      <label for="agree_to_dda">
        By checking this box, I agree to the
        <%= link_to 'Data Deposit Agreement', stash_url_helpers.dda_path, target: '_blank' %>
      </label>
    </p>
  <% end %>
```

I had no idea this was happening! Is this a requirement? Should we add these two (2) DDAs to the new submission system?

**Comment by ryscher** [comment]
The Data Deposit Agreement is no longer needed. Please remove.
