### ISSUE TITLE
Please put published dataset back into PPR

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3654]
This dataset was published too soon. It looks like the system withdrew it, and then the author resubmitted their manuscript and updated their dataset, which put it into "submitted" status. Because it was a pub-as-is case, it was published without contacting the author.

Can you also provide some clarity (for me) on whether PPR can be selected after the system auto-withdraws it (i.e., did the author just miss the button the second time around), and if not, why?

Resource ID: 316790
DOI: 10.5061/dryad.pnvx0k6v0
Activity log: https://datadryad.org/stash/ds_admin/115661/activity_log

**Comment by ahamelers** [comment]
> Can you also provide some clarity (for me) on whether PPR can be selected after the system auto-withdraws it (i.e., did the author just miss the button the second time around), and if not, why?

We think not, because of withdrawal being a special status, but I'm not 100% sure. For further clarification please add this to a curator meeting
