### ISSUE TITLE
Install software in virtual environment (VE)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3656]
We've got a large (10GB) submission with EEG files. Please install relevant software for viewing these in the VE.

Author has suggested Brainstorm and EEGLAB (https://sccn.ucsd.edu/eeglab/download.php) -- our house document suggests Neuroscope (https://neurosuite.sourceforge.net/).

**Comment by ryscher** [comment]
Neuroscope is installed and appears to be working
