### ISSUE TITLE
'Generate new README' directing to a blank page

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3657]
When the option to 'Generate new README' is selected I'm directed to a blank page. I've tested this on a few new submissions and get the same result. I'm selecting the link to generate a new one even when there's an existing one. 

![Screenshot 2024-09-19 at 1 59 03 PM](https://github.com/user-attachments/assets/5d7014b6-fb9c-4509-9734-f9d125b1cfea)

![Screenshot 2024-09-19 at 9 48 42 AM](https://github.com/user-attachments/assets/88788a61-6ad6-4e2f-9df1-73446556989f)

**Comment by ahamelers** [comment]
@jleighherzog I can't recreate this on sandbox or production. Could you maybe delete your javascript cache and try again?

**Comment by ahamelers** [comment]
@jleighherzog any update on this?

**Comment by jleighherzog** [comment]
@ahamelers : I haven't come across this issue since I posted. Will close.
