### ISSUE TITLE
Sponsorship confirmation not available on final page of submission form

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3658]
For datasets sponsored by a journal or institution, the confirmation of payment on the final page of the Dryad submission form is missing. It used to display a line of text but it's missing from recent submissions. 

In the Activity Log, the internal data section appropriately displays the sponsorship but the final page of the form doesn't have the confirmation as it did before. 

Example:
_Evolution_ is a sponsoring journal
10.5061/dryad.f1vhhmh5h
https://datadryad.org/stash/ds_admin/140842/activity_log

![Screenshot 2024-09-19 at 2 44 29 PM](https://github.com/user-attachments/assets/7d1dc456-3e18-48bf-a54e-fc9b6487cc81)

**Comment by ahamelers** [comment]
@jleighherzog It looks like the payment section, which contains this information, is hidden once a definite payment type is recorded (so once an institution or journal is covering the DPC, or the invoice is sent via stripe). Presumably to prevent this from being fiddled with after, or indicating after publication that people have to pay a second time.

This is probably not the most elegant solution and I can alter it slightly (to still show the payment details, without offering any tenant change options) for now. This may still confuse post-publication submitters (and we have another ticket for that, #2298). We can review it in a more detailed way as part of the submission system redesign.
