### ISSUE TITLE
"Very urgent" request to remove previous version of published dataset

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3661]
An author accidentally chose the wrong dataset to publish, and would like us to remove it as soon as possible. Since the correct dataset has yet to be uploaded, it might be best to 1) remove the first version, and 2) put the dataset into PPR.

DOI: 10.5061/dryad.j0zpc86pv
most recent Resource ID: 317587

**Comment by ryscher** [comment]
I set this to `withdrawn` status. The file size is negligible. It sounds like the author may possibly want to reinstate this datasert when another publication is created.
