### ISSUE TITLE
Delay in processing Curator-edited submissions, unable to set status

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3662]
Curators have reported that it takes a long time (several minutes) for datasets that have been edited by Curators to return to 'Curation' status after their changes are submitted (sometimes metadata-only edits).  Several minutes, at least. 

The message below appears while changing the status from 'Submitted' to 'Curation' status
![Screenshot 2024-09-23 at 1 20 20 PM](https://github.com/user-attachments/assets/dd927a48-d7a7-453e-96be-5cfdf6450e7a)

**Comment by ryscher** [comment]
Is this fixed now?

**Comment by ahamelers** [comment]
I believe the delay/queue problems are a separate issue from #3708

**Comment by ahamelers** [comment]
@jleighherzog Is this fixed now?

**Comment by jleighherzog** [comment]
Yep, I believe so.
