### ISSUE TITLE
PubUpdater billing

### ISSUE THREAD

**Issue by jeremywalter** [datadryad/dryad-product-roadmap#3664]
**Bug description:** When PubUpdater updates a submission with a different Journal, Payment info is not updated.

**Steps to reproduce:** 10.5061/dryad.ngf1vhj1d -- PubUpdater updated Primary Article, but Payment ID did not change from the original (wrong) Journal association

**Expected behavior:** Payment info will update along with other Journal metadata when Primary article update requires a change in Journal.

**Comment by ahamelers** [comment]
I've added a change for this and will fix the affected submission as well
