### ISSUE TITLE
Dataset will not change from curation to published status- remains stuck in curation

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3667]
When attempting to publish [this particular](https://datadryad.org/stash/dataset/doi:10.5061/dryad.f1vhhmh4k) dataset, nothing happens. This was brought to me by Kathi, and I also tried to publish the dataset, without success. When clicking "publish" nothing happens and the dataset remains in "curation" status, whereas usually the dataset is published as soon as we click that button. I have since published other datasets successfully.

DOI: 10.5061/dryad.f1vhhmh4k
Resource ID: 317758

**Comment by ahamelers** [comment]
Looks like there's something weird in the database for this one, around its current stata

```
A NoMethodError occurred in admin_dashboard#update:

  undefined method `current_resource_state' for nil
  app/controllers/stash_engine/admin_dashboard_controller.rb:376:in `publishing_error'
```

I'll look into it and let you know when it's normal

**Comment by ahamelers** [comment]
I have left the user-edited version, 317759, as the latest, in order to not lose any of their changes, and changed the version numbers to reflect this. It may need re-curation (for the same, or other, curator edits as were made to the other confusingly out of order versions)
