### ISSUE TITLE
"Authors in" report for Cornell

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3673]
Send to Maria

**Comment by ryscher** [comment]
Created report and shared with Maria.

**Comment by mariaguerreiro** [comment]
@ryscher Please could you re-run the report to ensure it features the “Payment type” and “Sponsor” columns?
Your previous spreadsheet is here: https://docs.google.com/spreadsheets/d/161t0GveeDl8wmRA9mPiy6Zh-cN3TdkRVdh_78zuIvvw/edit?gid=0#gid=0

Many thanks!

**Comment by ryscher** [comment]
The previous spreadsheet is now updated with the requested fields.
