### ISSUE TITLE
Return to PPR status [priority]

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3676]
[Heterogeneity of locked-pasture snow conditions modulate habitat and movement choices of a facultative migrant](https://datadryad.org/stash/dataset/doi:10.5061/dryad.bnzs7h4jm)
DOI: 10.5061/dryad.bnzs7h4jm

Dataset was published today, PPR not selected, journal requires double-blind review process

**Comment by ryscher** [comment]
Unpublished and forced back to PPR.
