### ISSUE TITLE
Unable to download files via Reviewer URL (10.5061/dryad.gxd2547w7)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3700]
Unable to download this dataset via Reviewer URL: http://datadryad.org/stash/share/m0ROJ3qAP8jzX0mdk30hN_dLkWl9wJrK25LOl87x7Ns

Error message pops up.

**Comment by lauradryad** [comment]
I think I may have encountered another instance of this: 10.5061/dryad.vhhmgqnzt

I get this: 
![image](https://github.com/user-attachments/assets/b98d5f93-1f6d-4db6-98d4-3e38549ded08)
And when I try the files individually, it goes back to that little text warning that "You may not download this file."

**Comment by ahamelers** [comment]
@lauradryad the second thing is a true/false issue (please make new tickets for these, or list them in #3615 )

The reviewer stuff not working is a separate error

**Comment by ahamelers** [comment]
A fix for this has been deployed
