### ISSUE TITLE
BUG: display of previous version files

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3701]
Landing pages no longer display data files from previous versions; only the most recent version is shown.

For example, https://sandbox.datadryad.org/stash/dataset/doi:10.7959/dryad.69p8cz8xg has 3 published versions, 2 of which have different files. These two versions are returned correctly in Rails console using `StashEngine::Identifier.find(31059).resources.files_published`, but for some reason, they are not being displayed on the page.

**Comment by ahamelers** [comment]
A fix for this has been deployed
