### ISSUE TITLE
System deleting manuscript numbers when authors link article DOIs in versioned datasets

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3704]
The system appears to be deleting manuscript numbers when authors are prompted to add their article DOIs six months after their dataset is published. This makes the versioned dataset come back to curators, but nothing has changed other than the deletion of the manuscript number and the addition of the primary article DOI. The expected behavior is that when an author links their primary article DOI, the manuscript number is retained and the dataset is automatically republished without needing to be looked at by a curator.

We have not been adding manuscript numbers back. We just re-publish as-is. This has been happening for at least one week, maybe two.

**Comment by mahirst** [comment]
Seems to still be happening:
DOI: 10.5061/dryad.q83bk3jqv
Resource ID: 321404

**Comment by ahamelers** [comment]
@mahirst this isn't deployed yet

**Comment by ahamelers** [comment]
@mahirst (it's deployed now)
