### ISSUE TITLE
PRIORITY: 10.25349/D9402J

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3712]
Several published versions of this submission contain data that can potentially be re-identifying. 

The current version, published on **October 4, 2024** has been updated and published with de-identified data (this version is _the only_ version that should remain published and publicly available). 

Will the original publication date remain or be removed?

**Comment by ahamelers** [comment]
> Will the original publication date remain or be removed?

We keep all the published file versions and just mark them as not viewable. Whether the publication dates are displayed can be a separate question, but we generally keep them. Is there a preference in this case?
