### ISSUE TITLE
Rename file in existing submission

### ISSUE THREAD

**Issue by jeremywalter** [datadryad/dryad-product-roadmap#3717]
DOI: 10.5061/dryad.j3tx95xpw
Resource ID: 320889

Submission has bad characters in the folder name. Currently named:

└───A_possible_archaic_precursor_of_the_octocoral_structural_plan_from_the_Estonian_Ordovician
    └───ì«óá∩ »á»¬á

Can we make the file one folder "Ordovician octocoral precursor" with all the existing files?

**Comment by ahamelers** [comment]
@jeremywalter Renaming files is easy enough for us to do in place, but if you are asking us to rename a folder within a compressed (zip) file, I am afraid that is no more easy for dev to do than for you. It would require

1. downloading the file
2. opening it
3. renaming the folder
4. compressing everything again
5. reuploading it

Can you clarify what you're asking here?

**Comment by jeremywalter** [comment]
@ahamelers it is indeed the renaming of the folder (as shown above) - I went ahead and pulled and re-uploaded it through the VE and am awaiting approval by the author... thank you for steering me in the right direction ;) (or at least inspiring a fix I could manage myself).
