### ISSUE TITLE
Remove 10.5061/dryad.7pvmcvf3f 

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3720]
This dataset should be entirely deleted, metadata and all, please. Latest resource ID is 322109

**Comment by lauradryad** [comment]
Yes, you can withdraw it

**Comment by ahamelers** [comment]
@ryscher Does this need a tombstone page?

**Comment by jleighherzog** [comment]
Collecting feedback on the COPE guidelines I've been working on. Should have an update early next week. Iratxe is reviewing.

**Comment by ryscher** [comment]
Closing; we can always add a tombstone if needed later.
