### ISSUE TITLE
Old dataset submitted by Ryan needs to change corresponding author

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3722]
This dataset was submitted and published by Ryan/Admin system, but the author has contacted us to become an editing author to update the files post-publication. 

activity log: https://datadryad.org/stash/ds_admin/131/activity_log
doi: 10.5061/dryad.1nt24m0
resource ID: 131

Here is the corresponding author information:
Name: Manoj Srinivasan
email: srinivasan.88@osu.edu
ORCID: 0000-0002-7811-3617

**Comment by ahamelers** [comment]
Okay, done!
