### ISSUE TITLE
stage-1 problems

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3732]
Server is responding very slowly.

**Comment by ryscher** [comment]
Prolblems still exist; we will need to rebuild the server.

Build a new server, following the [AWS EC2 instructions](https://github.com/datadryad/dryad-app/blob/main/documentation/external_services/amazon_aws_ec2_setup.md)

**Comment by alinvetian** [comment]
The server is created but stopped since we fixed the current stage-1 server
