### ISSUE TITLE
Add Tenant: Georgetown University

### ISSUE THREAD

**Issue by sarahklippincott** [datadryad/dryad-product-roadmap#3740]
**Tenant name:** Georgetown University																									

**Logo location:** https://drive.google.com/file/d/11k7lRNjvfigpOgSzJCLp9-4aBh6xu4dH/view?usp=sharing

**Contacts to receive submission notices:** Abigail Scheetz as5050@georgetown.edu https://orcid.org/0009-0003-3646-6902

**RORs that are considered part of the tenant (including medical centers, alternate campuses, etc.)** https://ror.org/05vzafd60; https://ror.org/03ja1ak26; https://ror.org/029e47x73; https://ror.org/035zrb927; https://ror.org/00hjz7x27; https://ror.org/02fz54z33

**Shibboleth info, if not in [InCommon](https://incommon.org/community-organizations/):** InCommon Member

**Membership model:** Normal

Tasks:
- [x] add new tenant and logo to database on stage and production
- [ ] test on stage (institution should log in to verify working as expected)
- [x] update `tenant_id` for users in the database who have emails with the institutional domain name

**Comment by ahamelers** [comment]
@sarahklippincott 

>Membership model: Normal

Does this mean not tiered?
