### ISSUE TITLE
Assign old dataset (10.5061/dryad.g68d124) to current ORCID

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3750]
There is a dataset from 2019 that appears to be imported from the old system (resource ID 34207) and the author now needs access to finalize it, but it's not attached to his ORCID. 

His ORCID is 0000-0002-1487-3254 and he has logged in to the system.

**Comment by ahamelers** [comment]
There were 3 entries for this user. I've merged them all and corrected the ORCID for the final user. He should see all his datasets listed now
