### ISSUE TITLE
Update to Help page section: Preferred file formats

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3754]
Please add the following paragraph to the [Preferred file formats](https://datadryad.org/stash/requirements#:~:text=the%20Dryad%20DOI.-,Preferred%20file%20formats,-Most%20types%20of) section of our Help page: 

Note: RAR (Roshal ARchive) is a proprietary compression format. Because users may not have access to the necessary tools to open RAR files we cannot accept them for publication. For open data submissions, it’s best to use open, widely supported, and easily accessible formats like those listed above.

> Preferred file formats
> 
> Most types of files can be submitted (e.g., text, spreadsheets, video, photographs, code) including compressed archives of multiple files. Dryad welcomes the submission of data in multiple formats to enable various reuse scenarios. For instance, Dryad's preferred format for tabular data is CSV, however, an Excel spreadsheet may optimize reuse in some cases. Thus, Dryad accepts more than just the preservation-friendly formats listed below.

- Text:
> - README files should be in Markdown (MD)
> - Comma-separated values (CSV) for tabular data
> - Semi-structured plain text formats for non-tabular data (e.g., protein sequences)
> - Structured plain text (XML, JSON)
> - Images: PDF, JPEG, PNG, TIFF, SVG
> - Audio: FLAC, AIFF, WAV, MP3, OGG
> - Video: AVI, MPEG, MP4
> - Compressed file archive: TAR.GZ, 7Z, ZIP
> Note: RAR (Roshal ARchive) is a proprietary compression format. Because users may not have access to the necessary tools to open RAR files we cannot accept them for publication. For open data submissions, it’s best to use open, widely supported, and easily accessible formats like those listed above.

**Comment by ahamelers** [comment]
@jleighherzog Good?

<img width="831" alt="Screenshot 2024-11-07 at 15 45 51" src="https://github.com/user-attachments/assets/2cc5e021-6557-4e88-943b-4639e83cf10f">

**Comment by ahamelers** [comment]
Some text changes:
<img width="847" alt="Screenshot 2024-11-07 at 15 47 28" src="https://github.com/user-attachments/assets/e091d7f0-b52f-461d-8fbd-122911558ea9">

**Comment by jleighherzog** [comment]
Looks great, thanks @ahamelers

**Comment by jleighherzog** [comment]
Ryan fixed the typo above.
