### ISSUE TITLE
Server slowness

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3755]
Production servers are slow. The problem seems intermittent, and not confied to any one server.

**Comment by ryscher** [comment]
Testing the hypothesis that certain types of activities cause a slowdown. Page types:
- [Static](http://localhost:3000/stash/mission) -- basically instant
- [Journal](http://localhost:3000/stash/journals) -- typically takes 4 seconds, but up to 30 when the server is slow
- Landing
- Dashboard
- Admin page
- Submission

**Comment by ahamelers** [comment]
Possibly loading the new roles is slowing down the admin dashboard—I can see if there are ways to speed this up

**Comment by ahamelers** [comment]
@ryscher I can deploy this https://github.com/datadryad/dryad-app/pull/1918 and we can see if it's any faster! It definitely won't hurt

**Comment by ahamelers** [comment]
Another slowing factor is probably still the curation stats—they are still recalculating (although this time I set it to only calculate the blank 'unclaimed' value, rather than do a full recalc of everything, it's still a lot of querying for that 1 value)

**Comment by ahamelers** [comment]
> @ryscher I can deploy this [datadryad/dryad-app#1918](https://github.com/datadryad/dryad-app/pull/1918) and we can see if it's any faster! It definitely won't hurt

I did this, and it IS faster I think

**Comment by ryscher** [comment]
Slowness still happening, along with other problems. Declared an [incident](https://docs.google.com/document/d/1-BKrrovJlV8dV6Tm6ovDHOC39odooJBGMs3paRhVR2I/edit?usp=sharing).

**Comment by ryscher** [comment]
Appears the problem was a runaway process on the production DB. Restarting the DB fixed it.
