### ISSUE TITLE
Linking old datasets with ORCID

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3756]
With the auto-emails going out, we are receiving a lot of emails about auto-withdrawn datasets. For datasets older than 2019, they are not linked to the submitting author's ORCID, so we are listing on this ticket the datasets and ORCIDs that need to be linked so the author can edit the datasets:

- [x] John Carlos Garza: 0000-0002-7325-6803
Datasets: 10.5061/dryad.574sv, 10.5061/dryad.76k4j

Will continue to add below

**Comment by ahamelers** [comment]
@lauradryad if you add new ones with a checkbox, I can check them off as I complete these

**Comment by ahamelers** [comment]
@lauradryad That first one actually did have a user account, just with no ORCID connection. I merged the users and he should have access to 7 datasets now

**Comment by mahirst** [comment]
- [ ] Heather Lynch: [0000-0002-9026-1612](https://orcid.org/0000-0002-9026-1612)
DOI: 10.5061/dryad.n14f14g (Resource ID: 36126)

**Comment by ahamelers** [comment]
Please double check with these if they can be resolved by merging users, since you have that power as well and it's actually all I've done so far!
<img width="676" alt="Screenshot 2024-11-11 at 8 59 23 AM" src="https://github.com/user-attachments/assets/0395faea-5850-4884-a8ed-813fbf845b33">
