### ISSUE TITLE
Dataset stuck in processing

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3758]
An author contacted the help desk about their dataset being stuck in processing status since submitting it yesterday. I tried to forcibly edit the dataset and cancel the changes, but it is still stuck in processing. Pulling it out of this status so the author can access and edit it in PPR would be great. :)

DOI: 10.5061/dryad.w6m905qx3
Resource ID: 326508

**Comment by ryscher** [comment]
All datasets were stuck. Paused submisssions, reset everything. Most datasets went through. However, some still stuck. 

Stuck datasets had a `user_id=115943`, which is a former curator. When I manually changed them to an active curator, they went through. There was an error message of:
```
Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`dryad`.`stash_engine_saved_searches`, CONSTRAINT `fk_rails_18d7700465` FOREIGN KEY (`user_id`) REFERENCES `stash_engine_users` (`id`))
```

**Comment by ahamelers** [comment]
@ryscher What exactly were you doing when you got that error?

**Comment by ryscher** [comment]
In Rails console, I was resubmitting it with `StashEngine.repository.submit(resource_id: res_id)`. Though I don't think the error appeared in the immediate results. It is more likely it appeared when I was manually running these steps from the status updater:
```

r=StashEngine::RepoQueueState.find(<id_num>)
r.possibly_set_as_completed
```
