### ISSUE TITLE
Research domain dropdown

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3759]
Research domain dropdown does not work
- Results in new datasets not being able to be submitted
- Datasets unable to be submitted

**Comment by ryscher** [comment]
This appears to be caused by non-FOS entries that are present in the field. Why are we allowing non-FOS entries?

Workaround: If you select the contents of the field and delete them, then clicking on the field again will bring up the selection list.

A subtle issue is related to the browser: 
- Safari: Works fine
- Firefox: User must click on the box twice, but then it works
- Chrome: Works fine

**Comment by ahamelers** [comment]
This appears to be a problem with the HTML datalist between different browsers: https://stackoverflow.com/questions/75946314/html-input-datalist-not-allowing-a-reselect-of-option

In the submission redesign we have removed this and we are using a more standard search-and-select component.

Doing that in the existing system requires a lot of edits throughout the code, so in the meantime I will just change the production system code to use a standard select element (without typing to search).
