### ISSUE TITLE
Dataset 10.5061/dryad.r7sqv9sm6 has a version issue

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3763]
When either the author or I try to edit this dataset, it opens the previous version 3 instead of the latest version 4. When the author attempts to go back in, the activity log isn't even recording it. It does show that I have gone in and deleted the version twice. 

The version that should be the most recent is 326977 but we keep going in to 307411 and I'm not sure how to fix it.

**Comment by lauradryad** [comment]
It happened to this dataset as well just now 10.5061/dryad.47d7wm3f4

It's ready to publish, but I'm not really sure what version will publish if I update it. The author resubmitted it after it was withdrawn, and then I had to make some edits to it before I publish, but then it got messed up.

**Comment by ahamelers** [comment]
@lauradryad for the one in the ticket it should now be version 5 (327528). I really do not know why 307411 reopened, it's very weird.

**Comment by ahamelers** [comment]
The second one has 2 version 7s and that is the source of its problem.
<img width="608" alt="Screenshot 2024-11-11 at 1 06 30 PM" src="https://github.com/user-attachments/assets/0a818ada-7392-4fc6-a92e-b58b0edfa2e1">

Which SHOULD be the latest version? I can change the version # for it to 8.

**Comment by ahamelers** [comment]
@lauradryad I made 326893 the latest version (version 8), since I think you need to look at it to see any changes that may have been made by the submitter. You may need to create a version 9 to reincorporate changes you'd made in 326892 (version 7).
