### ISSUE TITLE
New dummy curator accounts for assigning datasets

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3769]
Instead of using existing people's accounts as dumping grounds, we would like new dummy curator accounts:

**ReinstateQueue**: this one will replace what are currently assigned to Audrey. Resubmitted datasets which were previously curated by someone who no longer works here should be automatically assigned to this one (this is to catch a lot of reinstated ones).

**TempQueue**: This will replace what is currently assigned to Alin, and will be the datasets we have chosen for triage  

I believe Audrey said she needed a Curator one for the API.

**Comment by ahamelers** [comment]
> Resubmitted datasets which were previously curated by someone who no longer works here should be automatically assigned to this one

Is this meant to be a permanent feature or something for this period of time only?

**Comment by lauradryad** [comment]
Temporary! Can we edit the "name" of this account later or should we just make it something more general for right now?

**Comment by ahamelers** [comment]
We can edit it whenever

**Comment by ahamelers** [comment]
Looks like we already had a mysterious other account like this. Someone probably did something like this previously
<img width="1225" alt="Screenshot 2024-11-11 at 2 39 35 PM" src="https://github.com/user-attachments/assets/22434662-8f65-4fc2-8a00-5e4c98f2723e">

**Comment by lauradryad** [comment]
Can you bulk reassign what is already in Alin's and your queue to those?

**Comment by ahamelers** [comment]
> > Resubmitted datasets which were previously curated by someone who no longer works here should be automatically assigned to this one

> Is this meant to be a permanent feature or something for this period of time only?

I've automatically set everything that was "withdrawn" to come back to the 'Reinstate Queue' account if it's resubmitted. Is it okay for you to have to reassign things coming from AAR to this?
