### ISSUE TITLE
Push metadata changes to Zenodo for 10.5061/dryad.g1jwstr0h

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3775]
The author of this dataset updated the Abstract and Methods to correct some errors, but noted that those changes did not go to the Zenodo instances (which I think is always the case for us when no files change). Please push these changes over to Zenodo.

**Comment by kathiyayinijk** [comment]
DOI: 10.5061/dryad.x95x69ptg for this dataset also, metadata changes are not reflected on Zenodo

**Comment by ahamelers** [comment]
Both of these changes were made on zenodo, and just needed to be published—they were, basically, saved as a draft. I do not know why the final 'publish' step is not being made and will bring this up in our next dev meeting, as it seems like it should be an easy thing to add!
