### ISSUE TITLE
Extra text in files uploaded by API

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3783]
From ACS:

While testing in the Sandbox recently, we noticed that files uploaded via [https://sandbox.datadryad.org/api/v2/datasets/{doi}/files/{filename}](https://sandbox.datadryad.org/api/v2/datasets/%7bdoi%7d/files/%7bfilename%7d) had unnecessary metadata included in the file content. This is causing poor formatting in text based files upon download and is causing other file types (XLSX and multiple different image types for example) to be corrupted entirely upon download. We verified that this is happening outside of our system by making a call directly to the Dryad API with Postman. The cURL for that request is below, and the “Before” and “After”  for the related README file are attached.
 
```
cURL:
curl --location 'https://sandbox.datadryad.org/api/v2/datasets/doi%3A10.7959%2Fdryad.2280gb5n9/files/readme.md' \
--header 'Authorization: Bearer <token>' \
--header 'Cookie: AWSALB=TwgflfJfFOI6nRpS2E5CWOtQpr+xS6cPnv3Udf54MNdy8gwYVPZV7wCADLgLCuZKT85l19P1jMXTQOfn7YA4maVtj8Y/j9jvVcNHDiD2qqQF0BRpBmAtjWD7TUuG; AWSALBCORS=TwgflfJfFOI6nRpS2E5CWOtQpr+xS6cPnv3Udf54MNdy8gwYVPZV7wCADLgLCuZKT85l19P1jMXTQOfn7YA4maVtj8Y/j9jvVcNHDiD2qqQF0BRpBmAtjWD7TUuG; AWSALBTG=nMVKoUIiO0a++6WGt8+O9Nnt5OpQKYVpJFM6aEyLSDdBVIPrUbjxKXfYN9M8MO7HtD6+9221IbCgexVpBQA7X7MCLzDSNPmthORuIKrRjuWNQ212/kzEho/B9SymWlFwISP5Fmg6rJA6KY3yHN9XgBZno+4eVP86mz1hLMCH/muSUo8TQTg=; AWSALBTGCORS=nMVKoUIiO0a++6WGt8+O9Nnt5OpQKYVpJFM6aEyLSDdBVIPrUbjxKXfYN9M8MO7HtD6+9221IbCgexVpBQA7X7MCLzDSNPmthORuIKrRjuWNQ212/kzEho/B9SymWlFwISP5Fmg6rJA6KY3yHN9XgBZno+4eVP86mz1hLMCH/muSUo8TQTg=; AWSALB=4bbHOr9eAIJbd0gHanqNwm5JhzuP124uqubKJSzsnP7k/3vxOWaTC/oWWbr8A/qNyYx/wKJ35lA0VUeroqwTAxVDpmhI7wWvnyyco57DtljNf5snBE2fSIerbmMV; AWSALBCORS=4bbHOr9eAIJbd0gHanqNwm5JhzuP124uqubKJSzsnP7k/3vxOWaTC/oWWbr8A/qNyYx/wKJ35lA0VUeroqwTAxVDpmhI7wWvnyyco57DtljNf5snBE2fSIerbmMV; AWSALBTG=EP6cVN2dGntYsVNxUHcvpyh6CheYJZQ4pI3C6F2iAC5UWI5BLqBOnD0B7dRa0dgTjiEv4ZMp4xF4ZmR9QQkdNPm6zSqauhnQFgUYtB+zwYtnWHbRNasnhO7uv7zPktSHT2+aauiLmbvuvp9C1/19YPJLQkTkIa0IA4cZZKjncSB3gg6Ktlc=; AWSALBTGCORS=EP6cVN2dGntYsVNxUHcvpyh6CheYJZQ4pI3C6F2iAC5UWI5BLqBOnD0B7dRa0dgTjiEv4ZMp4xF4ZmR9QQkdNPm6zSqauhnQFgUYtB+zwYtnWHbRNasnhO7uv7zPktSHT2+aauiLmbvuvp9C1/19YPJLQkTkIa0IA4cZZKjncSB3gg6Ktlc=' \
--form '=@"/C:/Users/00480/Downloads/README.md"'
```

**Comment by ryscher** [comment]
[README - Sent to Dryad (Before).md](https://github.com/user-attachments/files/17804953/README.-.Sent.to.Dryad.Before.md)
[README - Stored on Dryad (After).md](https://github.com/user-attachments/files/17804954/README.-.Stored.on.Dryad.After.md)

**Comment by ryscher** [comment]
Verify whether the behavior is correct when using CURL with this format:

```
curl --data "@/tmp/sample_dataset.json" -i -X POST https://sandbox.datadryad.org/api/v2/datasets -H "Authorization: Bea\
rer JPb03FUOF4vqIKWbDyESO6L09wR4p07SY6gPZb8CNlo" -H "Content-Type: application/json"
```

**Comment by alinvetian** [comment]
I just verified, and sending the file using
```
--data-binary '@/path/to/file.md'
```
OR 
```
--data-binary '@/path/to/file.md'
```

works as expected

**Comment by ryscher** [comment]
I sent ACS a description of the solution and a link to the documentation.
