### ISSUE TITLE
Onboarding Jairo Melo-Florez (UCSB)

### ISSUE THREAD

**Issue by rcurty** [datadryad/dryad-product-roadmap#3794]
**Full name:** Jairo  Melo-Florez (UCSB)

**Position:** DH Research Facilitator

**Personal email address:** jmeloflorez@ucsb.edu 

**ORCID:** (if available) https://orcid.org/0000-0002-2020-1163

Please complete the [onboarding tasks](https://docs.google.com/document/d/1xj27OsuMgWbuaeWqXkgsAWOBiSx9L-8uNbfpVmzbd5o/) for this new staff member.

**Comment by jleighherzog** [comment]
I'll close this ticket and will create a new one when training is complete.
