### ISSUE TITLE
Dataset landing page won't open- 10.5061/dryad.q573n5tsp

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3795]
We cannot see the landing page of this dataset, but you can see the Activity Log. It was created and submitted on the fateful day on Nov 8, so I'm guessing some permissions got muddled for this one. Resource ID 327236

**Comment by ryscher** [comment]
Fixed. 

The resource_state was stuck in 'error' status, so I forced it to 'submitted'
