### ISSUE TITLE
Edit sponsorship of dataset resource ID 330094

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3797]
This dataset should have been sponsored by Desert Research Institute. I manually added this affiliation to the user's account, but it didn't reflect on the payment information yet. I'm about to publish this and don't want them to receive an invoice. 10.5061/dryad.0zpc8676t

Let me know if there's a way I can do this myself without making a ticket!

**Comment by ryscher** [comment]
Updated.

No, curators cannot currently make this type of change.
