### ISSUE TITLE
Transfer ownership of 10.5061/dryad.612jm64b8

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3799]
Please transfer the ownership of this dataset to Shou-Li Li from Hai-Tao Miao.

Current ORCID: 0000-0002-6703-0285
New ORCID owner: 0000-0001-8536-8194 (who does have a Dryad account already and is one of the current co-authors).

Resource ID 330098

**Comment by ahamelers** [comment]
Done
