### ISSUE TITLE
High priority. Please replace some text in the HSI PDF document

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3802]
In the table in this document https://datadryad.org/docs/HumanSubjectsData.pdf

Please update the table text under 'Direct identifiers (none allowed)' such that 

"Facial photograph or comparable image such as fMRI data showing facial structures"

is changed to 

"Facial photographs or comparable images such as fMRI scans showing facial or cranial structures, including any resulting data from those scans"

Will discuss why this is high priority in our meeting soon.

**Comment by jleighherzog** [comment]
Checking the links in this PDF while we're at it. This one is broken: 

Olesen S, Australian National Data Service (2014) ANDS Guide to Publishing and sharing sensitive data.
Australian National Data Service. Retrieved February 01, 2017 from http://ands.org.au/guides/sensitivedata.pdf

New link: https://apo.org.au/node/41413

**Comment by mahirst** [comment]
On Page 5 under **Tools**, Amnesia: Used to remove and transform identifiers in a dataset: https://www.openaire.eu/item/amnesia

link should be https://amnesia.openaire.eu/

On page 5 under **Resources**: Direct and Indirect Identifiers: https://uwaterloo.ca/research/sites/ca.research/files/uploads/files/direct_and_indirect_identifiers_access_check_do ne_0.pdf

link should be https://uwaterloo.ca/research/sites/default/files/uploads/documents/direct_and_indirect_identifiers_access_check_done_0.pdf

Checked all other links, and they work for me.

**Comment by ahamelers** [comment]
If I'm not mistaken, normally the curators update this and give us a new copy to upload to the site.

**Comment by ryscher** [comment]
Document is updated.

**Comment by mahirst** [comment]
Hi! The wrong version of this was updated recently. Please update this document to this version, as soon as possible. Thank you!
https://docs.google.com/document/d/1bBwFn8kHbsUtj9PmyeieEdyyi7fcOj0bkr_B5_-zIKo/edit?tab=t.0

**Comment by ahamelers** [comment]
We updated this according to this ticket: https://github.com/datadryad/dryad-product-roadmap/issues/3829
