### ISSUE TITLE
Whitelist ScholarOne emails

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#3805]
Molecular Oncology notified us that their emails are being marked as spam. Unclear whether other journals are affected.
![Image](https://github.com/user-attachments/assets/36ea2d9e-7ae6-4a1f-871c-f1099b804a6c)

**Comment by ryscher** [comment]
I have updated some settings to make our system more likely to accept these messages. However, I do not see any messages that have been blocked, so they may have been blocked by a ScholarOne system before getting to us. 

Please advise ScholarOne that if messages are not going through, they could avoid these problems by completing an API integration with Dryad.

**Comment by mariaguerreiro** [comment]
Noted, thanks!

**Comment by mariaguerreiro** [comment]
From FEBS: Thank you for updating the settings, we think it worked. If it happens again we will try contacting ScholarOne.

**Comment by ryscher** [comment]
Reinstating, due to an updated request.

**Comment by ryscher** [comment]
Added [onbehalfof@manuscriptcentral.com](mailto:onbehalfof@manuscriptcentral.com) as a member to the Google Group for journal-submit@datadryad.org.

Note that ScholarOne fails standard email authentication checks for SPF, DKIM, and DMARC. I suggested that they add these authentication methods to their system.
