### ISSUE TITLE
med-high priority: transfer ownership of dataset

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3810]
Hello, I have a dataset that needs the ownership transferred as soon as possible.

DOI: 10.5061/dryad.fn2z34tvc
Resource ID: 331538

New owner ORCID: 0000-0002-7991-1514
New owner name: Marijke Achterberg
New owner email: e.j.m.achterberg@uu.nl

**Comment by ahamelers** [comment]
Done
