### ISSUE TITLE
GitHub permissions for repo creation

### ISSUE THREAD

**Issue by jeremywalter** [datadryad/dryad-product-roadmap#3819]
**Problem description, and links to relevant helpdesk tickets:**
Curation team needs a private space for task tracking and a central hub for resources connected to curation. 

**Describe the solution you'd like:**
I would like to create a private repository for the curators to track tickets and organized resources. If I can have permissions to do so I am happy to manage it myself. Otherwise I would like to have a curation-team repo that is private that we can add just the curators to.

**Additional context:**
Please ping me here or in slack with any questions or concerns!

**Comment by ahamelers** [comment]
https://github.com/datadryad/curation
