### ISSUE TITLE
Assign sponsorship to datasets

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3826]
An author created four datasets but had not yet signed in to their tenant before they submitted. They have successfully signed in, so the datasets should be attributed to Montana State University:

DOI: 10.5061/dryad.v15dv426j
DOI: 10.5061/dryad.12jm63z80
DOI: 10.5061/dryad.18931zd6t
DOI: 10.5061/dryad.rv15dv4jh

**Comment by ahamelers** [comment]
These are all in 'action required'. I've updated the resources in the database, but I think that may have been unnecessary and would have happened automatically when the user made and submitted a new version, and I don't think it will be reflected on the activity logs or anything until the user makes and submits a new version.

**Comment by lauradryad** [comment]
Oh! I didn't realize that.. sorry for the trouble then! I thought they had to add their affiliation from inside the dataset for that to work. Noted!
