### ISSUE TITLE
Multiple versions created on same dataset (10.5061/dryad.tdz08kq62)

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3827]
This author created multiple versions of the same dataset in a span of two minutes (in September). I'm guessing that the 316630 resource ID is probably the most up to date one that should be kept since the author edited it today, but they should all be pretty similar. If you're able, the one to keep should have a csv file in the files (in addition to the fastq) and a note in the abstract that describes several related datasets.

**Comment by ahamelers** [comment]
I have tried to assign version numbers to these extra versions in a way that makes sense. If you want it reverted from the new version 4 to some previous version, let me know (or create a 'New version based on previous')
