### ISSUE TITLE
Fix status of auto-published dataset(s)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3830]
The status of this dataset is “Published”, citation mentions update is ‘forthcoming’: **10.5061/dryad.573n5tbgd** 

Note: @ahamelers fix weirdness here (possibly caused by auto-publication) when a ticket is created

**Comment by ahamelers** [comment]
Created a change going forward to use the existing publication date for auto-published submissions. Will fix existing auto-published with no pub dates in the db.
