### ISSUE TITLE
Version issue with nvx0k6f22

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3840]
The author of this dataset created two in progress versions within the same minute and then submitted them in reverse order, causing the Data files box to look like we can time travel. 

The Dec 19 version (335412) is the most up to date and correct one, but as it doesn't appear last in the list on the landing page, I am worried if I hit publish on it, it will publish the Dec 18 version [please note, this does require further edits so it should still be in curation status]. 

Please delete the Dec 18 version (335413).

**Comment by ahamelers** [comment]
I've kept all the versions, but made 335412 version 3/the latest version, so if you go to curate this now that should be the version you access, and any future version should be created from it as a basis
