### ISSUE TITLE
The dataset with paths for filenames doesn't work for individual file downloads

### ISSUE THREAD

**Issue by sfisher** [datadryad/dryad-product-roadmap#569]
As predicted, it's not a good idea to hack in data for things you don't actually support in your application, but of course we did so anyway.

The old Dash dataset where we did this has individual file downloads failing.  It seems like slashes are double-encoded when sent to Merritt Express--either just because we're doing something wrong or because Merritt used to require double encoding of slashes (as I recall, it did a long while back) and we haven't changed it.

The full dataset download works, so people can get at the data if they want it, but it would be nice to fix, but I don't think we should drop everything for this one-off dataset that didn't want to play by the rules, though.  We can work it in, maybe in in this or our next sprint.  I hope it's just a tiny little fix.

A little info about it.

```
Resource:
id	download_uri	identifier_id
30608	https://merritt.cdlib.org/d/ark%3A%2Fb7272%2Fq6057cv6	29620

Identifier:
id	identifier	identifier_type	storage_size	created_at	updated_at	latest_resource_id	license_id	invoice_id	pub_state
29620	10.7272/Q6057CV6	DOI	4031446175	2016-11-17 00:19:54	2019-10-09 06:41:54	30608	cc0	NULL	published
```

**Comment by ryscher** [comment]
Funny enough, these files download just fine now that we're not going through all of the Merritt machinery. But it is probably dependent on the fact that AWS uses slashes to denote folders, similar to a filesystem. 

I agree with Scott that the slashes were always a terrible idea and they will eventually cause problems...this is why we filter them out for new deposits. But they're not worth fixing in this dataset until the problems actually happen.
