### ISSUE TITLE
Copyright in footer

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#750]
The website footer says "Copyright (c) 2019 Dryad". We should programmatically update it to always show the current year.

Or perhaps change it entirely? The Terms of Service states that all content on the website is CC-BY, so it seems disingenuous to have a copyright statement without mentioning the CC-BY.

**Comment by sfisher** [comment]
Huh.  the date seems to be updating now.  Is everything on the site really CC-BY?  I didn't realize.
