### ISSUE TITLE
Fix Dryad migrated filenames that have leading or trailing spaces.

### ISSUE THREAD

**Issue by sfisher** [datadryad/dryad-product-roadmap#836]
Terry pointed this out.  See notes at https://github.com/CDLUC3/mrt-doc/issues/442 .

My response.

It looks like the one you mentioned at https://datadryad.org/stash/dataset/doi:10.5061/dryad.k6t16 was failing because of an extra space in front of the filename in our database compared to the version in Merritt. It looks like this was probably migrated incorrectly from the old Dryad system. I'll put in a ticket to look for these types of issues to fix.

We originally got this error.

```
Merritt couldn't create presigned URL for http://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5j72jfz/1/producer%2F%20Mu%CC%88ller%20et%20al.%202016%20Journal%20of%20Ecology%20%282%29%20seeds.xls?no_redirect=true
Http status code: 404
```

But it works when removing the extraneous space in the filename, so doesn't seem to be so much an encoding issue as an issue where the filenames between the two systems didn't match up. I'm not sure if there are other problems in there.

The original filename in the database was " Müller et al. 2016 Journal of Ecology (2) seeds.xls" (note extra space at first).  It works when removing this space.

We should probably look for filenames like this and fix them if there are others present.

**Comment by sfisher** [comment]
Seems like an easy thing to check and fix to me.

**Comment by ryscher** [comment]
Seems to have been fixed by the migration to Dryad v3
